// 我的品飲清單
// 新增酒款只要往陣列裡塞一筆。所有欄位都會自動帶到 UI。
// id 必填且唯一；image 留 null 會用 SVG 酒瓶插畫，填 URL 會用照片。
//
// style_axis：風格光譜（主觀定位）。0 = 國際風格 / 高度標準化，
//   100 = 風土個性 / 反標準化。新增酒款時憑感覺給個 0–100 就好。
// style_note：一句話說明為什麼放在這個位置（modal 詳情頁會顯示）。
//
// rating 一律由站主本人親口給；沒喝過 / 還沒打分 = null（顯示「待品飲」）。
//   絕不代填、不引用酒評家分數。notes_long 是站主自己的筆記（個人感受）。
//
// 購入資訊：price = 購入單價（新台幣，數字）；bottles = 購入瓶數；
//   price_estimated = true 代表單價是推估（收據未列）；
//   market_price_twd = 市場行情參考價帶（字串，純參考、非評分）。
// 知識欄位（modal 詳情頁會分區顯示，皆為事實／教育性內容，不含個人評價）：
//   producer_note 酒莊、varietal_note 品種小知識、region_note 產區風土、
//   vinification_note 釀法、classification / classification_note 產區分級、
//   why_beginner 為什麼適合新手、background 深入認識、tasting_focus 品飲練習重點、
//   sweetness 甜度、drink_window 適飲期、serve_temp 飲用溫度、decant 醒酒建議、pairing_note 配餐邏輯。
//   長欄位（vinification_note / background / tasting_focus 等）可用空行（\n\n）分段，modal 會自動拆成多段。
// highlights：看點陣列（3–5 條短句），會顯示在 modal 上方做亮點導讀。
// appearance：外觀描述（一句話），與 aroma／palate／finish 同屬品飲區。
//
// 譯名統一：Tenuta Carretta=卡蕾塔、Tenuta Pederzana=佩德札納、
//   Lambrusco=蘭布魯斯科、Grasparossa=葛拉斯帕羅薩、Castelvetro=卡斯特爾韋特羅、
//   Nizza=尼薩、Roero=羅埃羅、Alto Adige=上阿迪杰。

export const drinks = [
  {
    id: 'pinot-nero-eppan',
    region_key: 'trentino-alto-adige',
    category: 'wine',
    type: 'red',
    type_zh: '紅酒',
    name_en: 'St. Michael-Eppan Pinot Nero',
    name_zh: '聖米歇爾-艾本 黑皮諾',
    producer: 'St. Michael-Eppan',
    varietal: 'Pinot Nero',
    varietal_zh: '黑皮諾',
    region: 'Alto Adige',
    region_zh: '上阿迪杰',
    country: 'Italy',
    country_zh: '義大利',
    year: 2023,
    abv: 13.5,
    sweetness: '乾型',
    classification: 'Alto Adige DOC',
    price: 1200,
    bottles: 1,
    price_tier: '$$',
    market_price_twd: '約 NT$900–1,400',
    rating: 5,
    tasting_date: '2026-06-03',
    occasion: '人生第一支紅酒',
    aroma: ['紅櫻桃', '覆盆子', '黑莓', '紫羅蘭', '些許香料'],
    palate: ['中等酒體', '單寧細柔', '酸度清爽'],
    finish: '柔順收尾，紅果與淡淡香料尾韻',
    pairing: ['烤雞', '滷肉', '菇類料理', '鮭魚生魚片'],
    pairing_note: '黑皮諾單寧細、酸度清爽，能襯托白肉與菇類的鮮味又不搶味，連油脂豐厚的鮭魚生魚片或台式滷肉都接得住。',
    varietal_note: '黑皮諾（義大利文 Pinot Nero、法文 Pinot Noir）是出了名嬌貴難種的紅葡萄，但釀出的酒單寧細柔、酸度清爽、果香鮮明，是公認最好入口的紅酒之一。它怕熱、偏好冷涼氣候，因此上阿迪杰這種高海拔山區特別適合，能保留紅櫻桃、覆盆子般的清新果味。對新手來說，它沒有粗澀厚重的單寧，是從白酒跨進紅酒世界很友善的橋樑。',
    region_note: '上阿迪杰位於義大利最北端、靠近奧地利的阿爾卑斯山區，是公認義大利最會做黑皮諾的產區；高海拔（葡萄園約 400–550 公尺）日夜溫差大，賦予紅酒清爽酸度與優雅果香。',
    classification_note: 'DOC（法定產區）是義大利的中階品質分級，代表產地、品種與釀法都受法規規範；標單一品種的酒，該品種要占至少 85%。這支屬酒莊入門的「Classic」系列，不是頂級的 Sanct Valentin 珍藏版，但已能展現產區水準。',
    producer_note: '聖米歇爾-艾本是上阿迪杰最受敬重的合作社酒莊之一，1907 年創立，由三百多位酒農、近 385 公頃葡萄園組成；曾被 Gambero Rosso／Slow Food《義大利葡萄酒指南》選為「2000 年度最佳義大利酒莊」，以細膩優雅著稱。',
    why_beginner: '單寧細柔、酸度清爽、沒有粗澀厚重感，是最好入口的紅酒之一，還能稍微冰一下喝，很適合台灣天氣，對紅酒新手非常友善。',
    drink_window: '現在 – 2028',
    serve_temp: '14–16°C',
    decant: '不一定要醒酒；想讓香氣更開展，可開瓶後靜置或醒 15–20 分鐘，並稍微冰鎮（約 14–16°C）後享用。',
    background: '上阿迪杰是公認義大利最會做黑皮諾的產區，位在義大利最北端的阿爾卑斯山區，高海拔與大日夜溫差賦予紅酒清爽酸度與優雅果香。St. Michael-Eppan 是 1907 年創立、由三百多位酒農組成的頂級合作社，曾被 Gambero Rosso／Slow Food 選為 2000 年度最佳義大利酒莊。這支是入門的「Classic」系列（不是頂級的 Sanct Valentin 珍藏版）：於不鏽鋼槽發酵，再有一部分放進大木桶（grandi botti）陳年，增添柔順度。酒色石榴紅，乾型、酒精約 13.5%。',
    notes_short: '義大利最強黑皮諾產區的可靠大牌，入門紅酒天花板',
    notes_long: '我的第一支紅酒，超好喝！整體很順口、輕盈好入口。',
    color_hex: '#9E2B3C',
    beginner_friendly: true,
    style_axis: 60,
    style_note: '黑皮諾是最國際化的紅葡萄，但上阿迪杰的高山冷涼風土辨識度高，加上頂級合作社的不鏽鋼＋大木桶（grandi botti）傳統釀法——兩股力量拉鋸，落在中間略偏風土。',
    image: null,
  },
  {
    id: 'barbera-nizza-carretta',
    region_key: 'piemonte',
    category: 'wine',
    type: 'red',
    type_zh: '紅酒',
    name_en: 'Tenuta Carretta Bricco Manera',
    name_zh: '卡蕾塔 巴貝拉 馬內拉園',
    producer: 'Tenuta Carretta',
    varietal: 'Barbera',
    varietal_zh: '巴貝拉',
    region: 'Nizza, Piedmont',
    region_zh: '尼薩',
    country: 'Italy',
    country_zh: '義大利',
    year: 2020,
    abv: 14.5,
    sweetness: '乾型',
    classification: 'Nizza DOCG',
    price: 1300,
    bottles: 1,
    price_tier: '$$',
    market_price_twd: '約 NT$1,000–1,500',
    rating: null,
    tasting_date: '2026-06-03',
    occasion: '在家品飲',
    aroma: ['黑櫻桃', '成熟李子', '紫羅蘭', '香料', '香草橡木'],
    palate: ['多汁', '酸度爽朗', '中等至飽滿酒體'],
    finish: '尾韻悠長帶香料感，整體柔順和諧、不咬口',
    pairing: ['紅燒牛肉麵', '滷味', '三杯雞', '番茄肉醬麵', '煎烤豬排'],
    pairing_note: '巴貝拉爽朗的酸度能切開油脂、提亮醬汁鹹香，所以特別搭得起台灣常見的紅燒、滷味與帶醬汁的料理。',
    varietal_note: '巴貝拉是皮埃蒙特最親民的紅葡萄品種：天生酸度爽朗、單寧不重，所以喝起來多汁順口、不咬口。它的果味直接（黑櫻桃、李子），對新手非常友善，常被當作認識義大利紅酒的入門品種。',
    region_note: '尼薩位於皮埃蒙特的蒙費拉托丘陵，是巴貝拉的核心精華區。這款酒的果實來自蒙巴魯佐（Mombaruzzo）一帶的向陽坡地，被視為展現巴貝拉最佳風味的搖籃。',
    classification_note: 'Nizza DOCG 是巴貝拉的最高等級分級：必須 100% 用巴貝拉，只能來自尼薩一帶精選坡地，並要求最低 18 個月陳年（含至少 6 個月木桶），是義大利最嚴格的法定產區之一。簡單說，看到「Nizza DOCG」就代表這是巴貝拉裡最講究的一群。',
    producer_note: '卡蕾塔酒莊的歷史可追溯到 1467 年一份提及「cassina Careta」的契約，是皮埃蒙特最古老的酒莊之一，莊園位於阿爾巴近郊的 Piobesi d’Alba，1985 年起由阿爾巴的 Miroglio 家族接手經營，強調風土表現。',
    why_beginner: '巴貝拉酸度活潑、單寧柔和，喝起來多汁順口不咬口，是認識義大利紅酒非常友善的入門選擇；唯一要留意的是這款酒精偏高（約 14.5%），建議搭餐慢慢喝。',
    drink_window: '現在 – 2028',
    serve_temp: '16–18°C',
    decant: '建議開瓶前先醒酒約 30–60 分鐘，能讓果香與香料氣息更開展；不醒也可直接喝。',
    background: '這支由皮埃蒙特歷史可追溯到 1467 年的卡蕾塔酒莊釀造，100% 巴貝拉，果實來自尼薩產區蒙巴魯佐（Mombaruzzo）一帶的向陽坡地。Nizza 自 2014 年起獨立成為法定產區，是義大利第一個專屬巴貝拉的最高等級分級。這款 Bricco Manera 是酒莊的標準款（非珍藏級 Mora di Sassi），約於橡木桶陳年 12 個月、再瓶中陳放至少 12 個月，超過 Nizza DOCG 規定的最低門檻。酒色濃郁寶石紅，帶巴貝拉典型的紫羅蘭光澤。',
    notes_short: '皮埃蒙特逾五百年老莊釀的最高等級巴貝拉，多汁柔順、酸度討喜的入門紅酒',
    notes_long: null,
    color_hex: '#6E1530',
    beginner_friendly: true,
    style_axis: 72,
    style_note: '100% 巴貝拉、Nizza DOCG 的嚴格產區規範與蒙巴魯佐向陽坡風土，讓它偏向「風土個性」一端；橡木桶陳年帶來一些國際化的圓潤香草感，因此沒有更極端。',
    image: null,
  },
  {
    id: 'arneis-cayega-carretta',
    region_key: 'piemonte',
    category: 'wine',
    type: 'white',
    type_zh: '白酒',
    name_en: 'Cayega Roero Arneis',
    name_zh: '卡蕾塔 卡耶加 阿內斯',
    producer: 'Tenuta Carretta',
    varietal: 'Arneis',
    varietal_zh: '阿內斯',
    region: 'Roero, Piedmont',
    region_zh: '羅埃羅',
    country: 'Italy',
    country_zh: '義大利',
    year: 2023,
    abv: 13.5,
    sweetness: '乾型',
    classification: 'Roero Arneis DOCG',
    price: 1100,
    bottles: 1,
    price_tier: '$$',
    market_price_twd: '約 NT$900–1,200',
    rating: null,
    tasting_date: '2026-06-03',
    occasion: '在家品飲',
    aroma: ['西洋梨', '白桃', '柑橘', '白花', '燧石礦物'],
    palate: ['乾型圓潤', '酸度清爽', '礦物尾韻'],
    finish: '乾淨清爽，礦物與柑橘回韻悠長',
    pairing: ['清蒸魚', '生魚片', '鹽水蝦', '白灼海鮮', '涼拌菜'],
    pairing_note: '清爽的酸度與礦物感能解海鮮的鮮甜、壓住腥味，又因為不過桶、沒有橡木味，不會蓋過清淡料理的本味。',
    varietal_note: '阿內斯（Arneis）是皮埃蒙特的原生白葡萄。坊間常說它的名字在當地方言意思接近「小淘氣」，用來形容它難種、不好照顧（這說法很流行，但語源其實有爭議）。它二十世紀中葉曾一度近乎絕種，後來才被救回。釀出的白酒屬乾型但口感柔順圓潤，帶西洋梨、白桃與白花香，酸度溫和不尖銳，是很好入口的入門白酒。',
    region_note: '羅埃羅在皮埃蒙特、塔納羅河左岸，與對岸名滿天下的 Barolo、Barbaresco 隔河相望，是個低調的小產區，以清新的阿內斯白酒和優雅的內比歐露紅酒聞名。',
    classification_note: 'DOCG 是義大利葡萄酒分級的最高一級，規範比 DOC 更嚴格。Roero Arneis DOCG 規定至少要用 95% 的阿內斯葡萄，等於替「這是道地皮埃蒙特阿內斯白酒」做了官方背書。',
    producer_note: '卡蕾塔莊園位於皮埃蒙特羅埃羅產區的 Piobesi d’Alba，源頭可追溯到 1467 年的一份土地契約，是義大利歷史最悠久的酒莊之一；1985 年起由 Miroglio 家族接手經營至今。',
    why_beginner: '乾型但口感柔順圓潤、酸度溫和不刺激，又沒有橡木桶的味道，果香花香清楚易懂，是最容易上手、配台式海鮮也不會出錯的入門白酒。',
    drink_window: '現在 – 2027',
    serve_temp: '8–10°C',
    decant: '不需要醒酒，直接冰透開瓶即可；阿內斯白酒講究新鮮，現開現喝最能表現果香與酸度。',
    background: '阿內斯是皮埃蒙特的原生白葡萄，因為難種，二十世紀中葉曾一度近乎絕種，靠卡蕾塔等在地酒莊保留老藤、加上 1970 年代的復興才被救回。Cayega 採 100% 阿內斯，在不鏽鋼槽中陳化約半年、帶細緻酒渣（lees，即發酵後沉澱的酵母，能增添口感厚度），全程不過橡木桶，主打清新風格（酒莊另有過桶的頂級版 Canorei）。Roero Arneis 是 DOCG 最高分級，規定至少 95% 阿內斯。酒色金黃帶綠光，建議冰到 8–10°C、趁年輕喝。',
    notes_short: '皮埃蒙特軟順白酒，海鮮絕配、超好入口',
    notes_long: null,
    color_hex: '#E6DCA2',
    beginner_friendly: true,
    style_axis: 73,
    style_note: '阿內斯是皮埃蒙特近乎絕種、被在地酒莊救回的原生白葡萄，產區極小、不鏽鋼槽不過桶保留品種與風土本味——非常風土那一端；清爽討喜的風格讓它依然好親近。',
    image: null,
  },
  {
    id: 'lambrusco-grasparossa-tradizione',
    region_key: 'emilia-romagna',
    category: 'wine',
    type: 'sparkling-red',
    type_zh: '氣泡紅酒',
    name_en: 'Grasparossa della Tradizione',
    name_zh: '傳統葛拉斯帕羅薩',
    producer: 'Tenuta Pederzana',
    varietal: 'Lambrusco Grasparossa',
    varietal_zh: '蘭布魯斯科（葛拉斯帕羅薩）',
    region: 'Castelvetro, Emilia-Romagna',
    region_zh: '卡斯特爾韋特羅',
    country: 'Italy',
    country_zh: '義大利',
    year: 2023,
    abv: 11.5,
    sweetness: '乾型',
    classification: 'Lambrusco Grasparossa di Castelvetro DOC',
    price: 720,
    bottles: 6,
    price_tier: '$',
    market_price_twd: '約 NT$650–950',
    rating: 4,
    tasting_date: '2026-06-03',
    occasion: '在家品飲',
    aroma: ['黑櫻桃', '野莓', '肉桂', '石墨', '紫羅蘭'],
    palate: ['中等酒體', '細緻氣泡', '柔順單寧'],
    finish: '乾爽收尾，帶櫻桃果韻與一絲細微單寧',
    pairing: ['千層麵與紅醬義大利麵', '義式臘腸冷盤', '鹹酥雞與炸物', '滷味', '陳年硬質乳酪'],
    pairing_note: '乾型葛拉斯帕羅薩的氣泡與酸度能洗去油脂、單寧又對得起肉香，所以無論義式油潤料理、還是台式炸物、滷味都很合拍。',
    varietal_note: '葛拉斯帕羅薩（Grasparossa）是蘭布魯斯科大家族裡顏色最深、單寧最明顯、酒體也最厚實的一支，名字來自秋天會轉紅的葡萄梗。和清爽花香的 Sorbara 不同，它喝起來更像「會冒泡的紅酒」，是想從白氣泡跨到紅酒的新手很好的橋樑。',
    region_note: '卡斯特爾韋特羅是摩典納南方的丘陵帶，被視為葛拉斯帕羅薩最經典的故鄉，這裡的版本顏色更深、酒體更有勁。也是巴薩米可醋與帕瑪森乳酪的同鄉，飲食文化偏濃郁油潤，氣泡紅酒正好解膩。',
    classification_note: 'DOC 是義大利第二高的法定產區等級。看到「卡斯特爾韋特羅葛拉斯帕羅薩 DOC」，代表它受產區規範約束——至少 85% 用葛拉斯帕羅薩、限定摩典納一帶丘陵產地。等級越高，產地與品種的綁定就越嚴格。',
    producer_note: '佩德札納是摩典納卡斯特爾韋特羅一帶的家族小農酒莊，園區位於 Solignano Vecchio 丘陵，幾乎只種葛拉斯帕羅薩，走手工採收、忠於風土的路線；他們甚至保留了一支自家篩選、曾與波隆那大學合作研究的獨特老品系（clone，即從同一株母藤複製出的品系）。',
    why_beginner: '氣泡讓單寧顯得柔順、酒精也不高（約 11.5%），喝起來比一般靜態紅酒輕鬆，是想嘗試「紅酒口感」又怕太澀的新手很好的入門選擇；只是它是乾型，比甜味蘭布魯斯科多一點骨架。',
    drink_window: '現在 – 2027',
    serve_temp: '12–14°C',
    decant: '不需要醒酒；氣泡酒開瓶即飲，稍微冰鎮就好，醒酒反而會讓氣泡跑掉。',
    background: '這支由家族小農酒莊 Tenuta Pederzana（佩德札納）釀造，屬卡斯特爾韋特羅 DOC，用的是蘭布魯斯科家族裡顏色最深、最有酒體的葛拉斯帕羅薩。它是乾型（secco），和超市常見的甜味蘭布魯斯科很不一樣——多了單寧骨架、少了甜。葡萄手工採收，於水泥槽培養約七個月，再經自然二次發酵產氣，走較手工、忠於風土的做法，不是工業化大槽量產。酒精約 11.5%，稍微冰鎮後最能凸顯果香與氣泡活力。',
    notes_short: '顏色深、單寧柔、乾型的「氣泡紅酒」，小農風土版蘭布魯斯科',
    notes_long: '乾型的氣泡紅，清爽解膩，比想像中好入口。',
    color_hex: '#5A1320',
    beginner_friendly: true,
    style_axis: 75,
    style_note: '原生品種葛拉斯帕羅薩＋家族獨家老品系、水泥槽培養與自然二次發酵的小農做法，刻意保留產地個性而非追求國際討喜，明顯偏風土那一端。',
    image: null,
  },
  {
    id: 'lambrusco-spiriti-folletti',
    region_key: 'emilia-romagna',
    category: 'wine',
    type: 'sparkling-red',
    type_zh: '氣泡紅酒',
    name_en: 'Spiriti Folletti',
    name_zh: '頑皮精靈 葛拉斯帕羅薩',
    producer: 'Tenuta Pederzana',
    varietal: 'Lambrusco Grasparossa',
    varietal_zh: '蘭布魯斯科（葛拉斯帕羅薩）',
    region: 'Castelvetro, Emilia-Romagna',
    region_zh: '卡斯特爾韋特羅',
    country: 'Italy',
    country_zh: '義大利',
    year: null,
    abv: 11,
    sweetness: '乾型',
    classification: 'Lambrusco Grasparossa di Castelvetro DOC',
    price: 800,
    price_estimated: true,
    bottles: 2,
    price_tier: '$$',
    market_price_twd: '約 NT$700–1,000',
    rating: 3.8,
    tasting_date: '2026-06-03',
    occasion: '在家品飲',
    aroma: ['黑櫻桃', '野草莓', '紫羅蘭', '李子', '些許土壤氣息'],
    palate: ['細緻氣泡', '明亮酸度', '明顯而細緻的單寧'],
    finish: '尾韻乾爽、帶鹹鮮感，單寧明顯但不刺口，餘味留有莓果清新',
    pairing: ['鹹酥雞與炸物', '台式香腸', '滷味', '披薩', '帕瑪森乳酪火腿冷盤'],
    pairing_note: '微氣泡與酸度能解膩、清爽口腔，特別適合台灣的鹹酥雞、香腸與滷味。',
    varietal_note: '葛拉斯帕羅薩（Grasparossa）是蘭布魯斯科大家族裡顏色最深、單寧最明顯、酒體也最厚實的一支，名字來自秋天會轉紅的葡萄梗。和清爽花香的 Sorbara 不同，它喝起來更像「會冒泡的紅酒」，是想從白氣泡跨到紅酒的新手很好的橋樑。',
    region_note: '卡斯特爾韋特羅是摩典納南方的丘陵帶，被視為葛拉斯帕羅薩最經典的故鄉；相較於平原區的蘭布魯斯科，這裡的丘陵與黏土被認為能釀出更有層次、結構更扎實的版本。',
    classification_note: 'DOC 是義大利的法定產區認證。這支來自葛拉斯帕羅薩最核心的卡斯特爾韋特羅產區，法規要求至少 85% 用葛拉斯帕羅薩，而這支更採 100%，等於替你把關了品種與產地的純正度。',
    producer_note: '與「傳統款」同一家：佩德札納家族酒莊，專注葛拉斯帕羅薩。這支用的是酒莊自家保存的歷史老品系、手工採收，是一座規模約十幾公頃的小型家族園，產量不大。',
    why_beginner: '不甜、酒精僅約 11%、帶清爽氣泡與莓果香，單寧雖然比一般蘭布魯斯科明顯，但仍細緻、又能解膩，是很友善的氣泡紅酒入門款。',
    drink_window: '現在 – 2027',
    serve_temp: '12–14°C',
    decant: '不需要醒酒；氣泡紅酒講求新鮮，冰鎮後直接倒進杯子喝即可。',
    background: '「Spiriti Folletti（頑皮精靈）」同樣出自家族酒莊 Tenuta Pederzana（佩德札納），葡萄手工採收自 Solignano Vecchio 的丘陵園，採酒莊自家保存的老品系、100% 葛拉斯帕羅薩。釀法為不鏽鋼槽主發酵後，於加壓鋼槽進行二次發酵產生氣泡（Charmat 法，即在大鋼槽裡產氣的氣泡酒做法），屬乾型（secco）微氣泡紅酒，酒精約 11%。它和同酒莊的傳統款一樣不甜，但單寧更明顯一些。市面多以非年份（NV）販售。',
    notes_short: '來自核心產區的家族小農微氣泡紅酒，不甜、莓果香、解膩好搭',
    notes_long: '氣泡跟莓果味很討喜，尾韻稍微澀一些，沒有前一支那麼滑。',
    color_hex: '#5A1226',
    beginner_friendly: true,
    style_axis: 62,
    style_note: '出自核心卡斯特爾韋特羅產區、家族小農、堅持自家老品系，風土個性鮮明；但仍採鋼槽二次發酵（Charmat 法）的量產工藝、風格平易，因此偏向風土端但不極端。',
    image: null,
  },
  {
    id: 'lambrusco-cella',
    region_key: 'emilia-romagna',
    category: 'wine',
    type: 'sparkling-red',
    type_zh: '氣泡紅酒',
    name_en: 'Cella Lambrusco Amabile',
    name_zh: 'Cella 微甜蘭布魯斯科',
    producer: 'Fratelli Cella',
    varietal: 'Lambrusco',
    varietal_zh: '蘭布魯斯科',
    region: 'Emilia',
    region_zh: '艾米利亞',
    country: 'Italy',
    country_zh: '義大利',
    year: null,
    abv: 8,
    sweetness: '微甜',
    classification: 'Lambrusco dell\'Emilia IGT',
    price: 279,
    bottles: 1,
    price_tier: '$',
    market_price_twd: '約 NT$250–350',
    rating: 3.5,
    tasting_date: '2026-06-04',
    occasion: '簡單小聚會',
    aroma: ['紅櫻桃', '草莓', '葡萄果汁', '淡淡紫羅蘭'],
    palate: ['微甜', '輕氣泡', '酒體輕盈'],
    finish: '收尾短而甜潤，氣泡輕快、單寧幾乎感覺不到，餘味是直接的莓果與葡萄汁感',
    pairing: ['瑪格麗特披薩', '鹹酥雞', '炸雞', '美式炸物', '派對小點'],
    pairing_note: '微甜加上輕氣泡，最適合解油炸、鹹香的派對食物——披薩、炸雞、鹹酥雞都很對味；甜度也讓不太能接受乾型紅酒的朋友更容易入口。冰涼喝最舒服，當輕鬆聚會的「氣泡飲料感」紅酒就對了。',
    varietal_note: '蘭布魯斯科其實不是單一品種，而是一個有數十個成員的大家族。這支不像你的兩支葛拉斯帕羅薩只用單一品系，而是把多個品系混在一起調配（Salamino、Grasparossa、Marani、Maestri），目的是釀出風味穩定、討喜易飲的量產酒。對新手來說，記住「蘭布魯斯科＝微氣泡的紅葡萄酒家族」就夠了，甜的、乾的都有。',
    region_note: '艾米利亞-羅馬涅是蘭布魯斯科的大本營，也是巴薩米可醋、帕瑪森乳酪、義式火腿的故鄉，當地飲食濃郁油潤，微氣泡紅酒正好用來解膩配餐。IGT 標示的「艾米利亞」涵蓋範圍很廣，給了量產酒廠跨多個產區採購葡萄、調配穩定風味的彈性。',
    classification_note: 'IGT（地理標示保護）是義大利葡萄酒分級裡較寬鬆的一級，只規範葡萄大致來自某個地理範圍（這裡是「艾米利亞」），對品種、產量、釀法的限制都比 DOC 鬆很多。你另外兩支葛拉斯帕羅薩是 DOC（法定產區），產地與品種綁定更嚴格、更講究；這支是 IGT，等於給了酒廠較大的混調與量產彈性。簡單記：DOC 比 IGT 更嚴、更看重產地個性。',
    producer_note: 'Fratelli Cella（雀拉）創立於 1960 年，總部在艾米利亞-羅馬涅的 Campegine，是義大利最知名的商業蘭布魯斯科品牌之一，行銷全球四十多國，隸屬大型釀酒合作社聯盟 Cantine Riunite & CIV，走規模化、標準化的量產路線。',
    why_beginner: '微甜、輕氣泡、酒精很低（約 8%），喝起來幾乎像有氣泡的莓果葡萄汁，沒什麼單寧澀感，是怕紅酒苦澀的新手最沒壓力的入門選擇；價格親民、超市就買得到，當派對輕鬆飲也很合適。',
    drink_window: '趁新鮮喝（NV，越快越好）',
    serve_temp: '6–8°C（冰透喝最解膩）',
    decant: '不需要醒酒；氣泡酒講求新鮮，冰透後直接開瓶倒進杯子即可，醒酒反而會讓氣泡跑掉。',
    background: '這支由 Fratelli Cella（雀拉，創立於 1960 年）釀造，隸屬大型釀酒合作社 Cantine Riunite & CIV，屬 Lambrusco dell\'Emilia IGT。它是典型的「超市甜型蘭布魯斯科」：微甜（Amabile）、輕氣泡（Frizzante）、酒精僅約 8%，由多個蘭布魯斯科品系混調、規模化量產，主打討喜易飲、風味穩定。它和你另外兩支佩德札納的葛拉斯帕羅薩剛好形成鮮明對比：那兩支是小農手工、乾型、單一品系、DOC 法定產區、強調風土個性；這支則是合作社量產、微甜、多品系混調、IGT 寬鬆分級、走國際大眾口味。沒有好壞之分，只是定位不同——就是平價、輕鬆、隨手喝的派對氣泡紅。',
    notes_short: '超市平價微甜輕氣泡紅，低酒精、解膩好入口的派對酒',
    notes_long: '全聯架上隨手帶的，才 279，本來就沒抱期待。微甜、帶點氣泡，冰透了配披薩、炸雞意外順口；尾韻確實有那麼一絲廉價酒精感，但這價錢真的沒什麼好嫌的。不是會讓你停下來細品的酒，而是簡單小聚、請朋友隨興喝，或自己在家配宵夜的那種「日常款」——3.5 分，老實講是給它的 CP 值。',
    color_hex: '#7A1B2E',
    beginner_friendly: true,
    style_axis: 15,
    style_note: '典型的工業量產、超市派蘭布魯斯科：大型合作社規模化生產、多品系混調、IGT 彈性分級、走微甜討喜的國際大眾口味，刻意追求風味穩定一致而非凸顯產地個性，因此明顯落在「國際標準化」這一端。對照兩支佩德札納小農乾型葛拉斯帕羅薩（風土端），差異一目了然。',
    image: null,
  },
  {
    id: 'cave-mont-blanc-blanc-du-blanc',
    region_key: 'valle-aosta',
    category: 'wine',
    type: 'sparkling-white',
    type_zh: '氣泡白',
    name_en: 'Blanc du Blanc Brut · Metodo Classico',
    name_zh: '白朗峰 中白傳統法氣泡',
    producer: 'Cave Mont Blanc',
    varietal: 'Prié Blanc',
    varietal_zh: '普里耶白',
    region: 'Valle d\'Aosta',
    region_zh: '奧斯塔谷',
    country: 'Italy',
    country_zh: '義大利',
    year: null,
    abv: 11.5,
    sweetness: '乾型（Brut）',
    classification: 'Valle d\'Aosta DOC',
    price: null,
    bottles: null,
    price_tier: '$$',
    market_price_twd: '約 NT$1,000–1,400（國際零售推估）',
    rating: null,
    tasting_date: '2026-06-18',
    occasion: '越昇環義品飲課程 · 高海拔雙產區',
    highlights: [
      '歐洲最高酒廠：在海拔 2,173m 的纜車站釀氣泡',
      '未嫁接的「前根瘤蚜時代」純血老藤，全球罕見',
      '與香檳同源的傳統瓶中二次發酵（Metodo Classico）',
      '奧斯塔谷原生稀有品種，離開產區幾乎喝不到',
    ],
    appearance: '明亮麥稈黃帶綠色反光，氣泡細緻而持久。',
    aroma: ['紫藤白花', '青蘋果', '柑橘皮', '礦石', '一絲番紅花'],
    palate: ['鮮爽', '酸度為骨幹', '礦物感明顯', '綿密氣泡', '酒體輕盈'],
    finish: '礦石主導、乾淨俐落的尾韻，帶柑橘與「濕岩石」般的清涼餘味，持久而優雅。',
    pairing: ['生蠔', '握壽司', '生魚片', '天婦羅', '鹹酥雞', '清蒸海鮮'],
    pairing_note: '高酸與礦物鹹感能把油脂洗乾淨、替海鮮提鮮，氣泡又解炸物的膩，是最百搭的開場酒；避免重醬、重辣，以免蓋過它清秀的高山個性。',
    varietal_note: '普里耶白（Prié Blanc）是奧斯塔谷的原生稀有白葡萄，幾乎只種在白朗峰腳下的 Morgex 與 La Salle 兩個鄉鎮，是全義大利最「在地限定」的品種之一，最早文獻可追溯到 1691 年。它極早熟（九月初就採收）、果皮極薄、天生高酸、酒精偏低——正是它做氣泡酒能保持鮮爽骨架的本錢。對新手來說，這是一支離開產區幾乎喝不到的品種，喝它本身就是在認識一個你可能一輩子只會遇到一兩次的葡萄。',
    region_note: '奧斯塔谷是義大利面積最小、海拔最高、最靠阿爾卑斯的葡萄酒產區，就位在白朗峰腳下。這支來自上游的「Blanc de Morgex et de La Salle」子產區：葡萄園海拔約 900–1,200 公尺（法規甚至允許到 1,300m），是歐洲最高的葡萄園之一。土壤是排水極佳的冰磧砂礫土，日夜溫差極大，賦予它鮮明的花香、礦石感與高酸度。',
    vinification_note: '葡萄藤採貼地的「低棚架」（pergola valdostana）整枝，棚面離地僅約 0.5–1.4 公尺，為的是吸收地面輻射熱、抵禦強風與大雪。這裡最珍貴的是葡萄藤為「未嫁接」的純血歐洲原生根——因為高海拔太冷，19 世紀末摧毀全歐葡萄園的根瘤蚜在此活不了，保留了罕見的「前根瘤蚜時代」老藤。\n\n釀法採與香檳同源的傳統瓶中二次發酵（Metodo Classico）：基酒先在不鏽鋼槽與大木桶完成第一次發酵，裝瓶後加糖加酵母在瓶中進行二次發酵，於酒渣（lees，發酵後沉澱的酵母）上陳年約 24 個月才除渣——這正是氣泡綿密、帶麵包皮香氣的來源。',
    classification_note: 'DOC（法定產區）是義大利的中階品質分級，代表產地、品種與釀法都受法規規範。「Valle d\'Aosta DOC」底下再細分出「Blanc de Morgex et de La Salle」這個高山子產區，等於替「白朗峰腳下、普里耶白釀的高山酒」做了產地背書。',
    producer_note: 'Cave Mont Blanc 是 1983 年成立的釀酒「合作社」，把約 70 戶高山葡農、合計約 18 公頃葡萄園集結起來，共同守護這片風土。氣泡酒 1986 年首釀只做了約 1,000 瓶，如今年產約 10 萬瓶。最傳奇的是它在海拔 2,173 公尺的纜車站（Pavillon du Mont Fréty）設了酒窖——號稱全歐洲最高的酒廠，2025 年 2 月才落成新廠，把瓶中二次發酵直接放在高山低溫、低氣壓的環境裡養氣泡。',
    why_beginner: '氣泡＋高酸＋低酒精（約 11.5%）讓它清爽好入口、幾乎沒有壓力，是最理想的開場餐前氣泡；又因為夠特別（歐洲最高葡萄園、稀有品種），喝起來既輕鬆又長知識，對新手非常友善。',
    drink_window: '現在 – 購入後約 1–3 年（趁新鮮喝最佳）',
    serve_temp: '6–8°C',
    decant: '不需要醒酒；冰鎮後直接享用即可。用鬱金香型氣泡杯（比細長笛型杯更能展開高山花香與礦物層次）。',
    background: 'Cave Mont Blanc 同廠還有更極致的版本：頂級的「Cuvée des Guides」二次發酵與約 30–36 個月酒渣陳年，都直接在海拔 2,173 公尺的高山酒窖完成，且為完全不加糖的 Brut Nature。本支 Blanc du Blanc Brut 是它最親民的「名片款」，用同一套高山風土與傳統工法，讓人用入門價格就喝到歐洲最高葡萄園的滋味。',
    tasting_focus: '品飲練習：先聞花香（紫藤、丁香）→ 再找礦石與柑橘 → 最後感受尾韻那股「濕岩石」般的清涼感。順便比較這股麵包／酵母香（傳統瓶中二次發酵的標記）和一般大槽法便宜氣泡酒的差別——走完這三段層次，你就掌握了高山氣泡酒的品飲框架。',
    notes_short: '歐洲最高葡萄園、未嫁接老藤釀的高山傳統法氣泡，清爽礦感、最理想的開場',
    notes_long: null,
    color_hex: '#E9E2B0',
    beginner_friendly: true,
    style_axis: 88,
    style_note: '原生稀有品種普里耶白、未嫁接老藤、歐洲最高葡萄園的極端風土，加上小農合作社的傳統工法，辨識度極高——幾乎是「風土個性」這一端的教科書。',
    image: null,
  },
  {
    id: 'grosjean-petite-arvine-rovettaz',
    region_key: 'valle-aosta',
    category: 'wine',
    type: 'white',
    type_zh: '白酒',
    name_en: 'Petite Arvine Vigne Rovettaz',
    name_zh: '葛羅讓 小奧文 羅維塔茲園',
    producer: 'Grosjean',
    varietal: 'Petite Arvine',
    varietal_zh: '小奧文',
    region: 'Valle d\'Aosta',
    region_zh: '奧斯塔谷',
    country: 'Italy',
    country_zh: '義大利',
    year: 2021,
    abv: 14,
    sweetness: '乾型',
    classification: 'Valle d\'Aosta DOC',
    price: null,
    bottles: null,
    price_tier: '$$',
    market_price_twd: '約 NT$1,200–1,600（國際零售推估）',
    rating: null,
    tasting_date: '2026-06-18',
    occasion: '越昇環義品飲課程 · 高海拔雙產區',
    highlights: [
      '源自瑞士瓦萊的「孤兒品種」，台灣極罕見',
      '招牌指紋：收尾那一抹「鹹味 salinity」',
      '奧斯塔谷第一家有機認證酒莊（2011 年）',
      '陡坡正南、薄石礫土的單一園 Vigne Rovettaz',
    ],
    appearance: '明亮稻草黃至淺金黃，清澈帶光澤。',
    aroma: ['葡萄柚', '檸檬', '白花', '青蘋果', '百香果', '茴香'],
    palate: ['中等偏飽滿', '檸檬酸度', '密實礦物與鹹感', '白桃', '微蜂蜜杏仁'],
    finish: '悠長而爽口，以鹹鮮礦物與柑橘餘韻收尾——這就是 Petite Arvine 最迷人的記憶點。',
    pairing: ['清蒸魚', '生魚片壽司', '白灼蝦', '鹽烤魚', '蛤蜊絲瓜', '海南雞飯'],
    pairing_note: '高酸＋鹹礦物的個性百搭海鮮河鮮：能借鹹感與酸度替清蒸魚、白灼蝦提鮮、解膩；避免重辣重醬，以免蓋過它細緻的礦物。',
    varietal_note: '小奧文（Petite Arvine）是個對台灣酒友很陌生、行家圈卻評價極高的稀有白葡萄。它原生於瑞士瓦萊州，1602 年即有文獻記載，DNA 至今找不到親本、是個「孤兒品種」，被譽為瓦萊白酒的「Diva（首席女伶）」，二十世紀中由 Joseph Vaudan 教士引進奧斯塔谷。名字裡的「Petite」指的是小果粒。它最招牌的，就是收尾那一抹像「鹽之花」的鹹鮮味——這是辨識 Petite Arvine 的指紋特徵。',
    region_note: '奧斯塔谷是義大利最小、最高、最靠阿爾卑斯的葡萄酒產區，高山大陸性氣候、日夜溫差大，有利保酸與累積香氣。羅維塔茲園（Vigne Rovettaz）是 Quart 鎮的單一園（cru），海拔約 550 公尺、陡坡、正南向以爭取最大日照；土層薄（不到 50 公分）、砂質夾大量石礫、排水極佳——逼根深扎，正是它鹹礦感的來源。',
    vinification_note: '手工採收後整串壓榨，果汁以浮選（flotation）澄清；以選育酵母在不鏽鋼槽發酵，帶酒渣（lees）長時間培養，第一個月持續攪桶（bâtonnage）增加質地與圓潤度。陳年採混合方式：約 70% 留在不鏽鋼、約 30% 移入法國橡木桶（barrique，約半數新桶），均帶細酒渣培養約 8 個月後再調配——目的是保留品種純淨的果香與鹹度，用少量橡木增添層次而不搶戲。酒精約 14%，屬有機認證酒。',
    classification_note: 'DOC（法定產區）是義大利的中階品質分級，規範產地、品種與釀法。看到「Valle d\'Aosta DOC（法文 Vallée d\'Aoste）」，代表這支是道地、受法規約束的奧斯塔谷高山酒；標單一品種者，該品種通常要占絕大多數。',
    producer_note: '葛羅讓兄弟酒莊（Maison Vigneronne Frères Grosjean）位在奧斯塔谷 Quart 鎮的 Ollignan 小村，是典型「英雄式高山葡萄種植」（陡坡、人工）。家族根源可溯至 18 世紀末，現代酒莊由祖父 Dauphin Grosjean 約 1968 年正式創立；常被提到的五兄弟（Vincent、Giorgio、Marco、Fernando、Eraldo）是第二代，2018 年起已交棒第三代經營。環保走得很早——1975 年起就不噴殺蟲劑，並於 2011 年成為奧斯塔谷第一家通過有機認證的酒莊。',
    why_beginner: '它酸度漂亮、香氣奔放（葡萄柚、白花、百香果），雖然酒精約 14%，但靠清爽酸度撐起來不顯重，整體清新好入口；最棒的是它帶來一個你味覺清單裡可能還沒出現過的新體驗——「鹹味白酒」，學起來很有成就感。',
    drink_window: '現在 – 2030',
    serve_temp: '10–12°C',
    decant: '不需要醒酒；別冰過頭（10–12°C 最佳），太冰會把香氣與鹹感都鎖住。開瓶後在杯中等 10–15 分鐘、或稍微回溫，鹹礦物與果香會更立體。',
    background: 'Petite Arvine 在瑞士瓦萊與義大利奧斯塔谷都被視為旗艦白葡萄，但全球種植極少、台灣相當罕見。這支來自 Grosjean 家族的旗艦單一園 Vigne Rovettaz，有機種植；酒莊更高階的 Petite Arvine「Les Frères」曾獲 Gambero Rosso 紅蝦評鑑最高的三隻酒杯肯定（那是另一款酒），可見其 Petite Arvine 的整體水準。',
    tasting_focus: '品飲練習：第一，刻意留意舌尖／喉頭收尾那股像鹽之花的鹹鮮感，把這個「鹹味白酒」的味覺記憶記起來。第二，體會「高海拔＝高酸＋礦物」的邏輯，和你喝過的平地白酒做對比。第三，拿它配一道清蒸魚或白灼蝦，感受酸與鹹如何把海鮮的鮮甜放大、把油膩沖淡——這是白酒佐餐最直觀的一課。',
    notes_short: '瓦萊「孤兒品種」的稀有高山白，招牌鹹礦感，認識「鹹味白酒」的教科書',
    notes_long: null,
    color_hex: '#E0D284',
    beginner_friendly: true,
    style_axis: 82,
    style_note: '稀有原生品種、有機單一園、薄石礫陡坡的鮮明鹹礦個性，明顯偏風土；唯約三成法國橡木桶培養帶來一點國際化的圓潤質地，因此沒有更極端。',
    image: null,
  },
  {
    id: 'elena-walch-lagrein',
    region_key: 'trentino-alto-adige',
    category: 'wine',
    type: 'red',
    type_zh: '紅酒',
    name_en: 'Lagrein Alto Adige',
    name_zh: '伊蓮娜·瓦爾希 拉格萊因',
    producer: 'Elena Walch',
    varietal: 'Lagrein',
    varietal_zh: '拉格萊因',
    region: 'Alto Adige',
    region_zh: '上阿迪杰',
    country: 'Italy',
    country_zh: '義大利',
    year: 2022,
    abv: 13.5,
    sweetness: '乾型',
    classification: 'Alto Adige DOC',
    price: null,
    bottles: null,
    price_tier: '$$',
    market_price_twd: '約 NT$1,000–1,400（國際零售推估）',
    rating: null,
    tasting_date: '2026-06-18',
    occasion: '越昇環義品飲課程 · 高海拔雙產區',
    highlights: [
      'Bolzano 原生紅葡萄，1970s 幾乎絕種後復興',
      'Teroldego 的後代、黑皮諾的「孫輩」',
      '招牌「苦杏仁」微苦尾韻 + 近墨深色',
      '與你的上阿迪杰黑皮諾同產區，最佳對照組',
    ],
    appearance: '濃郁石榴紅至近墨紫、邊緣帶紫，倒進杯中幾乎不透光。',
    aroma: ['黑櫻桃', '成熟黑莓', '藍莓', '李子', '紫羅蘭', '可可肉桂'],
    palate: ['中等酒體', '多汁深色果', '單寧明顯但相對柔順', '酸度爽脆', '鐵礦鹹鮮'],
    finish: '悠長多汁，收在 Lagrein 標誌性的微苦——苦杏仁／黑巧克力／咖啡感的清爽收口，讓濃郁果味不顯甜膩。',
    pairing: ['滷牛腱', '紅燒牛肉麵', '三杯雞', '黑胡椒牛排', '北京烤鴨', '廣式叉燒'],
    pairing_note: '紮實單寧＋鮮明酸度＋微苦尾韻使它非常百搭重口味：滷味、紅燒、燒臘、麻辣鍋都接得住，微苦尾韻還能呼應醬油與燒烤的焦香。',
    varietal_note: '拉格萊因（Lagrein）是發源於上阿迪杰首府 Bolzano（波札諾）周邊溫暖谷地的原生紅葡萄。身世精彩：DNA 確認它是 Teroldego（特洛迪歌）的後代、黑皮諾的「孫輩」、Marzemino 的姊妹。它 13 世紀就有記載，但 15 世紀後被高產的 Schiava 排擠，到 1970 年代幾乎絕種（僅剩約 50 公頃），靠在地人救回；至今仍稀有（全球約 537 公頃）。特徵是色深近墨紫、單寧紮實、酸度鮮明，最招牌的是尾韻那一抹「苦杏仁／黑巧克力」的微苦收口。',
    region_note: '上阿迪杰是義大利最北、阿爾卑斯山環抱的產區。Lagrein 是晚熟、需要熱量的品種，所以種在產區最溫暖的低海拔河谷（約 200–300 公尺、Bolzano 盆地周邊），排水好、白天蓄熱讓它熟透，夜間山區冷空氣保住酸度與香氣。有趣的對照是：同產區的黑皮諾嬌氣、種在涼爽的中高海拔坡地，Lagrein 則強壯、種在最熱的谷底——剛好是上阿迪杰紅酒的兩個極端。',
    vinification_note: '手工採收，於最佳成熟度進場；傳統控溫發酵約 10 天於不鏽鋼槽萃取色素與單寧，蘋果酸乳酸發酵（柔化酸度）在大型橡木桶中完成，桶型為 70hl 與 22hl 的法國與斯拉沃尼亞大桶，之後於大桶陳年數月。這是「以大桶輕修飾、柔化單寧並增添可可肉桂香」的風格，刻意不給明顯新桶味——與酒莊頂級的單一園 Castel Ringberg Lagrein Riserva（20 個月法國小新桶 barrique）明顯不同。殘糖極低（2022 年份約 3.4 g/L），是不甜紅酒，酒精約 13.5%。',
    classification_note: 'DOC（法定產區）是義大利的中階品質分級，規範產地、品種與釀法。「Alto Adige DOC」涵蓋這個阿爾卑斯產區的多種品種；標單一品種（如 Lagrein）者，代表它以該品種為主、產自法規劃定的上阿迪杰範圍。',
    producer_note: '伊蓮娜·瓦爾希（Elena Walch）是上阿迪杰公認的指標酒莊之一，位在 Tramin 小鎮，家族釀酒史溯至 1869 年，酒窖約 300 年。靈魂人物 Elena Walch 建築師出身，1985 年成為南提洛第一位女釀酒師，1988 年創立自有品牌，把「風土＋單一園」的現代觀念帶進產區；現由女兒 Julia 與 Karoline 接手（第五代）。旗下有兩座名園 Castel Ringberg 與 Kastelaz，酒莊近年轉型有機、2024 年取得 VIVA 永續認證。台灣由越昇國際代理進口。',
    why_beginner: '它單寧雖明顯，但在這個常規等級相對柔順，加上果味奔放、酸度爽脆，是很友善的紅酒入門款；配滷味、牛肉麵這類台味重口料理就很好喝，也不必久放——買來現在就能享用。',
    drink_window: '現在 – 2028',
    serve_temp: '15–18°C',
    decant: '年輕的 2022 可開瓶前醒酒約 30–60 分鐘，讓單寧鬆開、苦韻更圓潤；偏涼上桌（15–18°C）更能凸顯清爽。用波爾多型大肚杯聚攏深色果香。',
    background: 'Lagrein 是一段「差點消失、靠在地人救回」的復興故事：1970 年代幾乎絕種，80 年代品質革命後才重返舞台。Elena Walch 的這支屬入門到中階、走量的核心款（2022 年約 5,000 箱），用大桶輕修飾保留品種純淨的深色果味與微苦個性，供應與價格都相對親民，是認識 Lagrein 很理想的起點。',
    tasting_focus: '品飲練習：(1) 記兩個招牌記號——眼睛看「色深近墨」、尾韻嚐「苦杏仁／黑巧克力的微苦收口」，以後盲飲就抓得到 Lagrein。(2) 務必和你的「聖米歇爾-艾本 黑皮諾」並排喝（先黑皮諾、後 Lagrein）：同樣來自上阿迪杰，黑皮諾輕巧紅果、種在涼爽高坡，Lagrein 深色厚實、種在最熱谷底——一次就懂「同產區、不同品種與海拔」風格差多少。',
    notes_short: '差點絕種、被救回的上阿迪杰原生紅，色深、微苦尾韻，與黑皮諾的最佳同產區對照',
    notes_long: null,
    color_hex: '#3A0E1C',
    beginner_friendly: true,
    style_axis: 66,
    style_note: '稀有原生品種 Lagrein、上阿迪杰特定風土，本就偏風土；但 Elena Walch 是現代化名莊、此款走大桶輕修飾的核心量產路線，風格乾淨易親近，因此落在偏風土但不極端。',
    image: null,
  },
  {
    id: 'floramundi-cerasuolo-vittoria',
    region_key: 'sicilia',
    category: 'wine',
    type: 'red',
    type_zh: '紅酒',
    name_en: 'Floramundi Cerasuolo di Vittoria',
    name_zh: '多娜佳塔 弗洛拉蒙地',
    producer: 'Donnafugata',
    varietal: 'Nero d\'Avola · Frappato',
    varietal_zh: '黑達沃拉 · 弗萊帕托',
    region: 'Vittoria, Sicily',
    region_zh: '西西里',
    country: 'Italy',
    country_zh: '義大利',
    year: 2023,
    abv: 13.5,
    sweetness: '乾型',
    classification: 'Cerasuolo di Vittoria DOCG',
    price: null,
    bottles: null,
    price_tier: '$$',
    market_price_twd: '約 NT$1,260–1,400',
    rating: null,
    tasting_date: '2026-06-08',
    occasion: '想喝清單 · 西西里',
    highlights: [
      '西西里「唯一」DOCG：Cerasuolo di Vittoria（2005 升格，島上第一也是唯一）',
      '西西里名莊多娜佳塔（Donnafugata）的代表作',
      '兩大原生品種：Nero d\'Avola（王者結構）＋ Frappato（鮮果花香）',
      '明亮櫻桃紅、單寧細、酸度爽——可微冰、超順口的餐桌紅',
      '著名藝術酒標：花卉新藝術 × 西西里傳統木偶意象',
    ],
    appearance: '明亮的櫻桃紅至寶石紅、帶紫色光澤，色澤清透鮮活——正是「Cerasuolo（櫻桃紅）」之名的由來。',
    aroma: ['紅櫻桃', '草莓', '覆盆子', '紫羅蘭花香', '地中海香草', '黑胡椒'],
    palate: ['輕至中等酒體', '單寧細柔滑順', '酸度清爽活潑', '多汁鮮果主導', '一絲血橙與香料'],
    finish: '清新多汁的收尾，紅櫻桃與淡淡花香、香料尾韻，順口好喝、不澀不重。',
    pairing: ['番茄紅醬義大利麵', '烤雞', '披薩', '滷肉飯', '三杯雞', '紅燒家常菜', '微辣川菜／泰式'],
    pairing_note: '果味奔放、單寧細、酸度爽，是非常百搭的「餐桌酒」。稍微冰一下喝，酸度能解油膩、襯托番茄與醬汁的鮮甜；台菜的滷肉飯、三杯雞、紅燒類醬香與油脂它都接得住，面對微辣（川菜、泰式）也比厚重高單寧紅酒更不易「打架」。',
    varietal_note: '這是西西里兩個原生紅葡萄的經典組合。Nero d\'Avola（黑達沃拉，當地別名 Calabrese）被稱為「西西里紅葡萄之王」，提供酒體、結構與成熟黑／紅果的厚度；Frappato（弗萊帕托）是島上最古老品種之一，色淺、單寧細、酸度活潑，帶來鮮明的紅櫻桃、草莓果香與花香。兩者一搭，剛好是「有骨架但不厚重、果味奔放又好喝」，對新手非常友善。',
    region_note: '產區位於西西里島東南角、拉古薩（Ragusa）省的維多利亞（Vittoria）一帶，鄰近 Acate、Comiso 等鄉鎮。這裡日照充足、地中海氣候溫暖乾燥，多為砂質與紅土土壤，海風調節溫度，賦予葡萄成熟果味又保有清爽酸度，正是釀出明亮「櫻桃紅」風格的關鍵。',
    vinification_note: '兩個品種分開於不鏽鋼槽發酵，帶皮浸泡（macération）約 10 天、控溫 25–28°C 萃取色澤與果味；完成乳酸發酵後，於不鏽鋼槽熟成約 8–9 個月（保留鮮明果香、不過木桶），再瓶中靜置至少 3 個月後上市。整體走「鮮果與純淨度」路線，不刻意用新橡木桶壓味。',
    classification_note: 'Cerasuolo di Vittoria 是整個西西里島「唯一」的 DOCG（保證法定產區，義大利最高分級）。它 1973 年先取得 DOC、2005 年升格 DOCG，是西西里第一個、也是至今唯一一個。法規限定只能用 Nero d\'Avola（50–70%）與 Frappato（30–50%）兩個品種、最低酒精度 13%，另有更嚴格的 Classico 子產區。「Cerasuolo」意為「櫻桃紅」，直接點出這款酒明亮的酒色。',
    producer_note: '多娜佳塔（Donnafugata）由 Giacomo Rallo 與妻子 Gabriella 於 1983 年創立，背後是經營馬沙拉（Marsala）加烈酒已逾 150 年的拉羅（Rallo）家族。酒莊名「Donnafugata（逃亡的女人）」典出蘭佩杜薩的小說《豹》（Il Gattopardo）。如今由第二代姊弟 José 與 Antonio Rallo 共同經營，葡萄園遍及西西里多個產區（Contessa Entellina、馬沙拉、埃特納火山、維多利亞）與離島潘泰萊里亞，總面積逾 400 公頃，是西西里最具代表性、最受國際推崇的名莊之一。',
    why_beginner: '單寧細柔、酸度清爽、果味直接奔放，喝起來輕盈順口、完全沒有粗澀厚重感，還能稍微冰一下喝，很適合台灣天氣。又出自名莊、品質穩定，還是西西里唯一 DOCG，是踏入義大利紅酒、認識原生品種很友善的一支。',
    drink_window: '現在 – 2029（鮮果風格，趁年輕喝最能享受奔放果香）',
    serve_temp: '15–16°C',
    decant: '不需要長時間醒酒；開瓶後靜置或醒 15–20 分鐘即可。建議稍微冰鎮到 15–16°C 再喝，果香與清爽感最迷人。',
    background: 'Floramundi 是多娜佳塔在西西里唯一 DOCG——Cerasuolo di Vittoria——的代表作，由「西西里紅葡萄之王」Nero d\'Avola 約 70% 搭配古老品種 Frappato 約 30% 釀成。產區在西西里東南角維多利亞一帶，溫暖地中海氣候加海風，造就明亮櫻桃紅、果味奔放又清爽的風格；採不鏽鋼發酵、約 10 天浸皮、鋼槽熟成再瓶陳，刻意保留純淨鮮果味。酒名「Floramundi」意指「世界之花」，酒標由 Stefano Vitale 繪製，融合維多利亞當地的花卉新藝術（Liberty）風格與西西里傳統木偶（Pupi Siciliani）意象，是酒莊著名的藝術酒標之一。',
    tasting_focus: '品飲練習：先看酒色——它的「櫻桃紅、帶紫光澤、清透」正是 Cerasuolo 名字的由來，可和深濃厚重的紅酒對照。聞香找紅櫻桃、草莓、紫羅蘭（多半來自 Frappato）。入口練習感受三件事：單寧很細（不咬口）、酸度清爽（口水會分泌）、果味多汁；最後留意收尾的清新與一絲香料。可試著稍微冰鎮（15–16°C）前後各喝一口，體會溫度如何放大果香與爽口度。',
    notes_short: '西西里唯一 DOCG，黑達沃拉＋弗萊帕托的明亮櫻桃紅，單寧細、酸度爽、超順口的餐桌紅',
    notes_long: null,
    color_hex: '#B0263C',
    beginner_friendly: true,
    style_axis: 70,
    style_note: '西西里唯一 DOCG、兩個原生品種（Nero d\'Avola＋Frappato）的經典組合，風土辨識度高；但出自現代化名莊多娜佳塔、走不鏽鋼槽保留純淨鮮果的乾淨路線，因此偏風土但不極端。',
    image: null,
  },
];

// 類型 → 中文 + 顏色（給篩選器跟圖表用）
export const typeMeta = {
  'sparkling-red':   { zh: '氣泡紅', accent: '#7A2024', group: 'sparkling' },
  'sparkling-white': { zh: '氣泡白', accent: '#B89A5E', group: 'sparkling' },
  'red':             { zh: '紅酒',   accent: '#5C1A1B', group: 'red' },
  'white':           { zh: '白酒',   accent: '#A8924E', group: 'white' },
  'rose':            { zh: '粉紅酒', accent: '#93515C', group: 'rose' },
};

// 風格光譜的兩端標籤（給 modal 與圖表共用）
export const STYLE_AXIS_ENDS = {
  left:  { zh: '國際風格', en: 'International' },
  right: { zh: '風土個性', en: 'Terroir' },
};

// 把 0–100 的 style_axis 轉成一個分級標籤
export function styleAxisTier(v) {
  if (v == null) return null;
  if (v <= 22) return { zh: '國際風格', en: 'International' };
  if (v <= 42) return { zh: '偏國際',   en: 'Leans Intl' };
  if (v <= 58) return { zh: '兼具',     en: 'Balanced' };
  if (v <= 78) return { zh: '偏風土',   en: 'Leans Terroir' };
  return { zh: '風土個性', en: 'Terroir' };
}

// ============================================================
// 義大利 20 個葡萄酒產區（事實/參考資料，已查證）
// 「產區地圖」用：每支酒的 region_key 連到這張表；未收藏的產區也能顯示代表酒。
// zone：North / Central / South / Islands（標準酒業 4 區慣例；顯示時南部與離島併為一組）。
// grapes 代表品種、wines 代表酒/法定產區、note 一句話新手導覽。
// 新增義大利酒時：給酒一個 region_key 對應這裡的 key 即可自動上表。
// ============================================================
export const ITALY_REGIONS = [
  // —— 北部 North（8）——
  { key: 'piemonte', name_en: 'Piedmont', name_it: 'Piemonte', name_zh: '皮埃蒙特', zone: 'North',
    grapes: ['Nebbiolo', 'Barbera', 'Moscato'], wines: ['Barolo', 'Barbaresco', 'Barbera d\'Alba'],
    note: '義大利紅酒王國，Barolo 被稱「酒中之王」；新手可先試單寧較柔、果香飽滿的 Barbera。' },
  { key: 'valle-aosta', name_en: 'Valle d\'Aosta', name_it: 'Valle d\'Aosta', name_zh: '瓦萊達奧斯塔', zone: 'North',
    grapes: ['Prié Blanc', 'Petit Rouge', 'Fumin'], wines: ['Blanc de Morgex', 'Torrette'],
    note: '義大利最小、最高海拔的阿爾卑斯山產區；高山清爽白酒與柔順紅酒為主。' },
  { key: 'trentino-alto-adige', name_en: 'Trentino-Alto Adige', name_it: 'Trentino-Alto Adige', name_zh: '上阿迪杰', zone: 'North',
    grapes: ['Pinot Grigio', 'Gewürztraminer', 'Lagrein'], wines: ['Alto Adige DOC', 'Trentodoc', 'Teroldego'],
    note: '阿爾卑斯高山白酒天堂，乾淨純淨；清爽 Pinot Grigio 或花香 Gewürztraminer 入門。' },
  { key: 'emilia-romagna', name_en: 'Emilia-Romagna', name_it: 'Emilia-Romagna', name_zh: '艾米利亞-羅馬涅', zone: 'North',
    grapes: ['Lambrusco', 'Sangiovese', 'Albana'], wines: ['Lambrusco di Sorbara', 'Romagna Sangiovese'],
    note: '美食之鄉，微甜微氣泡紅酒 Lambrusco 最親民，配義式火腿起司一流。' },
  { key: 'veneto', name_en: 'Veneto', name_it: 'Veneto', name_zh: '威尼托', zone: 'North',
    grapes: ['Glera', 'Corvina', 'Garganega'], wines: ['Prosecco', 'Amarone', 'Soave'],
    note: '出口量最大的產區，從氣泡到濃郁紅酒全包；入門首選人人愛的 Prosecco。' },
  { key: 'friuli', name_en: 'Friuli-Venezia Giulia', name_it: 'Friuli-Venezia Giulia', name_zh: '弗留利', zone: 'North',
    grapes: ['Friulano', 'Ribolla Gialla', 'Pinot Grigio'], wines: ['Collio', 'Friuli DOC'],
    note: '義大利頂級白酒產地（八成以上是白酒）；想喝乾淨花香白酒可從 Friulano 入門。' },
  { key: 'lombardia', name_en: 'Lombardy', name_it: 'Lombardia', name_zh: '倫巴第', zone: 'North',
    grapes: ['Chardonnay', 'Pinot Nero', 'Nebbiolo'], wines: ['Franciacorta', 'Valtellina', 'Oltrepò Pavese'],
    note: '傳統法氣泡酒重鎮；想喝氣泡選香檳工法的 Franciacorta，紅酒試山區的 Valtellina。' },
  { key: 'liguria', name_en: 'Liguria', name_it: 'Liguria', name_zh: '利古里亞', zone: 'North',
    grapes: ['Vermentino', 'Pigato', 'Rossese'], wines: ['Cinque Terre', 'Rossese di Dolceacqua'],
    note: '地中海沿岸小產區，清爽帶鹹礦感的白酒聞名；配海鮮首選 Vermentino。' },
  // —— 中部 Central（5）——
  { key: 'toscana', name_en: 'Tuscany', name_it: 'Toscana', name_zh: '托斯卡尼', zone: 'Central',
    grapes: ['Sangiovese', 'Vernaccia', 'Cabernet'], wines: ['Chianti Classico', 'Brunello di Montalcino', 'Vino Nobile'],
    note: '最知名紅酒產區，山吉歐維榭釀的 Chianti 酸櫻桃清爽好搭餐，是入門首選。' },
  { key: 'abruzzo', name_en: 'Abruzzo', name_it: 'Abruzzo', name_zh: '阿布魯佐', zone: 'Central',
    grapes: ['Montepulciano', 'Trebbiano', 'Pecorino'], wines: ['Montepulciano d\'Abruzzo', 'Cerasuolo d\'Abruzzo'],
    note: 'Montepulciano d\'Abruzzo 果香飽滿、單寧柔、價格實惠，新手最易上手的義大利紅酒。' },
  { key: 'marche', name_en: 'Marche', name_it: 'Marche', name_zh: '馬爾凱', zone: 'Central',
    grapes: ['Verdicchio', 'Montepulciano', 'Sangiovese'], wines: ['Verdicchio dei Castelli di Jesi', 'Rosso Conero'],
    note: '白葡萄 Verdicchio 聞名，酸度清爽帶礦石與杏仁尾韻，CP 值高、好配海鮮。' },
  { key: 'umbria', name_en: 'Umbria', name_it: 'Umbria', name_zh: '翁布里亞', zone: 'Central',
    grapes: ['Sagrantino', 'Grechetto', 'Sangiovese'], wines: ['Montefalco Sagrantino', 'Orvieto'],
    note: '唯一不靠海的中部產區；清爽白酒試 Orvieto，重口味單寧挑戰超濃的 Sagrantino。' },
  { key: 'lazio', name_en: 'Lazio', name_it: 'Lazio', name_zh: '拉吉歐', zone: 'Central',
    grapes: ['Malvasia', 'Trebbiano', 'Cesanese'], wines: ['Frascati', 'Cesanese del Piglio'],
    note: '羅馬所在地，好入口的 Frascati 白酒清爽日常、價格親民；紅酒找本地的 Cesanese。' },
  // —— 南部 South（5）——
  { key: 'campania', name_en: 'Campania', name_it: 'Campania', name_zh: '坎帕尼亞', zone: 'South',
    grapes: ['Aglianico', 'Fiano', 'Greco'], wines: ['Taurasi', 'Fiano di Avellino', 'Greco di Tufo'],
    note: '南義最有深度的產區，紅酒看「南部的 Barolo」Taurasi，白酒試清爽的 Greco di Tufo。' },
  { key: 'puglia', name_en: 'Puglia', name_it: 'Puglia', name_zh: '普利亞', zone: 'South',
    grapes: ['Primitivo', 'Negroamaro'], wines: ['Primitivo di Manduria', 'Salice Salentino'],
    note: '「鞋跟」陽光產區、CP 值極高；Primitivo（即加州 Zinfandel）果醬甜潤，新手最好上手。' },
  { key: 'basilicata', name_en: 'Basilicata', name_it: 'Basilicata', name_zh: '巴西利卡塔', zone: 'South',
    grapes: ['Aglianico'], wines: ['Aglianico del Vulture'],
    note: '幾乎只有一張王牌：火山土上的 Aglianico，結構厚實耐陳，南義硬派紅酒代表。' },
  { key: 'calabria', name_en: 'Calabria', name_it: 'Calabria', name_zh: '卡拉布里亞', zone: 'South',
    grapes: ['Gaglioppo'], wines: ['Cirò'],
    note: '「鞋尖」較冷門產區，古老紅葡萄 Gaglioppo 釀的 Cirò 酸度高、帶玫瑰菸草香。' },
  { key: 'molise', name_en: 'Molise', name_it: 'Molise', name_zh: '莫利塞', zone: 'South',
    grapes: ['Tintilia', 'Montepulciano', 'Aglianico'], wines: ['Tintilia del Molise', 'Biferno'],
    note: '義大利第二小、低調的產區，招牌是本地獨有品種 Tintilia，辛香紮實的紅酒。' },
  // —— 離島 Islands（2）——
  { key: 'sicilia', name_en: 'Sicily', name_it: 'Sicilia', name_zh: '西西里', zone: 'Islands',
    grapes: ['Nero d\'Avola', 'Nerello Mascalese', 'Grillo'], wines: ['Etna Rosso', 'Cerasuolo di Vittoria', 'Marsala'],
    note: '近年最熱門的島嶼產區；紅酒從飽滿 Nero d\'Avola 入門，進階試 Etna 火山的礦感紅酒。' },
  { key: 'sardegna', name_en: 'Sardinia', name_it: 'Sardegna', name_zh: '薩丁尼亞', zone: 'Islands',
    grapes: ['Cannonau', 'Vermentino', 'Carignano'], wines: ['Vermentino di Gallura', 'Cannonau di Sardegna'],
    note: '地中海大島，白酒首選 Vermentino 清爽帶柑橘鹹味；紅酒 Cannonau（即格那希）溫暖好入口。' },
];

// 顯示分組：北 / 中 / 南＋離島（尊重「北中南」，離島併入南部一組但仍各自列出）
export const ITALY_ZONE_GROUPS = [
  { key: 'north',   it: 'Nord',        zh: '北部',      en: 'North',            zones: ['North'] },
  { key: 'central', it: 'Centro',      zh: '中部',      en: 'Central',          zones: ['Central'] },
  { key: 'south',   it: 'Sud · Isole', zh: '南部 · 離島', en: 'South & Islands', zones: ['South', 'Islands'] },
];
