// 我的品飲清單
// 新增酒款只要往陣列裡塞一筆。所有欄位都會自動帶到 UI。
// id 必填且唯一；image 留 null 會用 SVG 酒瓶插畫，填 URL 會用照片。
//
// style_axis：風格光譜（主觀定位）。0 = 國際風格 / 高度標準化，
//   100 = 風土個性 / 反標準化。新增酒款時憑感覺給個 0–100 就好。
// style_note：一句話說明為什麼放在這個位置（modal 詳情頁會顯示）。
//
// rating 一律由站主本人親口給；沒喝過 / 還沒打分 = null（顯示「待品飲」）。
//   絕不代填、不引用酒評家分數。notes_long 是站主自己的筆記（個人感受）。
//
// 購入資訊：price = 購入單價（新台幣，數字）；bottles = 購入瓶數；
//   price_estimated = true 代表單價是推估（收據未列）；
//   market_price_twd = 市場行情參考價帶（字串，純參考、非評分）。
// 知識欄位（modal 詳情頁會分區顯示，皆為事實／教育性內容，不含個人評價）：
//   producer_note 酒莊、varietal_note 品種小知識、region_note 產區風土、
//   vinification_note 釀法、classification / classification_note 產區分級、
//   why_beginner 為什麼適合新手、background 深入認識、tasting_focus 品飲練習重點、
//   sweetness 甜度、drink_window 適飲期、serve_temp 飲用溫度、decant 醒酒建議、pairing_note 配餐邏輯。
//   長欄位（vinification_note / background / tasting_focus 等）可用空行（\n\n）分段，modal 會自動拆成多段。
// highlights：看點陣列（3–5 條短句），會顯示在 modal 上方做亮點導讀。
// appearance：外觀描述（一句話），與 aroma／palate／finish 同屬品飲區。
//
// 譯名統一：Tenuta Carretta=卡蕾塔、Tenuta Pederzana=佩德札納、
//   Lambrusco=蘭布魯斯科、Grasparossa=葛拉斯帕羅薩、Castelvetro=卡斯特爾韋特羅、
//   Nizza=尼薩、Roero=羅埃羅、Alto Adige=上阿迪杰。

export const drinks = [
  {
    id: 'pinot-nero-eppan',
    region_key: 'trentino-alto-adige',
    category: 'wine',
    type: 'red',
    type_zh: '紅酒',
    name_en: 'St. Michael-Eppan Pinot Nero',
    name_zh: '聖米歇爾-艾本 黑皮諾',
    producer: 'St. Michael-Eppan',
    varietal: 'Pinot Nero',
    varietal_zh: '黑皮諾',
    region: 'Alto Adige',
    region_zh: '上阿迪杰',
    country: 'Italy',
    country_zh: '義大利',
    year: 2023,
    abv: 13.5,
    sweetness: '乾型',
    classification: 'Alto Adige DOC',
    price: 1200,
    bottles: 1,
    price_tier: '$$',
    market_price_twd: '約 NT$900–1,400',
    rating: 5,
    tasting_date: '2026-06-03',
    occasion: '人生第一支紅酒',
    aroma: ['紅櫻桃', '覆盆子', '黑莓', '紫羅蘭', '些許香料'],
    palate: ['中等酒體', '單寧細柔', '酸度清爽'],
    finish: '柔順收尾，紅果與淡淡香料尾韻',
    pairing: ['烤雞', '滷肉', '菇類料理', '鮭魚生魚片'],
    pairing_note: '黑皮諾單寧細、酸度清爽，能襯托白肉與菇類的鮮味又不搶味，連油脂豐厚的鮭魚生魚片或台式滷肉都接得住。',
    varietal_note: '黑皮諾（義大利文 Pinot Nero、法文 Pinot Noir）是出了名嬌貴難種的紅葡萄，但釀出的酒單寧細柔、酸度清爽、果香鮮明，是公認最好入口的紅酒之一。它怕熱、偏好冷涼氣候，因此上阿迪杰這種高海拔山區特別適合，能保留紅櫻桃、覆盆子般的清新果味。對新手來說，它沒有粗澀厚重的單寧，是從白酒跨進紅酒世界很友善的橋樑。',
    region_note: '上阿迪杰位於義大利最北端、靠近奧地利的阿爾卑斯山區，是公認義大利最會做黑皮諾的產區；高海拔（葡萄園約 400–550 公尺）日夜溫差大，賦予紅酒清爽酸度與優雅果香。',
    classification_note: 'DOC（法定產區）是義大利的中階品質分級，代表產地、品種與釀法都受法規規範；標單一品種的酒，該品種要占至少 85%。這支屬酒莊入門的「Classic」系列，不是頂級的 Sanct Valentin 珍藏版，但已能展現產區水準。',
    producer_note: '聖米歇爾-艾本是上阿迪杰最受敬重的合作社酒莊之一，1907 年創立，由三百多位酒農、近 385 公頃葡萄園組成；曾被 Gambero Rosso／Slow Food《義大利葡萄酒指南》選為「2000 年度最佳義大利酒莊」，以細膩優雅著稱。',
    why_beginner: '單寧細柔、酸度清爽、沒有粗澀厚重感，是最好入口的紅酒之一，還能稍微冰一下喝，很適合台灣天氣，對紅酒新手非常友善。',
    drink_window: '現在 – 2028',
    serve_temp: '14–16°C',
    decant: '不一定要醒酒；想讓香氣更開展，可開瓶後靜置或醒 15–20 分鐘，並稍微冰鎮（約 14–16°C）後享用。',
    background: '上阿迪杰是公認義大利最會做黑皮諾的產區，位在義大利最北端的阿爾卑斯山區，高海拔與大日夜溫差賦予紅酒清爽酸度與優雅果香。St. Michael-Eppan 是 1907 年創立、由三百多位酒農組成的頂級合作社，曾被 Gambero Rosso／Slow Food 選為 2000 年度最佳義大利酒莊。這支是入門的「Classic」系列（不是頂級的 Sanct Valentin 珍藏版）：於不鏽鋼槽發酵，再有一部分放進大木桶（grandi botti）陳年，增添柔順度。酒色石榴紅，乾型、酒精約 13.5%。',
    notes_short: '義大利最強黑皮諾產區的可靠大牌，入門紅酒天花板',
    notes_long: '我的第一支紅酒，超好喝！整體很順口、輕盈好入口。',
    color_hex: '#9E2B3C',
    beginner_friendly: true,
    style_axis: 60,
    style_note: '黑皮諾是最國際化的紅葡萄，但上阿迪杰的高山冷涼風土辨識度高，加上頂級合作社的不鏽鋼＋大木桶（grandi botti）傳統釀法——兩股力量拉鋸，落在中間略偏風土。',
    image: null,
  },
  {
    id: 'barbera-nizza-carretta',
    region_key: 'piemonte',
    category: 'wine',
    type: 'red',
    type_zh: '紅酒',
    name_en: 'Bricco Manera Nizza DOCG',
    name_zh: '卡蕾塔 巴貝拉 馬內拉園',
    producer: 'Tenuta Carretta',
    varietal: 'Barbera',
    varietal_zh: '巴貝拉',
    region: 'Nizza, Piedmont',
    region_zh: '尼薩',
    country: 'Italy',
    country_zh: '義大利',
    year: 2020,
    abv: 14.5,
    sweetness: '乾型',
    classification: 'Nizza DOCG',
    price: 1300,
    bottles: 1,
    price_tier: '$$',
    market_price_twd: '約 NT$1,000–1,500',
    rating: 4.3,
    tasting_date: '2026-06-08',
    occasion: '在家品飲',
    aroma: ['黑櫻桃', '成熟李子', '紫羅蘭', '香料', '香草橡木'],
    palate: ['多汁', '酸度爽朗', '中等至飽滿酒體'],
    finish: '尾韻悠長帶香料感，整體柔順和諧、不咬口',
    pairing: ['紅燒牛肉麵', '滷味', '三杯雞', '番茄肉醬麵', '煎烤豬排'],
    pairing_note: '巴貝拉爽朗的酸度能切開油脂、提亮醬汁鹹香，所以特別搭得起台灣常見的紅燒、滷味與帶醬汁的料理。',
    varietal_note: '巴貝拉是皮埃蒙特最親民的紅葡萄品種：天生酸度爽朗、單寧不重，所以喝起來多汁順口、不咬口。它的果味直接（黑櫻桃、李子），對新手非常友善，常被當作認識義大利紅酒的入門品種。',
    region_note: '尼薩位於皮埃蒙特的蒙費拉托丘陵，是巴貝拉的核心精華區。這款酒的果實來自蒙巴魯佐（Mombaruzzo）一帶的向陽坡地，被視為展現巴貝拉最佳風味的搖籃。',
    classification_note: 'Nizza DOCG 是巴貝拉的最高等級分級：必須 100% 用巴貝拉，只能來自尼薩一帶精選坡地，並要求最低 18 個月陳年（含至少 6 個月木桶），是義大利最嚴格的法定產區之一。簡單說，看到「Nizza DOCG」就代表這是巴貝拉裡最講究的一群。',
    producer_note: '卡蕾塔酒莊的歷史可追溯到 1467 年一份提及「cassina Careta」的契約，是皮埃蒙特最古老的酒莊之一，莊園位於阿爾巴近郊的 Piobesi d’Alba，1985 年起由阿爾巴的 Miroglio 家族接手經營，強調風土表現。',
    why_beginner: '巴貝拉酸度活潑、單寧柔和，喝起來多汁順口不咬口，是認識義大利紅酒非常友善的入門選擇；唯一要留意的是這款酒精偏高（約 14.5%），建議搭餐慢慢喝。',
    drink_window: '現在 – 2028',
    serve_temp: '16–18°C',
    decant: '建議開瓶前先醒酒約 30–60 分鐘，能讓果香與香料氣息更開展；不醒也可直接喝。',
    background: '這支由皮埃蒙特歷史可追溯到 1467 年的卡蕾塔酒莊釀造，100% 巴貝拉，果實來自尼薩產區東南向、深厚凝灰岩（tufo）土壤的坡地。Nizza 自 2014 年起獨立成為法定產區，是義大利第一個專屬巴貝拉的最高等級分級。這款 Bricco Manera 是酒莊較清新易飲的標準款（非珍藏級 Riserva「Mora di Sassi」）：經約兩週控溫浸皮，於法國橡木中桶（tonneau）陳年至少 6 個月，上市前合計熟成約 18 個月，正符合 Nizza DOCG 的最低陳年規範。酒色濃郁寶石紅，帶巴貝拉典型的紫羅蘭光澤。',
    notes_short: '皮埃蒙特逾五百年老莊釀的最高等級巴貝拉，多汁柔順、酸度討喜的入門紅酒',
    notes_long: '我的第二支靜態紅酒，昨天在家開的。忍不住直接拿來跟人生第一支、那支 5★ 黑皮諾比——一比就有感：黑皮諾是輕盈、優雅、好入口的那種好喝；這支 Barbera 明顯複雜、厚重了一階，份量和結構都更足。有意思的是，這個「厚」是酒體的重量感、不是單寧的澀（Barbera 本來就酸度高、單寧低，喝起來其實很順）。對我來說它剛好卡在「入門好喝」和「需要細品的複雜紅酒」中間：不會難懂到要正襟危坐，但也不只是隨手解渴，開始有層次可以慢慢追。算是我從黑皮諾往上探、滿有成就感的一步。',
    color_hex: '#6E1530',
    beginner_friendly: true,
    style_axis: 72,
    style_note: '100% 巴貝拉、Nizza DOCG 的嚴格產區規範與蒙巴魯佐向陽坡風土，讓它偏向「風土個性」一端；橡木桶陳年帶來一些國際化的圓潤香草感，因此沒有更極端。',
    image: null,
  },
  {
    id: 'arneis-cayega-carretta',
    region_key: 'piemonte',
    category: 'wine',
    type: 'white',
    type_zh: '白酒',
    name_en: 'Cayega Roero Arneis',
    name_zh: '卡蕾塔 卡耶加 阿內斯',
    producer: 'Tenuta Carretta',
    varietal: 'Arneis',
    varietal_zh: '阿內斯',
    region: 'Roero, Piedmont',
    region_zh: '羅埃羅',
    country: 'Italy',
    country_zh: '義大利',
    year: 2023,
    abv: 13.5,
    sweetness: '乾型',
    classification: 'Roero Arneis DOCG',
    price: 1100,
    bottles: 1,
    price_tier: '$$',
    market_price_twd: '約 NT$900–1,200',
    rating: null,
    tasting_date: '2026-06-03',
    occasion: '在家品飲',
    aroma: ['西洋梨', '白桃', '柑橘', '白花', '燧石礦物'],
    palate: ['乾型圓潤', '酸度清爽', '礦物尾韻'],
    finish: '乾淨清爽，礦物與柑橘回韻悠長',
    pairing: ['清蒸魚', '生魚片', '鹽水蝦', '白灼海鮮', '涼拌菜'],
    pairing_note: '清爽的酸度與礦物感能解海鮮的鮮甜、壓住腥味，又因為不過桶、沒有橡木味，不會蓋過清淡料理的本味。',
    varietal_note: '阿內斯（Arneis）是皮埃蒙特的原生白葡萄。坊間常說它的名字在當地方言意思接近「小淘氣」，用來形容它難種、不好照顧（這說法很流行，但語源其實有爭議）。它二十世紀中葉曾一度近乎絕種，後來才被救回。釀出的白酒屬乾型但口感柔順圓潤，帶西洋梨、白桃與白花香，酸度溫和不尖銳，是很好入口的入門白酒。',
    region_note: '羅埃羅在皮埃蒙特、塔納羅河左岸，與對岸名滿天下的 Barolo、Barbaresco 隔河相望，是個低調的小產區，以清新的阿內斯白酒和優雅的內比歐露紅酒聞名。',
    classification_note: 'DOCG 是義大利葡萄酒分級的最高一級，規範比 DOC 更嚴格。Roero Arneis DOCG 規定至少要用 95% 的阿內斯葡萄，等於替「這是道地皮埃蒙特阿內斯白酒」做了官方背書。',
    producer_note: '卡蕾塔莊園位於皮埃蒙特羅埃羅產區的 Piobesi d’Alba，源頭可追溯到 1467 年的一份土地契約，是義大利歷史最悠久的酒莊之一；1985 年起由 Miroglio 家族接手經營至今。',
    why_beginner: '乾型但口感柔順圓潤、酸度溫和不刺激，又沒有橡木桶的味道，果香花香清楚易懂，是最容易上手、配台式海鮮也不會出錯的入門白酒。',
    drink_window: '現在 – 2027',
    serve_temp: '8–10°C',
    decant: '不需要醒酒，直接冰透開瓶即可；阿內斯白酒講究新鮮，現開現喝最能表現果香與酸度。',
    background: '阿內斯是皮埃蒙特的原生白葡萄，因為難種，二十世紀中葉曾一度近乎絕種，靠卡蕾塔等在地酒莊保留老藤、加上 1970 年代的復興才被救回。Cayega 採 100% 阿內斯，在不鏽鋼槽中陳化約半年、帶細緻酒渣（lees，即發酵後沉澱的酵母，能增添口感厚度），全程不過橡木桶，主打清新風格（酒莊另有過桶的頂級版 Canorei）。Roero Arneis 是 DOCG 最高分級，規定至少 95% 阿內斯。酒色金黃帶綠光，建議冰到 8–10°C、趁年輕喝。',
    notes_short: '皮埃蒙特軟順白酒，海鮮絕配、超好入口',
    notes_long: null,
    color_hex: '#E6DCA2',
    beginner_friendly: true,
    style_axis: 73,
    style_note: '阿內斯是皮埃蒙特近乎絕種、被在地酒莊救回的原生白葡萄，產區極小、不鏽鋼槽不過桶保留品種與風土本味——非常風土那一端；清爽討喜的風格讓它依然好親近。',
    image: null,
  },
  {
    id: 'lambrusco-grasparossa-tradizione',
    region_key: 'emilia-romagna',
    category: 'wine',
    type: 'sparkling-red',
    type_zh: '氣泡紅酒',
    name_en: 'Grasparossa della Tradizione',
    name_zh: '傳統葛拉斯帕羅薩',
    producer: 'Tenuta Pederzana',
    varietal: 'Lambrusco Grasparossa',
    varietal_zh: '蘭布魯斯科（葛拉斯帕羅薩）',
    region: 'Castelvetro, Emilia-Romagna',
    region_zh: '卡斯特爾韋特羅',
    country: 'Italy',
    country_zh: '義大利',
    year: 2023,
    abv: 11.5,
    sweetness: '乾型',
    classification: 'Lambrusco Grasparossa di Castelvetro DOC',
    price: 720,
    bottles: 6,
    price_tier: '$',
    market_price_twd: '約 NT$650–950',
    rating: 4,
    tasting_date: '2026-06-03',
    occasion: '在家品飲',
    aroma: ['黑櫻桃', '野莓', '肉桂', '石墨', '紫羅蘭'],
    palate: ['中等酒體', '細緻氣泡', '柔順單寧'],
    finish: '乾爽收尾，帶櫻桃果韻與一絲細微單寧',
    pairing: ['千層麵與紅醬義大利麵', '義式臘腸冷盤', '鹹酥雞與炸物', '滷味', '陳年硬質乳酪'],
    pairing_note: '乾型葛拉斯帕羅薩的氣泡與酸度能洗去油脂、單寧又對得起肉香，所以無論義式油潤料理、還是台式炸物、滷味都很合拍。',
    varietal_note: '葛拉斯帕羅薩（Grasparossa）是蘭布魯斯科大家族裡顏色最深、單寧最明顯、酒體也最厚實的一支，名字來自秋天會轉紅的葡萄梗。和清爽花香的 Sorbara 不同，它喝起來更像「會冒泡的紅酒」，是想從白氣泡跨到紅酒的新手很好的橋樑。',
    region_note: '卡斯特爾韋特羅是摩典納南方的丘陵帶，被視為葛拉斯帕羅薩最經典的故鄉，這裡的版本顏色更深、酒體更有勁。也是巴薩米可醋與帕瑪森乳酪的同鄉，飲食文化偏濃郁油潤，氣泡紅酒正好解膩。',
    classification_note: 'DOC 是義大利第二高的法定產區等級。看到「卡斯特爾韋特羅葛拉斯帕羅薩 DOC」，代表它受產區規範約束——至少 85% 用葛拉斯帕羅薩、限定摩典納一帶丘陵產地。等級越高，產地與品種的綁定就越嚴格。',
    producer_note: '佩德札納是摩典納卡斯特爾韋特羅一帶的家族小農酒莊，園區位於 Solignano Vecchio 丘陵，幾乎只種葛拉斯帕羅薩，走手工採收、忠於風土的路線；他們甚至保留了一支自家篩選、曾與波隆那大學合作研究的獨特老品系（clone，即從同一株母藤複製出的品系）。',
    why_beginner: '氣泡讓單寧顯得柔順、酒精也不高（約 11.5%），喝起來比一般靜態紅酒輕鬆，是想嘗試「紅酒口感」又怕太澀的新手很好的入門選擇；只是它是乾型，比甜味蘭布魯斯科多一點骨架。',
    drink_window: '現在 – 2027',
    serve_temp: '12–14°C',
    decant: '不需要醒酒；氣泡酒開瓶即飲，稍微冰鎮就好，醒酒反而會讓氣泡跑掉。',
    background: '這支由家族小農酒莊 Tenuta Pederzana（佩德札納）釀造，屬卡斯特爾韋特羅 DOC，用的是蘭布魯斯科家族裡顏色最深、最有酒體的葛拉斯帕羅薩。它是乾型（secco），和超市常見的甜味蘭布魯斯科很不一樣——多了單寧骨架、少了甜。葡萄手工採收，於水泥槽培養約七個月，再經自然二次發酵產氣，走較手工、忠於風土的做法，不是工業化大槽量產。酒精約 11.5%，稍微冰鎮後最能凸顯果香與氣泡活力。',
    notes_short: '顏色深、單寧柔、乾型的「氣泡紅酒」，小農風土版蘭布魯斯科',
    notes_long: '乾型的氣泡紅，清爽解膩，比想像中好入口。',
    color_hex: '#5A1320',
    beginner_friendly: true,
    style_axis: 75,
    style_note: '原生品種葛拉斯帕羅薩＋家族獨家老品系、水泥槽培養與自然二次發酵的小農做法，刻意保留產地個性而非追求國際討喜，明顯偏風土那一端。',
    image: null,
  },
  {
    id: 'lambrusco-spiriti-folletti',
    region_key: 'emilia-romagna',
    category: 'wine',
    type: 'sparkling-red',
    type_zh: '氣泡紅酒',
    name_en: 'Spiriti Folletti',
    name_zh: '頑皮精靈 葛拉斯帕羅薩',
    producer: 'Tenuta Pederzana',
    varietal: 'Lambrusco Grasparossa',
    varietal_zh: '蘭布魯斯科（葛拉斯帕羅薩）',
    region: 'Castelvetro, Emilia-Romagna',
    region_zh: '卡斯特爾韋特羅',
    country: 'Italy',
    country_zh: '義大利',
    year: null,
    abv: 11,
    sweetness: '乾型',
    classification: 'Lambrusco Grasparossa di Castelvetro DOC',
    price: 800,
    price_estimated: true,
    bottles: 2,
    price_tier: '$$',
    market_price_twd: '約 NT$700–1,000',
    rating: 3.8,
    tasting_date: '2026-06-03',
    occasion: '在家品飲',
    aroma: ['黑櫻桃', '野草莓', '紫羅蘭', '李子', '些許土壤氣息'],
    palate: ['細緻氣泡', '明亮酸度', '明顯而細緻的單寧'],
    finish: '尾韻乾爽、帶鹹鮮感，單寧明顯但不刺口，餘味留有莓果清新',
    pairing: ['鹹酥雞與炸物', '台式香腸', '滷味', '披薩', '帕瑪森乳酪火腿冷盤'],
    pairing_note: '微氣泡與酸度能解膩、清爽口腔，特別適合台灣的鹹酥雞、香腸與滷味。',
    varietal_note: '葛拉斯帕羅薩（Grasparossa）是蘭布魯斯科大家族裡顏色最深、單寧最明顯、酒體也最厚實的一支，名字來自秋天會轉紅的葡萄梗。和清爽花香的 Sorbara 不同，它喝起來更像「會冒泡的紅酒」，是想從白氣泡跨到紅酒的新手很好的橋樑。',
    region_note: '卡斯特爾韋特羅是摩典納南方的丘陵帶，被視為葛拉斯帕羅薩最經典的故鄉；相較於平原區的蘭布魯斯科，這裡的丘陵與黏土被認為能釀出更有層次、結構更扎實的版本。',
    classification_note: 'DOC 是義大利的法定產區認證。這支來自葛拉斯帕羅薩最核心的卡斯特爾韋特羅產區，法規要求至少 85% 用葛拉斯帕羅薩，而這支更採 100%，等於替你把關了品種與產地的純正度。',
    producer_note: '與「傳統款」同一家：佩德札納家族酒莊，專注葛拉斯帕羅薩。這支用的是酒莊自家保存的歷史老品系、手工採收，是一座規模約十幾公頃的小型家族園，產量不大。',
    why_beginner: '不甜、酒精僅約 11%、帶清爽氣泡與莓果香，單寧雖然比一般蘭布魯斯科明顯，但仍細緻、又能解膩，是很友善的氣泡紅酒入門款。',
    drink_window: '現在 – 2027',
    serve_temp: '12–14°C',
    decant: '不需要醒酒；氣泡紅酒講求新鮮，冰鎮後直接倒進杯子喝即可。',
    background: '「Spiriti Folletti（頑皮精靈）」同樣出自家族酒莊 Tenuta Pederzana（佩德札納），葡萄手工採收自 Solignano Vecchio 的丘陵園，採酒莊自家保存的老品系、100% 葛拉斯帕羅薩。釀法為不鏽鋼槽主發酵後，於加壓鋼槽進行二次發酵產生氣泡（Charmat 法，即在大鋼槽裡產氣的氣泡酒做法），屬乾型（secco）微氣泡紅酒，酒精約 11%。它和同酒莊的傳統款一樣不甜，但單寧更明顯一些。市面多以非年份（NV）販售。',
    notes_short: '來自核心產區的家族小農微氣泡紅酒，不甜、莓果香、解膩好搭',
    notes_long: '氣泡跟莓果味很討喜，尾韻稍微澀一些，沒有前一支那麼滑。',
    color_hex: '#5A1226',
    beginner_friendly: true,
    style_axis: 62,
    style_note: '出自核心卡斯特爾韋特羅產區、家族小農、堅持自家老品系，風土個性鮮明；但仍採鋼槽二次發酵（Charmat 法）的量產工藝、風格平易，因此偏向風土端但不極端。',
    image: null,
  },
  {
    id: 'lambrusco-cella',
    region_key: 'emilia-romagna',
    category: 'wine',
    type: 'sparkling-red',
    type_zh: '氣泡紅酒',
    name_en: 'Cella Lambrusco Amabile',
    name_zh: 'Cella 微甜蘭布魯斯科',
    producer: 'Fratelli Cella',
    varietal: 'Lambrusco',
    varietal_zh: '蘭布魯斯科',
    region: 'Emilia',
    region_zh: '艾米利亞',
    country: 'Italy',
    country_zh: '義大利',
    year: null,
    abv: 8,
    sweetness: '微甜',
    classification: 'Lambrusco dell\'Emilia IGT',
    price: 279,
    bottles: 1,
    price_tier: '$',
    market_price_twd: '約 NT$250–350',
    rating: 3.5,
    tasting_date: '2026-06-04',
    occasion: '簡單小聚會',
    aroma: ['紅櫻桃', '草莓', '葡萄果汁', '淡淡紫羅蘭'],
    palate: ['微甜', '輕氣泡', '酒體輕盈'],
    finish: '收尾短而甜潤，氣泡輕快、單寧幾乎感覺不到，餘味是直接的莓果與葡萄汁感',
    pairing: ['瑪格麗特披薩', '鹹酥雞', '炸雞', '美式炸物', '派對小點'],
    pairing_note: '微甜加上輕氣泡，最適合解油炸、鹹香的派對食物——披薩、炸雞、鹹酥雞都很對味；甜度也讓不太能接受乾型紅酒的朋友更容易入口。冰涼喝最舒服，當輕鬆聚會的「氣泡飲料感」紅酒就對了。',
    varietal_note: '蘭布魯斯科其實不是單一品種，而是一個有數十個成員的大家族。這支不像你的兩支葛拉斯帕羅薩只用單一品系，而是把多個品系混在一起調配（Salamino、Grasparossa、Marani、Maestri），目的是釀出風味穩定、討喜易飲的量產酒。對新手來說，記住「蘭布魯斯科＝微氣泡的紅葡萄酒家族」就夠了，甜的、乾的都有。',
    region_note: '艾米利亞-羅馬涅是蘭布魯斯科的大本營，也是巴薩米可醋、帕瑪森乳酪、義式火腿的故鄉，當地飲食濃郁油潤，微氣泡紅酒正好用來解膩配餐。IGT 標示的「艾米利亞」涵蓋範圍很廣，給了量產酒廠跨多個產區採購葡萄、調配穩定風味的彈性。',
    classification_note: 'IGT（地理標示保護）是義大利葡萄酒分級裡較寬鬆的一級，只規範葡萄大致來自某個地理範圍（這裡是「艾米利亞」），對品種、產量、釀法的限制都比 DOC 鬆很多。你另外兩支葛拉斯帕羅薩是 DOC（法定產區），產地與品種綁定更嚴格、更講究；這支是 IGT，等於給了酒廠較大的混調與量產彈性。簡單記：DOC 比 IGT 更嚴、更看重產地個性。',
    producer_note: 'Fratelli Cella（雀拉）創立於 1960 年，總部在艾米利亞-羅馬涅的 Campegine，是義大利最知名的商業蘭布魯斯科品牌之一，行銷全球四十多國，隸屬大型釀酒合作社聯盟 Cantine Riunite & CIV，走規模化、標準化的量產路線。',
    why_beginner: '微甜、輕氣泡、酒精很低（約 8%），喝起來幾乎像有氣泡的莓果葡萄汁，沒什麼單寧澀感，是怕紅酒苦澀的新手最沒壓力的入門選擇；價格親民、超市就買得到，當派對輕鬆飲也很合適。',
    drink_window: '趁新鮮喝（NV，越快越好）',
    serve_temp: '6–8°C（冰透喝最解膩）',
    decant: '不需要醒酒；氣泡酒講求新鮮，冰透後直接開瓶倒進杯子即可，醒酒反而會讓氣泡跑掉。',
    background: '這支由 Fratelli Cella（雀拉，創立於 1960 年）釀造，隸屬大型釀酒合作社 Cantine Riunite & CIV，屬 Lambrusco dell\'Emilia IGT。它是典型的「超市甜型蘭布魯斯科」：微甜（Amabile）、輕氣泡（Frizzante）、酒精僅約 8%，由多個蘭布魯斯科品系混調、規模化量產，主打討喜易飲、風味穩定。它和你另外兩支佩德札納的葛拉斯帕羅薩剛好形成鮮明對比：那兩支是小農手工、乾型、單一品系、DOC 法定產區、強調風土個性；這支則是合作社量產、微甜、多品系混調、IGT 寬鬆分級、走國際大眾口味。沒有好壞之分，只是定位不同——就是平價、輕鬆、隨手喝的派對氣泡紅。',
    notes_short: '超市平價微甜輕氣泡紅，低酒精、解膩好入口的派對酒',
    notes_long: '全聯架上隨手帶的，才 279，本來就沒抱期待。微甜、帶點氣泡，冰透了配披薩、炸雞意外順口；尾韻確實有那麼一絲廉價酒精感，但這價錢真的沒什麼好嫌的。不是會讓你停下來細品的酒，而是簡單小聚、請朋友隨興喝，或自己在家配宵夜的那種「日常款」——3.5 分，老實講是給它的 CP 值。',
    color_hex: '#7A1B2E',
    beginner_friendly: true,
    style_axis: 15,
    style_note: '典型的工業量產、超市派蘭布魯斯科：大型合作社規模化生產、多品系混調、IGT 彈性分級、走微甜討喜的國際大眾口味，刻意追求風味穩定一致而非凸顯產地個性，因此明顯落在「國際標準化」這一端。對照兩支佩德札納小農乾型葛拉斯帕羅薩（風土端），差異一目了然。',
    image: null,
  },
  {
    id: 'cave-mont-blanc-blanc-du-blanc',
    region_key: 'valle-aosta',
    category: 'wine',
    type: 'sparkling-white',
    type_zh: '氣泡白',
    name_en: 'Blanc du Blanc Brut · Metodo Classico',
    name_zh: '白朗峰 中白傳統法氣泡',
    producer: 'Cave Mont Blanc',
    varietal: 'Prié Blanc',
    varietal_zh: '普里耶白',
    region: 'Valle d\'Aosta',
    region_zh: '奧斯塔谷',
    country: 'Italy',
    country_zh: '義大利',
    year: null,
    abv: 11.5,
    sweetness: '乾型（Brut）',
    classification: 'Valle d\'Aosta DOC',
    price: null,
    bottles: 1,
    price_tier: '$$',
    market_price_twd: '台灣代理原價約 NT$1,900（本次活動 4 支套組價更低）',
    rating: null,
    tasting_date: '2026-06-18',
    occasion: '越昇環義品飲課程 · 高海拔雙產區（活動購入 4 支套組）',
    highlights: [
      '歐洲最高酒廠：在海拔 2,173m 的纜車站釀氣泡',
      '未嫁接的「前根瘤蚜時代」純血老藤，全球罕見',
      '與香檳同源的傳統瓶中二次發酵（Metodo Classico）',
      '奧斯塔谷原生稀有品種，離開產區幾乎喝不到',
    ],
    appearance: '明亮麥稈黃帶綠色反光，氣泡細緻而持久。',
    aroma: ['紫藤白花', '青蘋果', '柑橘皮', '礦石', '一絲番紅花'],
    palate: ['鮮爽', '酸度為骨幹', '礦物感明顯', '綿密氣泡', '酒體輕盈'],
    finish: '礦石主導、乾淨俐落的尾韻，帶柑橘與「濕岩石」般的清涼餘味，持久而優雅。',
    pairing: ['生蠔', '握壽司', '生魚片', '天婦羅', '鹹酥雞', '清蒸海鮮'],
    pairing_note: '高酸與礦物鹹感能把油脂洗乾淨、替海鮮提鮮，氣泡又解炸物的膩，是最百搭的開場酒；避免重醬、重辣，以免蓋過它清秀的高山個性。',
    varietal_note: '普里耶白（Prié Blanc）是奧斯塔谷的原生稀有白葡萄，幾乎只種在白朗峰腳下的 Morgex 與 La Salle 兩個鄉鎮，是全義大利最「在地限定」的品種之一，最早文獻可追溯到 1691 年。它極早熟（九月初就採收）、果皮極薄、天生高酸、酒精偏低——正是它做氣泡酒能保持鮮爽骨架的本錢。對新手來說，這是一支離開產區幾乎喝不到的品種，喝它本身就是在認識一個你可能一輩子只會遇到一兩次的葡萄。',
    region_note: '奧斯塔谷是義大利面積最小、海拔最高、最靠阿爾卑斯的葡萄酒產區，就位在白朗峰腳下。這支來自上游的「Blanc de Morgex et de La Salle」子產區：葡萄園海拔約 900–1,200 公尺（法規甚至允許到 1,300m），是歐洲最高的葡萄園之一。土壤是排水極佳的冰磧砂礫土，日夜溫差極大，賦予它鮮明的花香、礦石感與高酸度。',
    vinification_note: '葡萄藤採貼地的「低棚架」（pergola valdostana）整枝，棚面離地僅約 0.5–1.4 公尺，為的是吸收地面輻射熱、抵禦強風與大雪。這裡最珍貴的是葡萄藤為「未嫁接」的純血歐洲原生根——因為高海拔太冷，19 世紀末摧毀全歐葡萄園的根瘤蚜在此活不了，保留了罕見的「前根瘤蚜時代」老藤。\n\n釀法採與香檳同源的傳統瓶中二次發酵（Metodo Classico）：基酒先在不鏽鋼槽與大木桶完成第一次發酵，裝瓶後加糖加酵母在瓶中進行二次發酵，於酒渣（lees，發酵後沉澱的酵母）上陳年約 24 個月才除渣——這正是氣泡綿密、帶麵包皮香氣的來源。',
    classification_note: 'DOC（法定產區）是義大利的中階品質分級，代表產地、品種與釀法都受法規規範。「Valle d\'Aosta DOC」底下再細分出「Blanc de Morgex et de La Salle」這個高山子產區，等於替「白朗峰腳下、普里耶白釀的高山酒」做了產地背書。',
    producer_note: 'Cave Mont Blanc 是 1983 年成立的釀酒「合作社」，把約 70 戶高山葡農、合計約 18 公頃葡萄園集結起來，共同守護這片風土。氣泡酒 1986 年首釀只做了約 1,000 瓶，如今年產約 10 萬瓶。最傳奇的是它在海拔 2,173 公尺的纜車站（Pavillon du Mont Fréty）設了酒窖——號稱全歐洲最高的酒廠，2025 年 2 月才落成新廠，把瓶中二次發酵直接放在高山低溫、低氣壓的環境裡養氣泡。',
    why_beginner: '氣泡＋高酸＋低酒精（約 11.5%）讓它清爽好入口、幾乎沒有壓力，是最理想的開場餐前氣泡；又因為夠特別（歐洲最高葡萄園、稀有品種），喝起來既輕鬆又長知識，對新手非常友善。',
    drink_window: '現在 – 購入後約 1–3 年（趁新鮮喝最佳）',
    serve_temp: '6–8°C',
    decant: '不需要醒酒；冰鎮後直接享用即可。用鬱金香型氣泡杯（比細長笛型杯更能展開高山花香與礦物層次）。',
    background: 'Cave Mont Blanc 同廠還有更極致的版本：頂級的「Cuvée des Guides」二次發酵與約 30–36 個月酒渣陳年，都直接在海拔 2,173 公尺的高山酒窖完成，且為完全不加糖的 Brut Nature。本支 Blanc du Blanc Brut 是它最親民的「名片款」，用同一套高山風土與傳統工法，讓人用入門價格就喝到歐洲最高葡萄園的滋味。',
    tasting_focus: '品飲練習：先聞花香（紫藤、丁香）→ 再找礦石與柑橘 → 最後感受尾韻那股「濕岩石」般的清涼感。順便比較這股麵包／酵母香（傳統瓶中二次發酵的標記）和一般大槽法便宜氣泡酒的差別——走完這三段層次，你就掌握了高山氣泡酒的品飲框架。',
    notes_short: '歐洲最高葡萄園、未嫁接老藤釀的高山傳統法氣泡，清爽礦感、最理想的開場',
    notes_long: null,
    color_hex: '#E9E2B0',
    beginner_friendly: true,
    style_axis: 88,
    style_note: '原生稀有品種普里耶白、未嫁接老藤、歐洲最高葡萄園的極端風土，加上小農合作社的傳統工法，辨識度極高——幾乎是「風土個性」這一端的教科書。',
    image: null,
  },
  {
    id: 'grosjean-petite-arvine-rovettaz',
    region_key: 'valle-aosta',
    category: 'wine',
    type: 'white',
    type_zh: '白酒',
    name_en: 'Petite Arvine Vigne Rovettaz',
    name_zh: '葛羅讓 小奧文 羅維塔茲園',
    producer: 'Grosjean',
    varietal: 'Petite Arvine',
    varietal_zh: '小奧文',
    region: 'Valle d\'Aosta',
    region_zh: '奧斯塔谷',
    country: 'Italy',
    country_zh: '義大利',
    year: 2021,
    abv: 14,
    sweetness: '乾型',
    classification: 'Valle d\'Aosta DOC',
    price: null,
    bottles: null,
    price_tier: '$$',
    market_price_twd: '約 NT$1,200–1,600（國際零售推估）',
    rating: null,
    tasting_date: '2026-06-18',
    occasion: '越昇環義品飲課程 · 高海拔雙產區',
    highlights: [
      '源自瑞士瓦萊的「孤兒品種」，台灣極罕見',
      '招牌指紋：收尾那一抹「鹹味 salinity」',
      '奧斯塔谷第一家有機認證酒莊（2011 年）',
      '陡坡正南、薄石礫土的單一園 Vigne Rovettaz',
    ],
    appearance: '明亮稻草黃至淺金黃，清澈帶光澤。',
    aroma: ['葡萄柚', '檸檬', '白花', '青蘋果', '百香果', '茴香'],
    palate: ['中等偏飽滿', '檸檬酸度', '密實礦物與鹹感', '白桃', '微蜂蜜杏仁'],
    finish: '悠長而爽口，以鹹鮮礦物與柑橘餘韻收尾——這就是 Petite Arvine 最迷人的記憶點。',
    pairing: ['清蒸魚', '生魚片壽司', '白灼蝦', '鹽烤魚', '蛤蜊絲瓜', '海南雞飯'],
    pairing_note: '高酸＋鹹礦物的個性百搭海鮮河鮮：能借鹹感與酸度替清蒸魚、白灼蝦提鮮、解膩；避免重辣重醬，以免蓋過它細緻的礦物。',
    varietal_note: '小奧文（Petite Arvine）是個對台灣酒友很陌生、行家圈卻評價極高的稀有白葡萄。它原生於瑞士瓦萊州，1602 年即有文獻記載，DNA 至今找不到親本、是個「孤兒品種」，被譽為瓦萊白酒的「Diva（首席女伶）」，二十世紀中由 Joseph Vaudan 教士引進奧斯塔谷。名字裡的「Petite」指的是小果粒。它最招牌的，就是收尾那一抹像「鹽之花」的鹹鮮味——這是辨識 Petite Arvine 的指紋特徵。',
    region_note: '奧斯塔谷是義大利最小、最高、最靠阿爾卑斯的葡萄酒產區，高山大陸性氣候、日夜溫差大，有利保酸與累積香氣。羅維塔茲園（Vigne Rovettaz）是 Quart 鎮的單一園（cru），海拔約 550 公尺、陡坡、正南向以爭取最大日照；土層薄（不到 50 公分）、砂質夾大量石礫、排水極佳——逼根深扎，正是它鹹礦感的來源。',
    vinification_note: '手工採收後整串壓榨，果汁以浮選（flotation）澄清；以選育酵母在不鏽鋼槽發酵，帶酒渣（lees）長時間培養，第一個月持續攪桶（bâtonnage）增加質地與圓潤度。陳年採混合方式：約 70% 留在不鏽鋼、約 30% 移入法國橡木桶（barrique，約半數新桶），均帶細酒渣培養約 8 個月後再調配——目的是保留品種純淨的果香與鹹度，用少量橡木增添層次而不搶戲。酒精約 14%，屬有機認證酒。',
    classification_note: 'DOC（法定產區）是義大利的中階品質分級，規範產地、品種與釀法。看到「Valle d\'Aosta DOC（法文 Vallée d\'Aoste）」，代表這支是道地、受法規約束的奧斯塔谷高山酒；標單一品種者，該品種通常要占絕大多數。',
    producer_note: '葛羅讓兄弟酒莊（Maison Vigneronne Frères Grosjean）位在奧斯塔谷 Quart 鎮的 Ollignan 小村，是典型「英雄式高山葡萄種植」（陡坡、人工）。家族根源可溯至 18 世紀末，現代酒莊由祖父 Dauphin Grosjean 約 1968 年正式創立；常被提到的五兄弟（Vincent、Giorgio、Marco、Fernando、Eraldo）是第二代，2018 年起已交棒第三代經營。環保走得很早——1975 年起就不噴殺蟲劑，並於 2011 年成為奧斯塔谷第一家通過有機認證的酒莊。',
    why_beginner: '它酸度漂亮、香氣奔放（葡萄柚、白花、百香果），雖然酒精約 14%，但靠清爽酸度撐起來不顯重，整體清新好入口；最棒的是它帶來一個你味覺清單裡可能還沒出現過的新體驗——「鹹味白酒」，學起來很有成就感。',
    drink_window: '現在 – 2030',
    serve_temp: '10–12°C',
    decant: '不需要醒酒；別冰過頭（10–12°C 最佳），太冰會把香氣與鹹感都鎖住。開瓶後在杯中等 10–15 分鐘、或稍微回溫，鹹礦物與果香會更立體。',
    background: 'Petite Arvine 在瑞士瓦萊與義大利奧斯塔谷都被視為旗艦白葡萄，但全球種植極少、台灣相當罕見。這支來自 Grosjean 家族的旗艦單一園 Vigne Rovettaz，有機種植；酒莊更高階的 Petite Arvine「Les Frères」曾獲 Gambero Rosso 紅蝦評鑑最高的三隻酒杯肯定（那是另一款酒），可見其 Petite Arvine 的整體水準。',
    tasting_focus: '品飲練習：第一，刻意留意舌尖／喉頭收尾那股像鹽之花的鹹鮮感，把這個「鹹味白酒」的味覺記憶記起來。第二，體會「高海拔＝高酸＋礦物」的邏輯，和你喝過的平地白酒做對比。第三，拿它配一道清蒸魚或白灼蝦，感受酸與鹹如何把海鮮的鮮甜放大、把油膩沖淡——這是白酒佐餐最直觀的一課。',
    notes_short: '瓦萊「孤兒品種」的稀有高山白，招牌鹹礦感，認識「鹹味白酒」的教科書',
    notes_long: null,
    color_hex: '#E0D284',
    beginner_friendly: true,
    style_axis: 82,
    style_note: '稀有原生品種、有機單一園、薄石礫陡坡的鮮明鹹礦個性，明顯偏風土；唯約三成法國橡木桶培養帶來一點國際化的圓潤質地，因此沒有更極端。',
    image: null,
  },
  {
    id: 'elena-walch-lagrein',
    region_key: 'trentino-alto-adige',
    category: 'wine',
    type: 'red',
    type_zh: '紅酒',
    name_en: 'Lagrein Alto Adige',
    name_zh: '伊蓮娜·瓦爾希 拉格萊因',
    producer: 'Elena Walch',
    varietal: 'Lagrein',
    varietal_zh: '拉格萊因',
    region: 'Alto Adige',
    region_zh: '上阿迪杰',
    country: 'Italy',
    country_zh: '義大利',
    year: 2022,
    abv: 13.5,
    sweetness: '乾型',
    classification: 'Alto Adige DOC',
    price: null,
    bottles: null,
    price_tier: '$$',
    market_price_twd: '約 NT$1,000–1,400（國際零售推估）',
    rating: null,
    tasting_date: '2026-06-18',
    occasion: '越昇環義品飲課程 · 高海拔雙產區',
    highlights: [
      'Bolzano 原生紅葡萄，1970s 幾乎絕種後復興',
      'Teroldego 的後代、黑皮諾的「孫輩」',
      '招牌「苦杏仁」微苦尾韻 + 近墨深色',
      '與你的上阿迪杰黑皮諾同產區，最佳對照組',
    ],
    appearance: '濃郁石榴紅至近墨紫、邊緣帶紫，倒進杯中幾乎不透光。',
    aroma: ['黑櫻桃', '成熟黑莓', '藍莓', '李子', '紫羅蘭', '可可肉桂'],
    palate: ['中等酒體', '多汁深色果', '單寧明顯但相對柔順', '酸度爽脆', '鐵礦鹹鮮'],
    finish: '悠長多汁，收在 Lagrein 標誌性的微苦——苦杏仁／黑巧克力／咖啡感的清爽收口，讓濃郁果味不顯甜膩。',
    pairing: ['滷牛腱', '紅燒牛肉麵', '三杯雞', '黑胡椒牛排', '北京烤鴨', '廣式叉燒'],
    pairing_note: '紮實單寧＋鮮明酸度＋微苦尾韻使它非常百搭重口味：滷味、紅燒、燒臘、麻辣鍋都接得住，微苦尾韻還能呼應醬油與燒烤的焦香。',
    varietal_note: '拉格萊因（Lagrein）是發源於上阿迪杰首府 Bolzano（波札諾）周邊溫暖谷地的原生紅葡萄。身世精彩：DNA 確認它是 Teroldego（特洛迪歌）的後代、黑皮諾的「孫輩」、Marzemino 的姊妹。它 13 世紀就有記載，但 15 世紀後被高產的 Schiava 排擠，到 1970 年代幾乎絕種（僅剩約 50 公頃），靠在地人救回；至今仍稀有（全球約 537 公頃）。特徵是色深近墨紫、單寧紮實、酸度鮮明，最招牌的是尾韻那一抹「苦杏仁／黑巧克力」的微苦收口。',
    region_note: '上阿迪杰是義大利最北、阿爾卑斯山環抱的產區。Lagrein 是晚熟、需要熱量的品種，所以種在產區最溫暖的低海拔河谷（約 200–300 公尺、Bolzano 盆地周邊），排水好、白天蓄熱讓它熟透，夜間山區冷空氣保住酸度與香氣。有趣的對照是：同產區的黑皮諾嬌氣、種在涼爽的中高海拔坡地，Lagrein 則強壯、種在最熱的谷底——剛好是上阿迪杰紅酒的兩個極端。',
    vinification_note: '手工採收，於最佳成熟度進場；傳統控溫發酵約 10 天於不鏽鋼槽萃取色素與單寧，蘋果酸乳酸發酵（柔化酸度）在大型橡木桶中完成，桶型為 70hl 與 22hl 的法國與斯拉沃尼亞大桶，之後於大桶陳年數月。這是「以大桶輕修飾、柔化單寧並增添可可肉桂香」的風格，刻意不給明顯新桶味——與酒莊頂級的單一園 Castel Ringberg Lagrein Riserva（20 個月法國小新桶 barrique）明顯不同。殘糖極低（2022 年份約 3.4 g/L），是不甜紅酒，酒精約 13.5%。',
    classification_note: 'DOC（法定產區）是義大利的中階品質分級，規範產地、品種與釀法。「Alto Adige DOC」涵蓋這個阿爾卑斯產區的多種品種；標單一品種（如 Lagrein）者，代表它以該品種為主、產自法規劃定的上阿迪杰範圍。',
    producer_note: '伊蓮娜·瓦爾希（Elena Walch）是上阿迪杰公認的指標酒莊之一，位在 Tramin 小鎮，家族釀酒史溯至 1869 年，酒窖約 300 年。靈魂人物 Elena Walch 建築師出身，1985 年成為南提洛第一位女釀酒師，1988 年創立自有品牌，把「風土＋單一園」的現代觀念帶進產區；現由女兒 Julia 與 Karoline 接手（第五代）。旗下有兩座名園 Castel Ringberg 與 Kastelaz，酒莊近年轉型有機、2024 年取得 VIVA 永續認證。台灣由越昇國際代理進口。',
    why_beginner: '它單寧雖明顯，但在這個常規等級相對柔順，加上果味奔放、酸度爽脆，是很友善的紅酒入門款；配滷味、牛肉麵這類台味重口料理就很好喝，也不必久放——買來現在就能享用。',
    drink_window: '現在 – 2028',
    serve_temp: '15–18°C',
    decant: '年輕的 2022 可開瓶前醒酒約 30–60 分鐘，讓單寧鬆開、苦韻更圓潤；偏涼上桌（15–18°C）更能凸顯清爽。用波爾多型大肚杯聚攏深色果香。',
    background: 'Lagrein 是一段「差點消失、靠在地人救回」的復興故事：1970 年代幾乎絕種，80 年代品質革命後才重返舞台。Elena Walch 的這支屬入門到中階、走量的核心款（2022 年約 5,000 箱），用大桶輕修飾保留品種純淨的深色果味與微苦個性，供應與價格都相對親民，是認識 Lagrein 很理想的起點。',
    tasting_focus: '品飲練習：(1) 記兩個招牌記號——眼睛看「色深近墨」、尾韻嚐「苦杏仁／黑巧克力的微苦收口」，以後盲飲就抓得到 Lagrein。(2) 務必和你的「聖米歇爾-艾本 黑皮諾」並排喝（先黑皮諾、後 Lagrein）：同樣來自上阿迪杰，黑皮諾輕巧紅果、種在涼爽高坡，Lagrein 深色厚實、種在最熱谷底——一次就懂「同產區、不同品種與海拔」風格差多少。',
    notes_short: '差點絕種、被救回的上阿迪杰原生紅，色深、微苦尾韻，與黑皮諾的最佳同產區對照',
    notes_long: null,
    color_hex: '#3A0E1C',
    beginner_friendly: true,
    style_axis: 66,
    style_note: '稀有原生品種 Lagrein、上阿迪杰特定風土，本就偏風土；但 Elena Walch 是現代化名莊、此款走大桶輕修飾的核心量產路線，風格乾淨易親近，因此落在偏風土但不極端。',
    image: null,
  },
  {
    id: 'floramundi-cerasuolo-vittoria',
    region_key: 'sicilia',
    category: 'wine',
    type: 'red',
    type_zh: '紅酒',
    name_en: 'Floramundi Cerasuolo di Vittoria',
    name_zh: '多娜佳塔 弗洛拉蒙地',
    producer: 'Donnafugata',
    varietal: 'Nero d\'Avola · Frappato',
    varietal_zh: '黑達沃拉 · 弗萊帕托',
    region: 'Vittoria, Sicily',
    region_zh: '西西里',
    country: 'Italy',
    country_zh: '義大利',
    year: 2023,
    abv: 13.5,
    sweetness: '乾型',
    classification: 'Cerasuolo di Vittoria DOCG',
    price: null,
    bottles: null,
    price_tier: '$$',
    market_price_twd: '約 NT$1,260–1,400',
    rating: null,
    tasting_date: '2026-06-08',
    occasion: '想喝清單 · 西西里',
    highlights: [
      '西西里「唯一」DOCG：Cerasuolo di Vittoria（2005 升格，島上第一也是唯一）',
      '西西里名莊多娜佳塔（Donnafugata）的代表作',
      '兩大原生品種：Nero d\'Avola（王者結構）＋ Frappato（鮮果花香）',
      '明亮櫻桃紅、單寧細、酸度爽——可微冰、超順口的餐桌紅',
      '著名藝術酒標：花卉新藝術 × 西西里傳統木偶意象',
    ],
    appearance: '明亮的櫻桃紅至寶石紅、帶紫色光澤，色澤清透鮮活——正是「Cerasuolo（櫻桃紅）」之名的由來。',
    aroma: ['紅櫻桃', '草莓', '覆盆子', '紫羅蘭花香', '地中海香草', '黑胡椒'],
    palate: ['輕至中等酒體', '單寧細柔滑順', '酸度清爽活潑', '多汁鮮果主導', '一絲血橙與香料'],
    finish: '清新多汁的收尾，紅櫻桃與淡淡花香、香料尾韻，順口好喝、不澀不重。',
    pairing: ['番茄紅醬義大利麵', '烤雞', '披薩', '滷肉飯', '三杯雞', '紅燒家常菜', '微辣川菜／泰式'],
    pairing_note: '果味奔放、單寧細、酸度爽，是非常百搭的「餐桌酒」。稍微冰一下喝，酸度能解油膩、襯托番茄與醬汁的鮮甜；台菜的滷肉飯、三杯雞、紅燒類醬香與油脂它都接得住，面對微辣（川菜、泰式）也比厚重高單寧紅酒更不易「打架」。',
    varietal_note: '這是西西里兩個原生紅葡萄的經典組合。Nero d\'Avola（黑達沃拉，當地別名 Calabrese）被稱為「西西里紅葡萄之王」，提供酒體、結構與成熟黑／紅果的厚度；Frappato（弗萊帕托）是島上最古老品種之一，色淺、單寧細、酸度活潑，帶來鮮明的紅櫻桃、草莓果香與花香。兩者一搭，剛好是「有骨架但不厚重、果味奔放又好喝」，對新手非常友善。',
    region_note: '產區位於西西里島東南角、拉古薩（Ragusa）省的維多利亞（Vittoria）一帶，鄰近 Acate、Comiso 等鄉鎮。這裡日照充足、地中海氣候溫暖乾燥，多為砂質與紅土土壤，海風調節溫度，賦予葡萄成熟果味又保有清爽酸度，正是釀出明亮「櫻桃紅」風格的關鍵。',
    vinification_note: '兩個品種分開於不鏽鋼槽發酵，帶皮浸泡（macération）約 10 天、控溫 25–28°C 萃取色澤與果味；完成乳酸發酵後，於不鏽鋼槽熟成約 8–9 個月（保留鮮明果香、不過木桶），再瓶中靜置至少 3 個月後上市。整體走「鮮果與純淨度」路線，不刻意用新橡木桶壓味。',
    classification_note: 'Cerasuolo di Vittoria 是整個西西里島「唯一」的 DOCG（保證法定產區，義大利最高分級）。它 1973 年先取得 DOC、2005 年升格 DOCG，是西西里第一個、也是至今唯一一個。法規限定只能用 Nero d\'Avola（50–70%）與 Frappato（30–50%）兩個品種、最低酒精度 13%，另有更嚴格的 Classico 子產區。「Cerasuolo」意為「櫻桃紅」，直接點出這款酒明亮的酒色。',
    producer_note: '多娜佳塔（Donnafugata）由 Giacomo Rallo 與妻子 Gabriella 於 1983 年創立，背後是經營馬沙拉（Marsala）加烈酒已逾 150 年的拉羅（Rallo）家族。酒莊名「Donnafugata（逃亡的女人）」典出蘭佩杜薩的小說《豹》（Il Gattopardo）。如今由第二代姊弟 José 與 Antonio Rallo 共同經營，葡萄園遍及西西里多個產區（Contessa Entellina、馬沙拉、埃特納火山、維多利亞）與離島潘泰萊里亞，總面積逾 400 公頃，是西西里最具代表性、最受國際推崇的名莊之一。',
    why_beginner: '單寧細柔、酸度清爽、果味直接奔放，喝起來輕盈順口、完全沒有粗澀厚重感，還能稍微冰一下喝，很適合台灣天氣。又出自名莊、品質穩定，還是西西里唯一 DOCG，是踏入義大利紅酒、認識原生品種很友善的一支。',
    drink_window: '現在 – 2029（鮮果風格，趁年輕喝最能享受奔放果香）',
    serve_temp: '15–16°C',
    decant: '不需要長時間醒酒；開瓶後靜置或醒 15–20 分鐘即可。建議稍微冰鎮到 15–16°C 再喝，果香與清爽感最迷人。',
    background: 'Floramundi 是多娜佳塔在西西里唯一 DOCG——Cerasuolo di Vittoria——的代表作，由「西西里紅葡萄之王」Nero d\'Avola 約 70% 搭配古老品種 Frappato 約 30% 釀成。產區在西西里東南角維多利亞一帶，溫暖地中海氣候加海風，造就明亮櫻桃紅、果味奔放又清爽的風格；採不鏽鋼發酵、約 10 天浸皮、鋼槽熟成再瓶陳，刻意保留純淨鮮果味。酒名「Floramundi」意指「世界之花」，酒標由 Stefano Vitale 繪製，融合維多利亞當地的花卉新藝術（Liberty）風格與西西里傳統木偶（Pupi Siciliani）意象，是酒莊著名的藝術酒標之一。',
    tasting_focus: '品飲練習：先看酒色——它的「櫻桃紅、帶紫光澤、清透」正是 Cerasuolo 名字的由來，可和深濃厚重的紅酒對照。聞香找紅櫻桃、草莓、紫羅蘭（多半來自 Frappato）。入口練習感受三件事：單寧很細（不咬口）、酸度清爽（口水會分泌）、果味多汁；最後留意收尾的清新與一絲香料。可試著稍微冰鎮（15–16°C）前後各喝一口，體會溫度如何放大果香與爽口度。',
    notes_short: '西西里唯一 DOCG，黑達沃拉＋弗萊帕托的明亮櫻桃紅，單寧細、酸度爽、超順口的餐桌紅',
    notes_long: null,
    color_hex: '#B0263C',
    beginner_friendly: true,
    style_axis: 70,
    style_note: '西西里唯一 DOCG、兩個原生品種（Nero d\'Avola＋Frappato）的經典組合，風土辨識度高；但出自現代化名莊多娜佳塔、走不鏽鋼槽保留純淨鮮果的乾淨路線，因此偏風土但不極端。',
    image: null,
  },
  {
    id: 'grosjean-muscat-petit-grain',
    region_key: 'valle-aosta',
    category: 'wine',
    type: 'white',
    type_zh: '白酒',
    name_en: 'Muscat Petit Grain',
    name_zh: '葛羅讓 小粒種蜜思嘉',
    producer: 'Grosjean',
    varietal: 'Muscat Blanc à Petits Grains',
    varietal_zh: '小粒種蜜思嘉',
    region: 'Valle d\'Aosta',
    region_zh: '奧斯塔谷',
    country: 'Italy',
    country_zh: '義大利',
    year: null,
    abv: 13,
    sweetness: '乾型',
    classification: 'Valle d\'Aosta DOC',
    price: null,
    bottles: null,
    price_tier: '$$',
    market_price_twd: '約 NT$900–1,300（國際零售推估）',
    rating: null,
    tasting_date: null,
    occasion: '想喝清單 · 越昇採購（主選）',
    highlights: [
      '香氣甜美、入口卻乾爽——最容易誤判的「乾型蜜思嘉」',
      '與課堂酒同酒莊：奧斯塔谷有機先驅 Grosjean',
      '芳香品種無單寧、完全不澀，新手最無壓力的開胃白',
      '高山日夜溫差賦予清新酸度與礦石鹹尾',
    ],
    appearance: '明亮稻草黃、清澈帶光澤。',
    aroma: ['橙花', '白桃', '杏桃', '麝香', '檸檬', '鼠尾草薄荷'],
    palate: ['輕盈', '酸度清新', '花果奔放', '一絲礦石鹹感'],
    finish: '乾爽清新的尾韻，帶柑橘與淡淡杏仁微苦，收口俐落、不甜膩。',
    pairing: ['清蒸海鮮', '白灼蝦', '泰式涼拌', '越南春捲', '檸檬香茅雞', '生菜沙拉'],
    pairing_note: '奔放的花果香能柔化香料與微辣、清新酸度能解膩，最適合當開胃酒或配清爽海鮮、東南亞菜；但因為是乾型（無糖），面對「極辣」的緩衝力不如甜型蜜思嘉，吃很辣時改配甜一點的酒會更舒服。',
    varietal_note: '小粒種蜜思嘉（Moscato Bianco／法文 Muscat Blanc à Petits Grains）是極古老、香氣辨識度最高的白葡萄之一：玫瑰、橙花、麝香、杏桃般的香氣一聞就懂。它能做成甜的（如微泡甜白 Moscato d\'Asti），也能做成乾的——這支正是「乾型（dry）」版本。新手最常踩的坑就是「聞起來很甜＝以為喝起來甜」，但它的糖分已發酵殆盡、入口清爽不甜，記住這點期待就不會錯位。白酒無單寧、完全不澀，是壓力最小的入門芳香白。',
    region_note: '奧斯塔谷是義大利最小、最高、最靠阿爾卑斯的葡萄酒產區，義／法雙語。蜜思嘉在谷中日照較足、較溫暖的 Chambave 一帶有長久的種植傳統（當地以 Chambave Muscat 聞名，含風乾甜酒版本）。高山大陸性氣候、日夜溫差大，讓這支乾型蜜思嘉在奔放香氣之外保有清新的酸度與礦石尾韻。',
    vinification_note: '有機種植、葡萄手工採收。低溫發酵保留品種純淨的花果香，發酵後帶細酒渣（sur lie）培養數月以增添口感層次，但全程維持乾型、不留糖、不過橡木桶，是一支乾淨直接的靜態芳香白。酒精約 13%，與微泡甜型的 Moscato d\'Asti（約 5–6.5%）截然不同。',
    classification_note: 'DOC（法定產區）是義大利的中階品質分級，規範產地、品種與釀法。看到「Valle d\'Aosta DOC（法文 Vallée d\'Aoste）」，代表這支是道地、受法規約束的奧斯塔谷高山酒。',
    producer_note: '葛羅讓兄弟酒莊（Maison Vigneronne Frères Grosjean）位在奧斯塔谷 Quart 鎮，是典型「英雄式高山葡萄種植」（陡坡、人工）。家族 18 世紀末即務農，現代酒莊約 1968 年由 Dauphin Grosjean 正式創立；環保走得很早——1975 年起不噴殺蟲劑，並於 2011 年成為奧斯塔谷第一家通過有機認證的酒莊。你課堂喝到的 Petite Arvine 也來自這家。',
    why_beginner: '芳香型乾白是最平易近人的入門白酒之一：香氣奔放好聞、口感輕盈、白酒無單寧不澀、酸度活潑好入口。只要先建立「香得甜≠喝起來甜」的觀念，就能輕鬆享受它的清新。',
    drink_window: '現在 – 購入後約 1–3 年（趁新鮮喝最佳）',
    serve_temp: '8–10°C',
    decant: '不需要醒酒；冰鎮後直接享用即可。別冰過頭（太冰會壓抑招牌香氣），約 8–10°C 最迷人。',
    background: '同一個小粒種蜜思嘉，在義大利北部能做成微泡、低酒精、甜美的 Moscato d\'Asti，也能做成這支奧斯塔谷的乾型靜態白——是體會「同一品種、不同釀法走向」的好教材。Grosjean 另有 Chambave Muscat（來自更溫暖的次產區）與風乾甜酒版本，風格各有層次。',
    tasting_focus: '品飲練習：(1) 先用力聞——橙花、麝香、杏桃的甜美香氣，建立「芳香品種」的嗅覺記憶。(2) 入口刻意確認「它是乾的、不甜」，把香氣的甜和味覺的甜分開。(3) 留意吞下後尾段那股清新與一絲礦石鹹感，這是高海拔風土的印記。',
    notes_short: '同酒莊（Grosjean）的乾型芳香蜜思嘉，香甜卻不甜、清爽好入口的開胃白',
    notes_long: null,
    color_hex: '#E8DFA0',
    beginner_friendly: true,
    style_axis: 78,
    style_note: '芳香品種＋奧斯塔谷高山風土＋有機種植，辨識度高、偏風土；但蜜思嘉本身是全球廣布的品種、釀法乾淨直接，因此沒有更極端。',
    image: null,
  },
  {
    id: 'grosjean-torrette-rovettaz',
    region_key: 'valle-aosta',
    category: 'wine',
    type: 'red',
    type_zh: '紅酒',
    name_en: 'Torrette Supérieur "Vigne Rovettaz"',
    name_zh: '葛羅讓 托雷塔 羅維塔茲園',
    producer: 'Grosjean',
    varietal: 'Petit Rouge',
    varietal_zh: '小紅（Petit Rouge）',
    region: 'Valle d\'Aosta',
    region_zh: '奧斯塔谷',
    country: 'Italy',
    country_zh: '義大利',
    year: null,
    abv: 13.5,
    sweetness: '乾型',
    classification: 'Valle d\'Aosta DOC（Torrette）',
    price: null,
    bottles: null,
    price_tier: '$$',
    market_price_twd: '約 NT$900–1,500（國際零售推估）',
    rating: null,
    tasting_date: null,
    occasion: '想喝清單 · 越昇採購（主選）',
    highlights: [
      '奧斯塔谷原生紅葡萄 Petit Rouge，當地最具代表的日常紅',
      '輕盈果香、軟單寧，常被類比薄酒萊，可微冰',
      '與課堂酒同酒莊：有機先驅 Grosjean',
      '越昇進的是過 12 個月橡木桶的「特級 Supérieur」單一園版',
    ],
    appearance: '明亮的紅寶石色、邊緣帶紫光。',
    aroma: ['紅櫻桃', '野莓', '紫羅蘭', '一點碎石礦感', '細緻香料'],
    palate: ['輕至中等酒體', '單寧柔順', '酸度爽脆', '紅果多汁'],
    finish: '乾淨爽口的尾韻，紅果與花香主導、單寧不咬口，年輕易飲。',
    pairing: ['臘腸冷肉拼盤', '披薩', '番茄義大利麵', '三杯雞', '控肉', '滷味'],
    pairing_note: '輕盈柔順、果香主導，是百搭的家常餐桌紅；微冰後在台灣濕熱天氣也好喝。佐番茄紅醬、台式滷味、烤雞都很順，輕單寧讓它佐餐彈性很大。',
    varietal_note: '小紅（Petit Rouge）是奧斯塔谷土生土長的紅葡萄，也是當地最主要的紅品種，撐起 Torrette、Enfer d\'Arvier、Chambave 等子產區。它酒體輕、果味鮮、單寧不重，風格類似薄酒萊，是想試「奧斯塔原生紅」最好入門的第一支。Torrette 法規要求至少 70% Petit Rouge，常再混入 Vien de Nus、Fumin、Cornalin 等在地品種增添層次。',
    region_note: '奧斯塔谷是義大利最小、最高的高山產區。Torrette 是環繞首府 Aosta 一帶的紅酒子產區，海拔約 550–750 公尺、陡坡人工耕作，高海拔大溫差讓紅酒保有清新酸度與輕盈骨架——是「高山＝輕巧、明亮」紅酒風格的代表。',
    vinification_note: '越昇進口的是「特級（Supérieur）」單一園 Vigne Rovettaz 版本：相較於以不鏽鋼為主的基礎 Torrette，特級款多了約 12 個月橡木桶陳年，酒體較飽滿、結構稍多一點，但仍維持柔順果香、好入口的風格——橡木只為增厚層次，而非主導風味。有機種植。',
    classification_note: 'DOC（法定產區）是義大利的中階品質分級。「Valle d\'Aosta DOC」底下的「Torrette」是以 Petit Rouge 為主（≥70%）的紅酒子產區，等於替「奧斯塔谷在地紅葡萄釀的高山紅」做了產地背書。',
    producer_note: '葛羅讓兄弟酒莊位在奧斯塔谷 Quart 鎮，1975 年起即採友善農法、2011 年成為奧斯塔谷第一家有機認證酒莊，是當地最具代表性的家族酒莊之一。你課堂喝到的 Petite Arvine、以及採購清單裡的蜜思嘉都出自這家，可一站認識同一酒莊的不同作品。',
    why_beginner: '輕盈、果香主導、單寧柔不咬口，是想踏進「紅酒」又怕澀的新手最佳入門；還能微冰著喝，台灣天氣下特別討喜。也是認識奧斯塔谷原生品種 Petit Rouge 的好起點。',
    drink_window: '現在 – 2028',
    serve_temp: '14–16°C（微冰）',
    decant: '基礎風格幾乎不用醒酒；特級款可開瓶後透氣 15–20 分鐘。夏天可先冰鎮 20–30 分鐘再倒，更顯清爽。',
    background: 'Torrette 是奧斯塔谷最具代表的日常紅，以在地品種 Petit Rouge 為骨幹。Grosjean 的這支單一園「特級」版本，把高山輕紅做得既有果香又多一點結構，是認識「奧斯塔谷在地紅酒」很直觀的一支。',
    tasting_focus: '品飲練習：(1) 看酒色——它偏淺的紅寶石，正是高山輕紅的視覺線索，可和深濃厚重的紅酒對照。(2) 感受單寧很輕、酸度爽脆、紅果多汁，理解「高海拔＝輕巧明亮」的紅酒邏輯。(3) 試著微冰後喝，體會溫度如何放大它的果香與爽口度。',
    notes_short: '奧斯塔原生 Petit Rouge 釀的高山輕紅，果香軟單寧、可微冰，怕澀新手的入門紅',
    notes_long: null,
    color_hex: '#A8313F',
    beginner_friendly: true,
    style_axis: 80,
    style_note: '奧斯塔谷原生品種 Petit Rouge、高山陡坡與在地子產區 Torrette，風土辨識度高、明顯偏風土；特級款少量橡木桶帶來一點圓潤，因此沒有更極端。',
    image: null,
  },
  {
    id: 'st-michael-eppan-anger-pinot-grigio',
    region_key: 'trentino-alto-adige',
    category: 'wine',
    type: 'white',
    type_zh: '白酒',
    name_en: 'Anger Pinot Grigio',
    name_zh: '聖米歇爾-艾本 安格 灰皮諾',
    producer: 'St. Michael-Eppan',
    varietal: 'Pinot Grigio',
    varietal_zh: '灰皮諾',
    region: 'Alto Adige',
    region_zh: '上阿迪杰',
    country: 'Italy',
    country_zh: '義大利',
    year: null,
    abv: 14,
    sweetness: '乾型',
    classification: 'Alto Adige DOC',
    price: null,
    bottles: null,
    price_tier: '$$',
    market_price_twd: '約 NT$1,000–1,600（國際零售推估）',
    rating: null,
    tasting_date: null,
    occasion: '想喝清單 · 越昇採購（主選）',
    highlights: [
      '出自義大利得獎最多的合作社之一（傳奇釀酒師 Hans Terzer）',
      '單一園 Cru 等級「Anger」（近年改名 Fallwind），非最入門款',
      '約一半木桶發酵＋乳酸發酵，口感比超市灰皮諾更圓潤奶滑',
      '位階在入門 Classic 之上、旗艦 Sanct Valentin 之下',
    ],
    appearance: '淡金黃帶綠色反光、清澈。',
    aroma: ['熟梨', '黃蘋果', '柑橘', '哈密瓜', '白色花香'],
    palate: ['中至飽滿酒體', '酸度柔順', '奶油般圓潤質地', '礦物與淡淡杏仁'],
    finish: '清爽帶礦物感與淡淡鹹鮮的收尾，質地圓潤、餘味宜人。',
    pairing: ['清蒸魚', '白灼蝦', '白斬雞', '生魚片', '涼拌沙拉', '清炒海瓜子'],
    pairing_note: '乾淨果香加奶油質地，百搭海鮮與白肉；圓潤口感也能襯起司、開胃前菜。冰鎮後清爽好入口，是台灣餐桌很安全的萬用白。',
    varietal_note: '灰皮諾（Pinot Grigio／Pinot Gris）是源自勃艮第 Pinot 家族的國際白品種，在義大利北部極普遍。多數平價版清淡簡單，但這支單一園版本因為部分木桶發酵與乳酸發酵，口感更有層次、奶油感與礦物尾韻，是「比超市灰皮諾有料一階」的版本。白酒幾乎無單寧、零澀感，對新手非常友善。',
    region_note: '上阿迪杰位於義大利最北、阿爾卑斯山環抱的德語區，是公認義大利最強的白酒產區之一。高海拔加上大日夜溫差，讓白葡萄保有漂亮的清新酸度與礦物感。「Anger」是 St. Michael 村中心附近、海拔約 400–430 公尺的單一葡萄園。',
    vinification_note: '約 50% 不鏽鋼槽、50% 木桶發酵，並進行乳酸發酵（malolactic，柔化酸度），合併調配後上市。這正是它口感比一般灰皮諾更圓潤、帶奶油質地與礦物鹹味層次的原因。乾型，酒精依年份約 14–14.5%。',
    classification_note: 'DOC（法定產區）是義大利的中階品質分級。這支屬酒莊的「單一園 Cru 系列」（近年由「Cru」改名「Fallwind 落山風」），位階在入門的 Classic 之上、頂級的 Sanct Valentin 珍藏之下——是強調特定園區風土的中高階款。',
    producer_note: '聖米歇爾-艾本（San Michele Appiano）是上阿迪杰最受敬重的合作社之一，1907 年創立、約 350 位酒農、近 385 公頃。它是第一家拿到 Gambero Rosso「三星 Tre Stelle」的上阿迪杰酒莊，並曾獲選年度合作社酒莊；傳奇釀酒師 Hans Terzer（人稱「白酒魔術師」）讓它以世界級白酒揚名。旗艦系列為 Sanct Valentin，頂級限量款為 Appius。台灣由越昇國際代理。',
    why_beginner: '乾型、果香明亮易懂、酸度柔順、幾乎無澀感，冰鎮即飲不需醒酒，單喝配餐都好入口；又出自白酒名門，是新手認識義大利高山白酒與優質灰皮諾很安全又體面的選擇。',
    drink_window: '現在 – 2027（年輕新鮮喝最佳）',
    serve_temp: '8–12°C',
    decant: '不需要醒酒；開瓶即飲。冰透可讓酒體更俐落；想多嘗質地層次可稍微回溫一兩度。',
    background: '這支來自義大利得獎最多的合作社之一 St. Michael-Eppan。「Anger」是它的單一園 Cru 等級灰皮諾，定位高於最暢銷的 Classic 入門款、低於旗艦 Sanct Valentin；以約一半木桶發酵與乳酸發酵打造圓潤質地，是展現酒莊白酒細膩功力、又好入手的一支。',
    tasting_focus: '品飲練習：(1) 比較它和印象中清淡的超市灰皮諾——留意這支多出來的「奶油圓潤質地」與礦物尾韻，那來自木桶與乳酸發酵。(2) 感受柔順酸度與尾段淡淡鹹鮮。(3) 冰鎮後配一道清蒸魚或白灼蝦，體會清爽白酒如何替海鮮提鮮、解膩。',
    notes_short: '白酒名門 St. Michael-Eppan 的單一園 Cru 灰皮諾，奶油圓潤、礦物尾韻，比超市款有料',
    notes_long: null,
    color_hex: '#E6DBA2',
    beginner_friendly: true,
    style_axis: 56,
    style_note: '灰皮諾是國際品種、本身偏標準化，但這支是單一園 Cru、高海拔風土加上木桶與乳酸發酵的工藝，把辨識度拉高，因此落在中間略偏國際一側。',
    image: null,
  },
  {
    id: 'franz-haas-lagrein',
    region_key: 'trentino-alto-adige',
    category: 'wine',
    type: 'red',
    type_zh: '紅酒',
    name_en: 'Lagrein Alto Adige',
    name_zh: '法蘭茲·哈斯 拉格萊因',
    producer: 'Franz Haas',
    varietal: 'Lagrein',
    varietal_zh: '拉格萊因',
    region: 'Alto Adige',
    region_zh: '上阿迪杰',
    country: 'Italy',
    country_zh: '義大利',
    year: null,
    abv: 13,
    sweetness: '乾型',
    classification: 'Alto Adige DOC',
    price: null,
    bottles: null,
    price_tier: '$$',
    market_price_twd: '約 NT$900–1,300（國際零售推估）',
    rating: null,
    tasting_date: null,
    occasion: '想喝清單 · 越昇採購（主選）',
    highlights: [
      '上阿迪杰招牌原生紅 Lagrein（發源 Bolzano）',
      '出自 1880 年創立、傳承八代的南提洛頂級名莊 Franz Haas',
      '深近墨黑、可可紫羅蘭，尾段招牌「微苦」',
      '與課堂第 3 杯（Elena Walch Lagrein）同品種不同莊——最佳產地對照組',
    ],
    appearance: '濃郁石榴紅至近墨紫、邊緣帶紫，倒入杯中幾乎不透光。',
    aroma: ['黑莓', '黑櫻桃', '李子', '紫羅蘭', '可可', '香料'],
    palate: ['中至飽滿酒體', '單寧紮實但圓潤', '酸度鮮明', '深色果多汁'],
    finish: '悠長多汁，收在 Lagrein 標誌性的微苦——苦杏仁／黑巧克力的清爽收口，讓濃郁果味不顯甜膩。',
    pairing: ['紅燒牛肉', '滷牛腱', '黑胡椒牛排', '烤豬肋排', '香腸', '陳年硬質起司'],
    pairing_note: '紮實單寧＋鮮明酸度＋微苦尾韻使它非常百搭重口味：紅燒、滷味、燒烤都接得住，微苦尾韻還能呼應醬油與燒烤焦香；以油脂平衡單寧會更顯多汁。',
    varietal_note: '拉格萊因（Lagrein）是發源於上阿迪杰首府 Bolzano（波札諾）周邊溫暖谷地的原生紅葡萄，DNA 上是 Teroldego 的後代、黑皮諾的「孫輩」。它色深近墨紫、單寧紮實、酸度鮮明，最招牌的是尾韻那一抹「苦杏仁／黑巧克力」的微苦收口——這是辨識 Lagrein 的指紋，是品種特徵而非缺點。',
    region_note: '上阿迪杰是義大利最北、阿爾卑斯環抱的產區。Lagrein 是晚熟、需要熱量的品種，種在產區最溫暖的低海拔河谷（約 200–300 公尺、Bolzano 盆地周邊）；白天蓄熱讓它熟透、夜間山區冷空氣保住酸度與香氣。Franz Haas 的葡萄來自約 220–250 公尺、向陽富礫石的暖土園區。',
    vinification_note: '不鏽鋼控溫發酵萃取色素與單寧後，於大型木桶（tonneau，非小新桶）進行乳酸發酵並熟成約 10–12 個月，再瓶中靜置數月。這種「大桶輕修飾」的手法柔化單寧、保留乾淨深色果味，刻意不給明顯新桶味。殘糖極低、近乎全乾。',
    classification_note: 'DOC（法定產區）是義大利的中階品質分級。「Alto Adige DOC」涵蓋這個阿爾卑斯產區的多種品種；標單一品種（Lagrein）者，代表以該品種為主、產自法規劃定的上阿迪杰範圍。',
    producer_note: '法蘭茲·哈斯（Franz Haas）是上阿迪杰頂級品質派名莊，1880 年創立於 Montagna／Egna 一帶、已傳承八代。它以全義頂尖的黑皮諾（旗艦 Schweizer）與罕見的玫瑰麝香（Moscato Rosa）聞名，色彩鮮明的藝術酒標出自畫家／建築師 Riccardo Schweizer 之手。台灣由越昇國際代理。',
    why_beginner: '單寧雖明顯，但被釀得圓潤不刮口，加上果味奔放、酸度爽脆，是「有份量但不兇」的好上手紅酒；配滷味、紅燒、烤肉這類台味重口料理很對味，也不必久放——買來現在就能享用。',
    drink_window: '現在 – 2029',
    serve_temp: '16–18°C',
    decant: '年輕年份可開瓶前醒酒約 20–30 分鐘，讓單寧鬆開、香氣更開；略低於室溫（16–18°C）上桌更顯清爽。用波爾多型大肚杯聚攏深色果香。',
    background: '這支是上阿迪杰原生紅 Lagrein 出自頂級名莊 Franz Haas 之手的版本，走「大桶輕修飾、保留品種純淨深色果味與微苦個性」的路線，供應與價格相對親民，是認識 Lagrein 很理想的一支。Franz Haas 真正最出名的其實是黑皮諾，因此買它也等於認識了一家南提洛名莊。',
    tasting_focus: '品飲練習：(1) 記兩個招牌記號——眼睛看「色深近墨」、尾韻嚐「苦杏仁／黑巧克力的微苦收口」，以後盲飲就抓得到 Lagrein。(2) 務必和課堂第 3 杯的 Elena Walch Lagrein 並排喝：同樣品種、不同酒莊，體會「兩家風格差在哪」，是很好的進階練習。',
    notes_short: '南提洛八代名莊 Franz Haas 的招牌原生紅 Lagrein，色深、微苦尾韻，與課堂 Lagrein 的酒莊對照組',
    notes_long: null,
    color_hex: '#3D1322',
    beginner_friendly: true,
    style_axis: 70,
    style_note: '稀有原生品種 Lagrein、上阿迪杰特定風土，本就偏風土；Franz Haas 為現代化名莊、此款走大桶輕修飾的核心路線，乾淨易親近，因此偏風土但不極端。',
    image: null,
  },
  {
    id: 'grosjean-chambave-muscat',
    region_key: 'valle-aosta',
    category: 'wine',
    type: 'white',
    type_zh: '白酒',
    name_en: 'Chambave Muscat',
    name_zh: '葛羅讓 香貝爾 蜜思嘉',
    producer: 'Grosjean',
    varietal: 'Muscat Blanc à Petits Grains',
    varietal_zh: '小粒種蜜思嘉',
    region: 'Valle d\'Aosta',
    region_zh: '奧斯塔谷',
    country: 'Italy',
    country_zh: '義大利',
    year: null,
    abv: 13.5,
    sweetness: '乾型',
    classification: 'Valle d\'Aosta DOC（Chambave）',
    price: null,
    bottles: null,
    price_tier: '$$',
    market_price_twd: '約 NT$1,200–1,500（國際零售推估）',
    rating: null,
    tasting_date: null,
    occasion: '想喝清單 · 越昇採購（① 缺貨備選）',
    highlights: [
      '① Grosjean Muscat Petit Grain 的缺貨備選',
      '同酒莊、同產區、同葡萄——幾乎是雙胞胎',
      '來自日照較足的 Chambave 次產區，香氣更飽滿',
      '同為乾型、有機種植，香甜卻不甜',
    ],
    appearance: '明亮稻草黃、清澈帶光澤。',
    aroma: ['玫瑰', '麝香', '白桃', '柑橘', '薄荷鼠尾草'],
    palate: ['輕盈', '酸度清新', '花果飽滿', '礦石鹹尾'],
    finish: '乾爽清新、帶杏仁微苦與礦石鹹感的收口。',
    pairing: ['餐前酒', '蘆筍蔬菜塔派', '清蒸海鮮', '白肉雞', '泰式涼拌', '壽司前菜'],
    pairing_note: '越昇官方建議當餐前酒或配蔬菜塔派、蘆筍料理；花香能柔化辛香、清新酸度能解膩，也很搭台灣的清蒸海鮮與東南亞菜。',
    varietal_note: '與正選 ① 完全相同的小粒種蜜思嘉（Moscato Bianco），香氣以玫瑰、麝香、白桃為招牌，入口乾爽不甜。差別只在這款葡萄來自奧斯塔谷裡日照較足、較溫暖的 Chambave 次產區（當地著名的蜜思嘉傳統區），香氣會更飽滿外放一點點。',
    region_note: 'Chambave 位在奧斯塔谷中段、首府 Aosta 東側，是谷中較溫暖、日照較足的蜜思嘉傳統產區，以乾型與風乾甜型（Muscat Flétri）蜜思嘉聞名。高海拔大溫差仍賦予它清新酸度與礦石尾韻。',
    vinification_note: '有機種植、低溫發酵保留花果香，帶酒渣（sur lie）培養增添口感層次，維持乾型、不過桶。酒精約 13.5%（這是乾型靜態白；別與 Chambave 的風乾甜酒 Muscat Flétri 混淆）。',
    classification_note: 'DOC（法定產區）是義大利中階品質分級。「Valle d\'Aosta DOC」底下的「Chambave」是以蜜思嘉聞名的子產區名，等於替「Chambave 一帶的蜜思嘉」做產地背書。',
    producer_note: '與正選同為葛羅讓兄弟酒莊（Grosjean）——奧斯塔谷 Quart 鎮的有機先驅（2011 年該谷第一家有機認證）。越昇官網設有此酒獨立商品頁，缺貨時可與其他 Grosjean 酒款一站補上。',
    why_beginner: '芳香奔放、輕盈無單寧、酸度清新，新手一聞就喜歡；同樣記住「香得甜≠喝起來甜」即可。是 ① 缺貨時最無痛接棒的同風格款。',
    drink_window: '現在 – 購入後約 1–3 年（趁新鮮喝最佳）',
    serve_temp: '10–12°C',
    decant: '不需要醒酒；越昇官方建議侍酒約 10–12°C，開瓶即飲。',
    background: '作為 ① Muscat Petit Grain 的備選：同酒莊、同產區、同品種，香氣個性一脈相承，只是來自更溫暖的 Chambave 次產區、香氣更飽滿。是缺貨時最貼合「清爽高山芳香乾白」角色的替補。',
    tasting_focus: '品飲練習：和正選 ① 一樣——先聞奔放花果香、入口確認乾爽不甜、尾段抓礦石鹹感；若兩支都到手，可並排比較 Chambave（較溫暖、香氣更飽）與正選的細微差異。',
    notes_short: '① Muscat 的缺貨備選：同莊同產區同葡萄，來自更溫暖 Chambave、香氣更飽的乾型蜜思嘉',
    notes_long: null,
    color_hex: '#E9E0A4',
    beginner_friendly: true,
    style_axis: 80,
    style_note: '芳香品種＋Chambave 子產區傳統＋有機，風土辨識度高、偏風土；蜜思嘉本身廣布、釀法乾淨，因此沒有更極端。',
    image: null,
  },
  {
    id: 'grosjean-cornalin-rovettaz',
    region_key: 'valle-aosta',
    category: 'wine',
    type: 'red',
    type_zh: '紅酒',
    name_en: 'Cornalin "Vigne Rovettaz"',
    name_zh: '葛羅讓 柯納林 羅維塔茲園',
    producer: 'Grosjean',
    varietal: 'Cornalin',
    varietal_zh: '柯納林',
    region: 'Valle d\'Aosta',
    region_zh: '奧斯塔谷',
    country: 'Italy',
    country_zh: '義大利',
    year: null,
    abv: 13,
    sweetness: '乾型',
    classification: 'Valle d\'Aosta DOC',
    price: null,
    bottles: null,
    price_tier: '$$',
    market_price_twd: '約 NT$1,200–1,600（國際零售推估）',
    rating: null,
    tasting_date: null,
    occasion: '想喝清單 · 越昇採購（② 缺貨備選）',
    highlights: [
      '② Grosjean Torrette 的缺貨備選',
      '另一支奧斯塔谷原生紅葡萄 Cornalin',
      '輕至中酒體、單寧柔順、紅果花香、不過桶',
      '同酒莊、同產區，可一站補上',
    ],
    appearance: '紅寶石色、清透帶光澤。',
    aroma: ['紅櫻桃', '覆盆子', '紫羅蘭', '黑白胡椒', '細緻香料', '一絲菸草'],
    palate: ['輕至中等酒體', '單寧柔順', '酸度偏柔', '紅果滑順'],
    finish: '乾淨悠長的尾韻，紅果與細緻辛香、花香收尾，滑順易飲。',
    pairing: ['烤雞', '煎豬排', '菇蕈燉飯', '番茄義大利麵', '滷味', 'Fontina 風格半硬起司'],
    pairing_note: '輕柔單寧讓佐餐彈性很大：家常烤雞、煎豬排、菇類料理、番茄紅醬都很搭，配奧斯塔谷傳統的 Fontina 起司更是同鄉絕配。',
    varietal_note: '柯納林（Cornalin，學名 Cornalin d\'Aoste，屬 Oriou 家族）是奧斯塔谷稀有的原生紅葡萄，紅寶石色、產量少。它輕至中等酒體、單寧柔順、酸度偏柔，帶紅櫻桃、覆盆子與細緻胡椒、紫羅蘭花香，是高山原生品種中相當親切好入口的一款（與 Torrette 一樣走輕柔路線，刻意避開酒莊較有結構的 Fumin）。',
    region_note: '葡萄來自 Grosjean 位於 Quart 鎮、海拔約 600–700 公尺的單一園 Vigne Rovettaz（羅維塔茲園），陡坡、砂質夾石礫、排水佳。奧斯塔谷高海拔大溫差賦予它清新酸度與輕盈骨架。',
    vinification_note: '手工採收，不鏽鋼槽發酵，不過橡木桶（或極輕修飾），保留品種純淨的紅果與花香，是一支果香清新、年輕即飲的高山原生紅。有機種植。',
    classification_note: 'DOC（法定產區）是義大利中階品質分級，規範產地、品種與釀法。「Valle d\'Aosta DOC」代表這支是道地、受法規約束的奧斯塔谷高山酒。',
    producer_note: '與 ② 正選同為葛羅讓兄弟酒莊（Grosjean），奧斯塔谷 Quart 鎮有機先驅。越昇官網 Grosjean 酒莊頁列有此「羅維塔茲園」柯納林紅葡萄酒，缺貨時可與其他 Grosjean 酒款一站補上。',
    why_beginner: '單寧柔、酸度親切、果香主導，幾乎無澀感，是想認識「奧斯塔原生紅」又怕澀的新手很友善的一支；可微冰著喝，台灣天氣下更討喜。',
    drink_window: '現在 – 2028',
    serve_temp: '16–18°C（可稍涼至 15–16°C）',
    decant: '年輕即飲、不需久醒，開瓶後略醒 15–20 分鐘即可；稍涼上桌更能凸顯紅果與花香。',
    background: '作為 ② Torrette 的備選：同酒莊、同產區、同樣是奧斯塔谷原生紅，輕柔好入口的程度與 Torrette 一致。Cornalin 產量稀少、台灣罕見，是缺貨時兼顧「原生品種＋新手友善」的理想替補。',
    tasting_focus: '品飲練習：(1) 看它偏淺的紅寶石色，對照深濃紅酒，理解高山輕紅的風格。(2) 感受柔順單寧與紅果花香、細緻胡椒。(3) 若與 Torrette 都到手，可並排比較兩個奧斯塔原生紅（Petit Rouge vs Cornalin）的細微差異。',
    notes_short: '② Torrette 的缺貨備選：同莊另一支奧斯塔原生紅 Cornalin，柔順紅果、不過桶、好入口',
    notes_long: null,
    color_hex: '#A6384A',
    beginner_friendly: true,
    style_axis: 82,
    style_note: '稀有原生品種 Cornalin、單一園、不過桶的純淨果香與高山風土，明顯偏風土；產量稀少、在地限定，辨識度高。',
    image: null,
  },
  {
    id: 'st-michael-eppan-classic-pinot-grigio',
    region_key: 'trentino-alto-adige',
    category: 'wine',
    type: 'white',
    type_zh: '白酒',
    name_en: 'Pinot Grigio (Classic)',
    name_zh: '聖米歇爾-艾本 經典 灰皮諾',
    producer: 'St. Michael-Eppan',
    varietal: 'Pinot Grigio',
    varietal_zh: '灰皮諾',
    region: 'Alto Adige',
    region_zh: '上阿迪杰',
    country: 'Italy',
    country_zh: '義大利',
    year: null,
    abv: 13,
    sweetness: '乾型',
    classification: 'Alto Adige DOC',
    price: null,
    bottles: null,
    price_tier: '$$',
    market_price_twd: '約 NT$750–900（國際零售推估）',
    rating: null,
    tasting_date: null,
    occasion: '想喝清單 · 越昇採購（③ 缺貨備選）',
    highlights: [
      '③ Anger 灰皮諾的缺貨備選——同酒莊、更便宜一階',
      '酒莊最暢銷的「Classic」入門灰皮諾',
      '不鏽鋼槽釀造、乾淨清爽、果香直接',
      '日常好入口、CP 值高',
    ],
    appearance: '稻草黃帶綠光、清澈。',
    aroma: ['熟梨', '青蘋果', '柑橘', '白花'],
    palate: ['輕盈', '清新酸度', '柔順', '乾淨果香'],
    finish: '清爽乾淨的收尾、餘味宜人，輕盈日常。',
    pairing: ['清蒸白肉魚', '生蠔', '蝦', '魚湯', '雞胸', '沙拉輕食'],
    pairing_note: '百搭餐前與海鮮：清蒸或香煎白肉魚、蝦、魚湯都合拍，乾淨清爽不搶味，是日常餐桌的安全萬用白。',
    varietal_note: '與 ③ 正選同為灰皮諾（Pinot Grigio），但這支是酒莊最暢銷的「Classic」廣域入門款：以不鏽鋼槽發酵、不過木桶，走乾淨清爽、果香直接路線，比正選 Anger（單一園、部分木桶、較飽滿）更輕盈日常，價格門檻也更低。白酒無單寧、零澀感，最適合新手每天喝、建立對品種的基本印象。',
    region_note: '上阿迪杰是義大利最強白酒產區之一，高海拔大溫差賦予白酒清新酸度與礦物感。Classic 系列葡萄來自酒莊較廣域的優質地塊，忠實表現品種與在地風土。',
    vinification_note: '不鏽鋼槽發酵、無木桶，乾淨清爽、保留純淨果香，酒精約 13%。這也是它比正選 Anger 更輕盈、更入門的原因。',
    classification_note: 'DOC（法定產區）是義大利中階品質分級。這支屬酒莊最入門的「Classic」系列，定位低於單一園的 Anger（Cru）與旗艦 Sanct Valentin，是認識酒莊與品種的親民起點。',
    producer_note: '與 ③ 正選同為聖米歇爾-艾本（St. Michael-Eppan）——上阿迪杰最受敬重的合作社之一、白酒名門。越昇官網同時列有單一園 Anger 與這支入門 Classic 灰皮諾，缺貨時可同酒莊、更省一階地補上。',
    why_beginner: '乾型、果香明亮、酸度柔順、零澀感、冰鎮即飲，價格親民，是新手認識義大利高山灰皮諾最沒壓力、最划算的入門基準款。',
    drink_window: '現在 – 2027（年輕新鮮喝最佳）',
    serve_temp: '8–10°C',
    decant: '不需要醒酒；冰鎮 8–10°C 開瓶即飲，當天喝完風味最佳。',
    background: '作為 ③ Anger 的備選：同酒莊、同品種、同產區乾型白，但定位更日常、更便宜。Anger 是較有結構的單一園精選，這支 Classic 則是酒莊最暢銷的廣域入門款——缺貨或想省一點時最穩的同風格替補。',
    tasting_focus: '品飲練習：(1) 感受它乾淨清爽的果香（熟梨、青蘋果）與柔順酸度。(2) 若與 Anger 都到手，可並排比較「Classic（不鏽鋼、輕盈）」與「Anger（部分木桶、圓潤奶滑）」的差異，體會工藝如何改變同一品種的口感。',
    notes_short: '③ Anger 的缺貨備選：同酒莊更入門的 Classic 灰皮諾，不鏽鋼乾淨果香、CP 值高',
    notes_long: null,
    color_hex: '#E9E2AC',
    beginner_friendly: true,
    style_axis: 44,
    style_note: '灰皮諾國際品種＋入門 Classic、不鏽鋼乾淨路線，偏標準化好入口；但高海拔產區仍給了一點清新辨識度，因此落在偏國際一側。',
    image: null,
  },
  {
    id: 'franz-haas-pinot-nero',
    region_key: 'trentino-alto-adige',
    category: 'wine',
    type: 'red',
    type_zh: '紅酒',
    name_en: 'Pinot Nero "Classic Line"',
    name_zh: '法蘭茲·哈斯 黑皮諾 經典',
    producer: 'Franz Haas',
    varietal: 'Pinot Nero',
    varietal_zh: '黑皮諾',
    region: 'Alto Adige',
    region_zh: '上阿迪杰',
    country: 'Italy',
    country_zh: '義大利',
    year: null,
    abv: 13.5,
    sweetness: '乾型',
    classification: 'Alto Adige DOC',
    price: null,
    bottles: null,
    price_tier: '$$',
    market_price_twd: '約 NT$1,600–2,200（國際零售推估）',
    rating: null,
    tasting_date: null,
    occasion: '想喝清單 · 越昇採購（④ 缺貨備選）',
    highlights: [
      '④ Franz Haas Lagrein 的缺貨備選（同酒莊）',
      '誠實提醒：這是黑皮諾、非原生 Lagrein',
      'Franz Haas 真正最出名的招牌品種',
      '單寧細滑、優雅好入口，酒莊暱稱「紅酒中的白酒」',
    ],
    appearance: '紅寶石色、色淺通透。',
    aroma: ['紅櫻桃', '覆盆子', '野莓', '紫羅蘭', '丁香肉桂', '森林氣息'],
    palate: ['輕至中等酒體', '單寧細柔滑順', '酸度清新活潑', '紅果鮮明'],
    finish: '優雅清新的收尾，紅果與淡淡香料尾韻，細緻不厚重。',
    pairing: ['烤雞', '油封鴨', '炒野菇／菇燉飯', '煎鮭魚', '醬油烤雞', '叉燒'],
    pairing_note: '單寧細、酸度清爽，能襯白肉與菇類的鮮味又不搶味，連油脂豐厚的鮭魚都接得住；台味的滷味、叉燒、醬油烤雞也很搭，單寧低不會跟醬汁打架。',
    varietal_note: '黑皮諾（Pinot Nero／法文 Pinot Noir）是源自勃艮第的國際紅品種，以單寧細柔、酸度清爽、果香鮮明著稱，是公認最好入口的紅酒之一。上阿迪杰是公認義大利最會做黑皮諾的產區；而 Franz Haas 更被視為義大利黑皮諾的標竿（旗艦 Schweezer 黑皮諾 1990 年問世）——所以這支備選等於「保留同一名莊、換成它真正的招牌葡萄」。',
    region_note: '上阿迪杰位於義大利最北的阿爾卑斯山區，高海拔（黑皮諾園多在涼爽的中高海拔坡地）與大日夜溫差賦予紅酒清爽酸度與優雅果香，是黑皮諾「好入口、不厚重」的典型風土。',
    vinification_note: '這是標準的「Classic Line」款（刻意有別於昂貴的 Schweizer 精選與 Pònkler 單一園）：輕至中酒體、紅寶石色、單寧細緻圓潤，果香前衛優雅，酒精約 13.5%。',
    classification_note: 'DOC（法定產區）是義大利中階品質分級。「Alto Adige DOC」涵蓋本區多種品種；這支為酒莊的標準款黑皮諾，非高階精選或單一園 Riserva。',
    producer_note: '與 ④ 正選同為法蘭茲·哈斯（Franz Haas）——1880 年創立、傳承八代的南提洛頂級名莊。它最出名的其實正是黑皮諾。越昇官網 Franz Haas 酒莊頁明列「Pinot Nero Classic Line」標準款（與高階 Schweizer、Pònkler 區隔），缺貨時可同酒莊補上。',
    why_beginner: '黑皮諾單寧細柔、酸度清爽、紅果香鮮明、開瓶即飲，是從白酒跨進紅酒壓力最小的橋樑，對新手其實比 Lagrein 更不易踩雷；代價是它是國際品種，少了 Lagrein 的在地獨特性。',
    drink_window: '現在 – 2029',
    serve_temp: '14–16°C',
    decant: '年輕飲用即佳；想讓香氣更開展可醒 15–30 分鐘。略低於一般紅酒（14–16°C）凸顯果香與清新酸度；薄胎布根地杯型有助聚香。',
    background: '作為 ④ Franz Haas Lagrein 的備選——誠實說明：經查證，越昇在上阿迪杰唯一的「原生紅」就是 Franz Haas Lagrein 本款，沒有其他原生 Lagrein 可替。因此最務實的同莊備選是 Franz Haas 招牌的黑皮諾標準款（避開昂貴的 Schweizer Riserva）：它用黑皮諾的優雅補上「上阿迪杰結構紅、新手友善」的角色，只是品種從原生 Lagrein 換成國際黑皮諾。',
    tasting_focus: '品飲練習：(1) 感受黑皮諾標誌性的「色淺、單寧細滑、紅果香」，理解為什麼它被稱為最好入口的紅酒。(2) 若與正選 Lagrein 對照，可體會「同產區、同酒莊，原生 Lagrein（深濃微苦）vs 國際黑皮諾（輕巧優雅）」的兩種紅酒性格。',
    notes_short: '④ Lagrein 的缺貨備選：同莊 Franz Haas 招牌黑皮諾，單寧細滑優雅；誠實說是國際品種、非原生',
    notes_long: null,
    color_hex: '#9E2B3C',
    beginner_friendly: true,
    style_axis: 56,
    style_note: '黑皮諾是國際品種、偏標準化，但上阿迪杰高山冷涼風土辨識度高、Franz Haas 又是黑皮諾名家——兩股力量拉鋸，落在中間略偏國際。',
    image: null,
  },
  {
    id: 'tommasi-amarone-classico',
    region_key: 'veneto',
    category: 'wine',
    type: 'red',
    type_zh: '紅酒',
    name_en: 'Amarone della Valpolicella Classico',
    name_zh: '托馬西 阿瑪羅內 經典',
    producer: 'Tommasi',
    varietal: 'Corvina · Corvinone · Rondinella',
    varietal_zh: '科維納等維羅納原生品種',
    region: 'Valpolicella Classico, Veneto',
    region_zh: '瓦波利切拉',
    country: 'Italy',
    country_zh: '義大利',
    year: 2021,
    abv: 15,
    sweetness: '乾型',
    classification: 'Amarone della Valpolicella Classico DOCG',
    price: null,
    bottles: 1,
    price_tier: '$$$',
    market_price_twd: '約 NT$2,100–2,800',
    rating: null,
    tasting_date: null,
    occasion: '越昇環義品飲課程 · 活動購入（4 支 NT$5,500 套組）',
    highlights: [
      '整套酒單的「大魔王」：義大利四大紅酒之王之一',
      '枯藤法（appassimento）：葡萄風乾 3–4 個月再釀，極度濃縮',
      'Tommasi 1902 年創立，Amarone「歷史家族」創始成員',
      '約 15% 酒精、絲絨般飽滿，特殊場合首選',
    ],
    appearance: '深石榴紅近乎不透光、邊緣帶磚紅。',
    aroma: ['黑櫻桃', '李子乾', '無花果', '黑巧克力', '咖啡', '甜香料'],
    palate: ['飽滿厚實', '絲絨般滑順', '果味集中', '單寧細緻', '酸度仍明亮', '微甜暖意'],
    finish: '悠長溫暖的尾韻，收在黑巧克力與微苦甜香料，餘味綿延。',
    pairing: ['熟成帕瑪森乾酪', '紅燒牛肉', '燉牛膝', '炭烤牛排', '滷味', '黑巧克力'],
    pairing_note: '酒體龐大、單寧細、帶甜潤暖意，最適合濃郁厚重的料理：紅燒、燉肉、炭烤紅肉都壓得住；切一塊高品質熟成起司（帕瑪森）讓乳脂與深邃紅酒交融，是 Amarone 的經典享受。',
    varietal_note: 'Corvina、Corvinone、Rondinella 是維羅納（Verona）一帶的原生紅葡萄，也是 Valpolicella、Amarone、Ripasso 共同的班底：Corvina 提供紅櫻桃果味與酸度骨架、Corvinone 增添色澤與結構、Rondinella 耐風乾。這些品種本身不算厚重——是「枯藤法」風乾濃縮後，才成就 Amarone 龐大的酒體。',
    region_note: 'Valpolicella 位在威尼托維羅納東北的丘陵，「Classico」指的是最核心的歷史精華區（Fumane、Marano、Negrar、Sant\'Ambrogio、San Pietro in Cariano 一帶）。冷涼山風與石灰岩坡地讓葡萄保有酸度與香氣，也適合採收後長時間風乾。',
    vinification_note: 'Amarone 的靈魂是「枯藤法（appassimento）」：精選的葡萄串採收後鋪在通風的陰乾室風乾約 3–4 個月，水分蒸散、糖與風味極度濃縮，再榨汁緩慢發酵到底——糖幾乎發酵殆盡，所以它是「乾型」卻有約 15% 酒精與甜潤暖意。Tommasi 此款再於斯拉夫尼亞（Slavonian）大橡木桶陳年約 3 年，柔化單寧、增添香料與可可氣息。',
    classification_note: 'Amarone della Valpolicella 自 2010 年起升格 DOCG（義大利最高分級），常與 Barolo、Barbaresco、Brunello 並列「義大利四大紅酒之王」。你這支是標準款「Classico」（核心產區），而非更高階的單一園 Riserva「Ca\' Florian」——標準款已是市場公認的標竿入門級 Amarone，品質優異、價位較親民。',
    producer_note: '托馬西（Tommasi）1902 年由 Giacomo Tommasi 在 Valpolicella 經典產區的 Pedemonte 創立，至今由家族第四代經營，是當地百年名門，也是「Amarone 歷史家族（Le Famiglie Storiche）」的創始成員之一。在 Valpolicella 核心擁有約 195 公頃葡萄園，並把版圖擴及托斯卡尼等義大利各地，是「具規模卻維持品質」的代表名莊。台灣由越昇國際代理。',
    drink_window: '現在 – 2035（2021 還年輕，2028 年後表現更佳）',
    serve_temp: '16–18°C',
    decant: '2021 年份還年輕強壯，強烈建議開瓶後倒入醒酒器 1–2 小時（甚至 2–3 小時）再喝，單寧與香氣會明顯更開、更圓潤；用波爾多型大肚杯。',
    background: '枯藤法是維羅納流傳數百年的工藝。「Amarone」之名源自 amaro（苦），指它在甜型 Recioto 的傳統上「發酵到底、轉為乾型」、尾段帶微苦的風格。它產量低、耗損大、陳年久，天生價位偏高，是義大利最具代表性的偉大紅酒之一。Tommasi 這支標準 Classico，是認識 Amarone 風格、或用於送禮／特殊場合很理想的一支。',
    tasting_focus: '品飲練習：(1) 感受它「乾型卻有甜潤暖意」的特殊矛盾感——這是枯藤法濃縮的結果、不是加糖。(2) 醒酒前後各喝一口，體會時間如何讓年輕單寧變柔。(3) 切一塊帕瑪森乾酪同吃，感受濃郁乳脂與深邃紅酒交融的層次。新手宜小口慢飲、搭餐喝，別空腹猛灌（約 15% 酒精）。',
    notes_short: '整套的「大魔王」：義大利四大紅酒之王之一，枯藤法釀的濃縮絲絨紅，特殊場合首選',
    notes_long: null,
    color_hex: '#4A0E1A',
    beginner_friendly: false,
    style_axis: 80,
    style_note: '維羅納原生品種、枯藤法的傳統工藝與 Valpolicella Classico 風土，辨識度極高、明顯偏風土；Tommasi 走具規模的現代釀造，因此沒到最極端。',
    image: null,
  },
  {
    id: 'roeno-rivoli-pinot-grigio',
    region_key: 'veneto',
    category: 'wine',
    type: 'white',
    type_zh: '白酒',
    name_en: 'Rivoli Pinot Grigio',
    name_zh: '羅埃諾 里沃利 灰皮諾',
    producer: 'Roeno',
    varietal: 'Pinot Grigio',
    varietal_zh: '灰皮諾',
    region: 'Valdadige Terradeiforti, Veneto',
    region_zh: '瓦達迪傑',
    country: 'Italy',
    country_zh: '義大利',
    year: 2023,
    abv: 13.5,
    sweetness: '乾型',
    classification: 'Valdadige Terradeiforti DOC',
    price: null,
    bottles: 1,
    price_tier: '$$',
    market_price_twd: '約 NT$950–1,350',
    rating: null,
    tasting_date: null,
    occasion: '越昇環義品飲課程 · 活動購入（4 支 NT$5,500 套組）',
    highlights: [
      '拿下 Gambero Rosso 2026 三杯（最高榮譽）的單一園灰皮諾',
      'Fugatti 家族小農、Terra dei Forti 最受矚目的酒莊之一',
      '單一園 cru「Rìvoli」：比超市灰皮諾更圓潤多層次',
      '阿迪傑河谷高山冷冽，純淨優雅',
    ],
    appearance: '明亮稻草黃、清澈帶光澤。',
    aroma: ['檸檬皮', '洋梨', '白桃', '白花', '礦石', '烤杏仁'],
    palate: ['中等偏圓潤', '酸度乾淨明亮', '質地飽滿', '餘韻綿長'],
    finish: '乾淨悠長的尾韻，帶一絲高雅的烤杏仁微苦。',
    pairing: ['烤鱸魚', '雞肉沙拉', '鮪魚塔塔', '蔬菜燉飯', '鹹派', '白肉料理'],
    pairing_note: '酒體比一般灰皮諾圓潤、酸度乾淨，百搭白肉與海鮮：烤魚、雞肉沙拉、奶香燉飯都合拍；單純下班倒一杯純飲放鬆也很舒服。冰鎮至約 10°C 飲用最佳。',
    varietal_note: '灰皮諾（Pinot Grigio）是源自勃艮第的國際白品種，多數平價版清瘦簡單。但這支是酒莊視為「cru」的單一園高階款，經部分橡木桶與較長熟成，打破「平淡灰皮諾」的印象——更圓潤、有層次、餘韻更長，是認識「進階版灰皮諾」很好的範例。',
    region_note: 'Valdadige（瓦達迪傑）／Terra dei Forti 是阿迪傑（Adige）河谷、威尼托與特倫提諾交界的狹長產區（Terra dei Forti「碉堡之地」之名源自拿破崙時代的要塞）。高山冷涼、日夜溫差大，賦予白酒清新酸度與礦物純淨感，很容易讓人聯想到科莫湖（Lake Como）一帶優雅清冷的湖光山色。',
    vinification_note: 'Rìvoli 是酒莊的單一園 cru，僅選優質地塊的果實；約 80% 不鏽鋼槽、20% 法國橡木桶發酵，再經約 10 個月槽中熟成與瓶中陳放。少量過桶與長時間熟成讓它比一般入門灰皮諾更有酒體、層次與綿長餘韻，但仍保留乾淨明亮的酸度。',
    classification_note: 'Valdadige Terradeiforti DOC 是橫跨威尼托與特倫提諾的法定產區（部分標示亦寫作 Trentino-Alto Adige）。這支屬酒莊旗艦「Le Firme」系列的單一園款，是產區內較講究的一群。',
    producer_note: '羅埃諾（Azienda Agricola Roeno）由 Fugatti 家族經營，位於威尼托維羅納省北端的 Brentino Belluno、Terra dei Forti 一帶。父親 Rolando 創立後，由 Roberta、Cristina 與 Giuseppe 三姊弟發揚光大，是 Valdadige／維羅納區最受敬重的小型酒農之一，多次獲 Gambero Rosso 三杯肯定。台灣由越昇國際代理。',
    why_beginner: '它比超市常見的清瘦型灰皮諾「更有料」：果香直接易懂（檸檬、洋梨、白桃）、酸度乾淨不尖銳，又因熟成多了圓潤質地，純飲或配餐都好入口，是新手認識「進階灰皮諾」很友善的一支。',
    drink_window: '現在 – 2027',
    serve_temp: '10–12°C',
    decant: '不需要醒酒；冰鎮至約 10°C（10–12°C）開瓶即飲，太冰會壓抑它圓潤的果香與質地。',
    background: '這支來自一家拿下 Gambero Rosso 2026 三杯（約 93 分）的精品小農。Rìvoli 是酒莊視為 cru 的單一葡萄園，展現阿爾卑斯山腳下冷冽純淨的灰皮諾風格——內斂、優雅，是「打破平淡灰皮諾印象」的好例子。',
    tasting_focus: '品飲練習：(1) 把它和印象中清淡的超市灰皮諾對照，留意這支多出來的圓潤酒體與綿長餘韻（來自過桶與長熟成）。(2) 找尾段那一絲高雅的烤杏仁微苦。(3) 在約 10°C 純飲，感受高山白酒的乾淨俐落。',
    notes_short: 'Gambero Rosso 三杯的單一園 cru 灰皮諾，圓潤多層次，打破「平淡灰皮諾」印象',
    notes_long: null,
    color_hex: '#E4D89A',
    beginner_friendly: true,
    style_axis: 52,
    style_note: '灰皮諾是國際品種、偏標準化；但這支是單一園 cru、阿迪傑河谷高山風土加上過桶熟成的工藝，把辨識度拉高，因此落在中間略偏國際。',
    image: null,
  },
  {
    id: 'argiolas-is-argiolas-vermentino',
    region_key: 'sardegna',
    category: 'wine',
    type: 'white',
    type_zh: '白酒',
    name_en: 'Is Argiolas Vermentino di Sardegna',
    name_zh: '阿吉歐拉斯 伊斯阿吉歐拉斯',
    producer: 'Argiolas',
    varietal: 'Vermentino',
    varietal_zh: '維門提諾',
    region: 'Sardegna',
    region_zh: '薩丁尼亞',
    country: 'Italy',
    country_zh: '義大利',
    year: 2024,
    abv: 14,
    sweetness: '乾型',
    classification: 'Vermentino di Sardegna DOC',
    price: null,
    bottles: 1,
    price_tier: '$$',
    market_price_twd: '約 NT$880–1,000',
    rating: null,
    tasting_date: null,
    occasion: '越昇環義品飲課程 · 活動購入（4 支 NT$5,500 套組）',
    highlights: [
      '薩丁尼亞地標酒莊（旗艦 Turriga 加持）的進階款 Vermentino',
      '老藤晚收 + 6–8 個月酒渣陳釀，酒體飽滿多層次',
      '招牌「微鹹海風感（salinity）」＋ 地中海香草',
      '四支裡香氣最外放、最熱情奔放的一款',
    ],
    appearance: '明亮的禾稈黃、清澈。',
    aroma: ['熟杏桃', '水蜜桃', '哈密瓜', '柑橘', '迷迭香等地中海香草', '蜂蜜杏仁'],
    palate: ['飽滿', '爽脆酸度', '海風鹹礦尾韻', '熟果重量感'],
    finish: '海風般的鹹礦尾韻配爽脆酸度，悠長而有活力。',
    pairing: ['蒜香海鮮義大利麵', '微辣海鮮', '義式前菜', '奶香燉飯', '炸物'],
    pairing_note: '它最好的歸宿就是搭海鮮，尤其帶蒜香或微辣的海鮮義大利麵——飽滿酒體與鹹鮮尾韻能呼應海味、酸度能解膩。冰得透涼再喝最迷人。',
    varietal_note: '維門提諾（Vermentino）是地中海沿岸（薩丁尼亞、利古里亞、托斯卡尼、法國科西嘉）的招牌白葡萄，特色是柑橘、白花、地中海香草，以及一抹標誌性的「鹹味（salinity）」。薩丁尼亞被視為它最重要的家，能釀出酒體飽滿、香氣奔放又帶海風鹹感的版本。',
    region_note: '薩丁尼亞（Sardegna）是地中海第二大島，陽光充足、海風強勁、灌木叢（macchia）遍布，賦予白酒成熟果味、香草氣息與鮮明的鹹礦尾韻。維門提諾是島上最重要的白葡萄，充滿海島的熱情個性。',
    vinification_note: '「Is Argiolas」是酒莊 Vermentino 系列中的進階款（高於入門的 Costamolino）：選自莊內較老的葡萄園、較晚採收，全程不鏽鋼槽低溫發酵以保留鮮度，再經約 6–8 個月酒渣陳釀增添酒體與層次，因此比一般清爽型 Vermentino 更有重量與口感深度。',
    classification_note: 'Vermentino di Sardegna DOC 是涵蓋全薩丁尼亞島的法定產區，規範以維門提諾為主的乾型白酒。（島上另有更嚴格、限於北部加盧拉一帶的 Vermentino di Gallura DOCG。）',
    producer_note: '阿吉歐拉斯（Argiolas）是薩丁尼亞最具代表性的家族酒莊，1938 年由 Antonio Argiolas 創立、現由家族第三代經營，總部在 Serdiana。它以旗艦紅酒「Turriga」（曾由傳奇釀酒顧問 Giacomo Tachis 操刀）聞名，多次拿下義大利權威評鑑 Gambero Rosso 最高榮譽三只酒杯，奠定了「帶領薩丁尼亞走向世界」的地標地位。台灣由越昇國際代理。',
    why_beginner: '它果香飽滿、香氣奔放好認，搭海鮮幾乎不會錯。對新手唯一要提醒的是：它帶有「熟果＋地中海香草＋鹹礦」的個性，初接觸可能略陌生——把它冰得很透（6–8°C）再喝，低溫能收斂草本味、讓清新果酸與鹹鮮更突出。',
    drink_window: '現在 – 2026（年輕即飲、不需久藏）',
    serve_temp: '6–8°C',
    decant: '不需要醒酒；重點是「冰透」——約 6–8°C，低溫能收斂奔放的草本香、凸顯果酸與鹹鮮平衡。',
    background: '這支充滿地中海陽光與海島風情，是四支酒中個性最外放的一款。Argiolas 是薩丁尼亞的地標名莊，「Is Argiolas」則是它 Vermentino 的進階款——以老藤與酒渣陳釀打造出比入門款更飽滿的酒體與層次。',
    tasting_focus: '品飲練習：(1) 專心抓尾段那股像「海風／海鹽」的鹹鮮感（salinity），這是 Vermentino 與海島風土的指紋。(2) 試著一開瓶（較溫）與冰透後各喝一口，體會低溫如何收斂草本味、放大果香——這對「不太習慣草本熟果香」的你特別有用。(3) 配一口蒜香海鮮義大利麵，感受鹹鮮與海味的呼應。',
    notes_short: '薩丁尼亞地標酒莊的進階款老藤 Vermentino，熱情奔放、海風鹹礦尾韻，配海鮮一絕',
    notes_long: null,
    color_hex: '#E8DD9C',
    beginner_friendly: true,
    style_axis: 68,
    style_note: '維門提諾在薩丁尼亞風土下的鹹礦與香草個性鮮明、偏風土；但它也是地中海廣布的品種、釀法走乾淨保鮮路線，因此偏風土但不極端。',
    image: null,
  },
];

// 類型 → 中文 + 顏色（給篩選器跟圖表用）
export const typeMeta = {
  'sparkling-red':   { zh: '氣泡紅', accent: '#7A2024', group: 'sparkling' },
  'sparkling-white': { zh: '氣泡白', accent: '#B89A5E', group: 'sparkling' },
  'red':             { zh: '紅酒',   accent: '#5C1A1B', group: 'red' },
  'white':           { zh: '白酒',   accent: '#A8924E', group: 'white' },
  'rose':            { zh: '粉紅酒', accent: '#93515C', group: 'rose' },
};

// 風格光譜的兩端標籤（給 modal 與圖表共用）
export const STYLE_AXIS_ENDS = {
  left:  { zh: '國際風格', en: 'International' },
  right: { zh: '風土個性', en: 'Terroir' },
};

// 把 0–100 的 style_axis 轉成一個分級標籤
export function styleAxisTier(v) {
  if (v == null) return null;
  if (v <= 22) return { zh: '國際風格', en: 'International' };
  if (v <= 42) return { zh: '偏國際',   en: 'Leans Intl' };
  if (v <= 58) return { zh: '兼具',     en: 'Balanced' };
  if (v <= 78) return { zh: '偏風土',   en: 'Leans Terroir' };
  return { zh: '風土個性', en: 'Terroir' };
}

// ============================================================
// 義大利 20 個葡萄酒產區（事實/參考資料，已查證）
// 「產區地圖」用：每支酒的 region_key 連到這張表；未收藏的產區也能顯示代表酒。
// zone：North / Central / South / Islands（標準酒業 4 區慣例；顯示時南部與離島併為一組）。
// grapes 代表品種、wines 代表酒/法定產區、note 一句話新手導覽。
// 新增義大利酒時：給酒一個 region_key 對應這裡的 key 即可自動上表。
// ============================================================
export const ITALY_REGIONS = [
  // —— 北部 North（8）——
  { key: 'piemonte', name_en: 'Piedmont', name_it: 'Piemonte', name_zh: '皮埃蒙特', zone: 'North',
    grapes: ['Nebbiolo', 'Barbera', 'Moscato'], wines: ['Barolo', 'Barbaresco', 'Barbera d\'Alba'],
    note: '義大利紅酒王國，Barolo 被稱「酒中之王」；新手可先試單寧較柔、果香飽滿的 Barbera。' },
  { key: 'valle-aosta', name_en: 'Valle d\'Aosta', name_it: 'Valle d\'Aosta', name_zh: '奧斯塔谷', zone: 'North',
    grapes: ['Prié Blanc', 'Petit Rouge', 'Fumin'], wines: ['Blanc de Morgex', 'Torrette'],
    note: '義大利最小、最高海拔的阿爾卑斯山產區；高山清爽白酒與柔順紅酒為主。' },
  { key: 'trentino-alto-adige', name_en: 'Trentino-Alto Adige', name_it: 'Trentino-Alto Adige', name_zh: '上阿迪杰', zone: 'North',
    grapes: ['Pinot Grigio', 'Gewürztraminer', 'Lagrein'], wines: ['Alto Adige DOC', 'Trentodoc', 'Teroldego'],
    note: '阿爾卑斯高山白酒天堂，乾淨純淨；清爽 Pinot Grigio 或花香 Gewürztraminer 入門。' },
  { key: 'emilia-romagna', name_en: 'Emilia-Romagna', name_it: 'Emilia-Romagna', name_zh: '艾米利亞-羅馬涅', zone: 'North',
    grapes: ['Lambrusco', 'Sangiovese', 'Albana'], wines: ['Lambrusco di Sorbara', 'Romagna Sangiovese'],
    note: '美食之鄉，微甜微氣泡紅酒 Lambrusco 最親民，配義式火腿起司一流。' },
  { key: 'veneto', name_en: 'Veneto', name_it: 'Veneto', name_zh: '威尼托', zone: 'North',
    grapes: ['Glera', 'Corvina', 'Garganega'], wines: ['Prosecco', 'Amarone', 'Soave'],
    note: '出口量最大的產區，從氣泡到濃郁紅酒全包；入門首選人人愛的 Prosecco。' },
  { key: 'friuli', name_en: 'Friuli-Venezia Giulia', name_it: 'Friuli-Venezia Giulia', name_zh: '弗留利', zone: 'North',
    grapes: ['Friulano', 'Ribolla Gialla', 'Pinot Grigio'], wines: ['Collio', 'Friuli DOC'],
    note: '義大利頂級白酒產地（八成以上是白酒）；想喝乾淨花香白酒可從 Friulano 入門。' },
  { key: 'lombardia', name_en: 'Lombardy', name_it: 'Lombardia', name_zh: '倫巴第', zone: 'North',
    grapes: ['Chardonnay', 'Pinot Nero', 'Nebbiolo'], wines: ['Franciacorta', 'Valtellina', 'Oltrepò Pavese'],
    note: '傳統法氣泡酒重鎮；想喝氣泡選香檳工法的 Franciacorta，紅酒試山區的 Valtellina。' },
  { key: 'liguria', name_en: 'Liguria', name_it: 'Liguria', name_zh: '利古里亞', zone: 'North',
    grapes: ['Vermentino', 'Pigato', 'Rossese'], wines: ['Cinque Terre', 'Rossese di Dolceacqua'],
    note: '地中海沿岸小產區，清爽帶鹹礦感的白酒聞名；配海鮮首選 Vermentino。' },
  // —— 中部 Central（5）——
  { key: 'toscana', name_en: 'Tuscany', name_it: 'Toscana', name_zh: '托斯卡尼', zone: 'Central',
    grapes: ['Sangiovese', 'Vernaccia', 'Cabernet'], wines: ['Chianti Classico', 'Brunello di Montalcino', 'Vino Nobile'],
    note: '最知名紅酒產區，山吉歐維榭釀的 Chianti 酸櫻桃清爽好搭餐，是入門首選。' },
  { key: 'abruzzo', name_en: 'Abruzzo', name_it: 'Abruzzo', name_zh: '阿布魯佐', zone: 'Central',
    grapes: ['Montepulciano', 'Trebbiano', 'Pecorino'], wines: ['Montepulciano d\'Abruzzo', 'Cerasuolo d\'Abruzzo'],
    note: 'Montepulciano d\'Abruzzo 果香飽滿、單寧柔、價格實惠，新手最易上手的義大利紅酒。' },
  { key: 'marche', name_en: 'Marche', name_it: 'Marche', name_zh: '馬爾凱', zone: 'Central',
    grapes: ['Verdicchio', 'Montepulciano', 'Sangiovese'], wines: ['Verdicchio dei Castelli di Jesi', 'Rosso Conero'],
    note: '白葡萄 Verdicchio 聞名，酸度清爽帶礦石與杏仁尾韻，CP 值高、好配海鮮。' },
  { key: 'umbria', name_en: 'Umbria', name_it: 'Umbria', name_zh: '翁布里亞', zone: 'Central',
    grapes: ['Sagrantino', 'Grechetto', 'Sangiovese'], wines: ['Montefalco Sagrantino', 'Orvieto'],
    note: '唯一不靠海的中部產區；清爽白酒試 Orvieto，重口味單寧挑戰超濃的 Sagrantino。' },
  { key: 'lazio', name_en: 'Lazio', name_it: 'Lazio', name_zh: '拉吉歐', zone: 'Central',
    grapes: ['Malvasia', 'Trebbiano', 'Cesanese'], wines: ['Frascati', 'Cesanese del Piglio'],
    note: '羅馬所在地，好入口的 Frascati 白酒清爽日常、價格親民；紅酒找本地的 Cesanese。' },
  // —— 南部 South（5）——
  { key: 'campania', name_en: 'Campania', name_it: 'Campania', name_zh: '坎帕尼亞', zone: 'South',
    grapes: ['Aglianico', 'Fiano', 'Greco'], wines: ['Taurasi', 'Fiano di Avellino', 'Greco di Tufo'],
    note: '南義最有深度的產區，紅酒看「南部的 Barolo」Taurasi，白酒試清爽的 Greco di Tufo。' },
  { key: 'puglia', name_en: 'Puglia', name_it: 'Puglia', name_zh: '普利亞', zone: 'South',
    grapes: ['Primitivo', 'Negroamaro'], wines: ['Primitivo di Manduria', 'Salice Salentino'],
    note: '「鞋跟」陽光產區、CP 值極高；Primitivo（即加州 Zinfandel）果醬甜潤，新手最好上手。' },
  { key: 'basilicata', name_en: 'Basilicata', name_it: 'Basilicata', name_zh: '巴西利卡塔', zone: 'South',
    grapes: ['Aglianico'], wines: ['Aglianico del Vulture'],
    note: '幾乎只有一張王牌：火山土上的 Aglianico，結構厚實耐陳，南義硬派紅酒代表。' },
  { key: 'calabria', name_en: 'Calabria', name_it: 'Calabria', name_zh: '卡拉布里亞', zone: 'South',
    grapes: ['Gaglioppo'], wines: ['Cirò'],
    note: '「鞋尖」較冷門產區，古老紅葡萄 Gaglioppo 釀的 Cirò 酸度高、帶玫瑰菸草香。' },
  { key: 'molise', name_en: 'Molise', name_it: 'Molise', name_zh: '莫利塞', zone: 'South',
    grapes: ['Tintilia', 'Montepulciano', 'Aglianico'], wines: ['Tintilia del Molise', 'Biferno'],
    note: '義大利第二小、低調的產區，招牌是本地獨有品種 Tintilia，辛香紮實的紅酒。' },
  // —— 離島 Islands（2）——
  { key: 'sicilia', name_en: 'Sicily', name_it: 'Sicilia', name_zh: '西西里', zone: 'Islands',
    grapes: ['Nero d\'Avola', 'Nerello Mascalese', 'Grillo'], wines: ['Etna Rosso', 'Cerasuolo di Vittoria', 'Marsala'],
    note: '近年最熱門的島嶼產區；紅酒從飽滿 Nero d\'Avola 入門，進階試 Etna 火山的礦感紅酒。' },
  { key: 'sardegna', name_en: 'Sardinia', name_it: 'Sardegna', name_zh: '薩丁尼亞', zone: 'Islands',
    grapes: ['Cannonau', 'Vermentino', 'Carignano'], wines: ['Vermentino di Gallura', 'Cannonau di Sardegna'],
    note: '地中海大島，白酒首選 Vermentino 清爽帶柑橘鹹味；紅酒 Cannonau（即格那希）溫暖好入口。' },
];

// 顯示分組：北 / 中 / 南＋離島（尊重「北中南」，離島併入南部一組但仍各自列出）
export const ITALY_ZONE_GROUPS = [
  { key: 'north',   it: 'Nord',        zh: '北部',      en: 'North',            zones: ['North'] },
  { key: 'central', it: 'Centro',      zh: '中部',      en: 'Central',          zones: ['Central'] },
  { key: 'south',   it: 'Sud · Isole', zh: '南部 · 離島', en: 'South & Islands', zones: ['South', 'Islands'] },
];

// ============================================================
// 酒莊（producer）參考表 — 給「產區地圖」的酒莊檢視與酒莊 modal 用。
// key = wine.producer 字串（直接 join）；story 是把同莊各酒的 producer_note
//   合併去重後的「莊級」簡介（事實敘述、不含個人評分）。
// founded / place / tagline / owner / image 皆可選，缺了就不顯示。
// story 為莊級豐富敘事（歷史＋文化特色＋地位，用空行分段）；signature 為該莊名酒/必喝（事實，不含個人評分）。
// image = Unsplash CDN 的 photo-id（已 curl 驗證可載入）。
// 新增義大利酒時：給酒一個 producer 字串對到這裡的 key 即可自動上莊。
// ============================================================
export const PRODUCERS = [
  {
    key: 'St. Michael-Eppan', name_zh: '聖米歇爾-艾本', region_key: 'trentino-alto-adige',
    founded: '1907', place: 'Eppan, 上阿迪杰', type: '合作社', tagline: '上阿迪杰黑皮諾名家',
    owner: '艾本葡農合作社', image: 'photo-1642872664566-e130139d0f77',
    story: `聖米歇爾-艾本（St. Michael-Eppan，義大利文 San Michele Appiano）是上阿迪杰（Alto Adige／南提洛 Südtirol）最具份量的酒莊之一，1907 年由艾本鎮（Appiano）27 位有遠見的葡萄農合資創立。當年他們的想法很單純：與其各自賣便宜散酒，不如集合眾人之力、共同提升品質。一個多世紀後，這間合作社已成長為約 320 戶葡萄農家族、約 390 公頃葡萄園、年產逾兩百萬瓶的規模。村名「Eppan／Appiano」源自古羅馬執政官 Appius，這段拉丁血脈日後也成了酒莊頂級旗艦酒「Appius」名字的由來。

合作社的故事，幾乎與一個人畫上等號——傳奇釀酒師 Hans Terzer。他 1977 年起掌管釀造，將一間地方合作社一路帶上義大利與國際舞台，被 Gambero Rosso 列入「全球十大釀酒師」。他是上阿迪杰最早大膽種下 Sauvignon Blanc 與 Chardonnay 的先驅之一，幾乎憑一己之力定義了今日世人對南提洛白酒的印象，因而有「Mr. Sauvignon」的稱號。酒莊哲學核心是「風土的純粹表達」：頂級酒只取海拔約 450 至 600 公尺、礫石與石灰岩土壤的精選地塊，低產量、手工分選，讓阿爾卑斯山腳的日夜溫差化為酒中鮮明的礦物張力與酸度。2024 年 Terzer 交棒給年輕釀酒師 Jakob Gasser。

它的頂級酒系列「Sanct Valentin」創立於 1986 年，是南提洛「山地白酒」優雅與陳年潛力的標竿。酒莊 2000 年獲選 Gambero Rosso 年度酒莊，更因連續 30 次拿下最高榮譽「Tre Bicchieri（三隻酒杯）」，於 2018 年成為首間獲頒 Gambero Rosso「三顆星」殊榮的南提洛酒莊——是「合作社也能釀出頂級酒」的最佳範例。`,
    signature: [
      { name: `Sauvignon Sanct Valentin Alto Adige DOC`, note: `酒莊與 Hans Terzer 的招牌之作，產自礫石石灰岩坡地，接骨木花、醋栗與礦物張力交織，是南提洛 Sauvignon 的標竿。` },
      { name: `Appius Alto Adige DOC`, note: `膜拜級旗艦白酒 cuvée（Terzer 親手調配），每年限量約 7,000 瓶、逐瓶編號、年年換藝術酒標，是收藏家追逐的夢幻酒。` },
      { name: `Weissburgunder (Pinot Bianco) Sanct Valentin`, note: `把白皮諾釀成有重量的頂級酒，木桶培養帶來力量與飽滿，又保有清晰礦物收尾。` },
      { name: `Gewürztraminer Sanct Valentin`, note: `玫瑰、荔枝與異國香料奔放卻不甜膩、平衡有礦物感，是領略上阿迪杰芳香白酒的名作。` },
      { name: `Pinot Nero Riserva Sanct Valentin`, note: `展現酒莊紅酒實力，山地黑皮諾的細緻紅果與優雅單寧。` },
    ],
  },
  {
    key: 'Tenuta Carretta', name_zh: '卡蕾塔', region_key: 'piemonte',
    founded: '1467', place: 'Piobesi d\'Alba, Roero', type: '家族莊', tagline: '皮埃蒙特最古老酒莊之一',
    owner: 'Miroglio 家族', image: 'photo-1602491399262-55831860b387',
    story: `坐落於皮埃蒙特 Roero 產區、阿爾巴（Alba）西北方塔納羅河左岸的 Piobesi d'Alba，Tenuta Carretta 是義大利最古老、且持續釀酒至今的酒莊之一。莊園歷史可追溯至 1467 年 11 月 28 日的一紙佃租契約。酒莊之名「Carretta／Careta」更早源於 14 世紀一位阿爾巴貴族女子 Careta Costanzi。此後莊園歷經數百年易主，直到 1985 年由阿爾巴知名紡織集團 Miroglio 家族買下並重建，開啟現代篇章。

文化上，Carretta 最動人的角色，是它在「Arneis 復興」中的份量。Roero 的白葡萄 Arneis（俗稱「白內比歐露」）20 世紀中葉幾乎絕跡，Carretta 正是讓它重生最重要的推手之一。如今它以三款 Arneis 詮釋此品種：親民的 Cayega、橡木桶發酵的 Canorei、久放酒泥的 Alteno della Fontana Riserva。釀造強調可持續耕作、手工採收，並把 15 世紀古窖與莊園悉心修復。

Carretta 最罕見的優勢，是幾乎握有 Nebbiolo 所有經典原鄉的園地。約 80 公頃葡萄園橫跨 Langhe 與 Roero（2014 年入選 UNESCO 世界遺產），讓它能同時釀出 Barolo、Barbaresco、Roero 與 Nebbiolo d'Alba。其中最受矚目的，是它在 Barolo 最負盛名的古老單一園 Cannubi 山坡上擁有約 2.6 公頃葡萄——全球僅約二十家酒莊掛得上 Cannubi 之名。莊園內更設有米其林一星餐廳與精品酒店，是探訪皮埃蒙特兼具歷史厚度與享受的代表。`,
    signature: [
      { name: `Roero Arneis DOCG "Cayega"`, note: `酒莊年產逾十萬瓶的招牌白酒，花香、洋槐蜜與淡淡熱帶果香，是認識 Roero Arneis 最經典親民的入門款（也是你收的這支）。` },
      { name: `Barolo DOCG "Cannubi"`, note: `來自 Barolo 最古老頂級的傳奇單一園 Cannubi，優雅、有骨架且極耐陳年，是酒莊皇冠上的明珠。` },
      { name: `Barbaresco DOCG "Cascina Bordino" Riserva`, note: `Treiso 陡坡砂質土的 Nebbiolo，陳釀逾 50 個月，香氣細膩、結構綿長。` },
      { name: `Roero DOCG "Bric Paradiso" Riserva`, note: `Roero 紅酒的標竿之作，最能代表 Roero 砂土孕育 Nebbiolo 的柔美與芳香。` },
      { name: `Roero Arneis Riserva "Canorei"`, note: `橡木桶發酵陳放的進階版 Arneis，展現此品種少見的陳年潛力與圓潤質地。` },
    ],
  },
  {
    key: 'Tenuta Pederzana', name_zh: '佩德札納', region_key: 'emilia-romagna',
    founded: '', place: 'Castelvetro, Modena', type: '家族小農', tagline: '葛拉斯帕羅薩老品系小農',
    owner: 'Gibellini 家族', image: 'photo-1761469309960-9bea46abe2bb',
    story: `Tenuta Pederzana 的故事要從二戰後的莫德納山丘說起。創辦人 Franco Simonini 是 Castelvetro 一位前衛的葡萄農，他與妻子 Margherita 看中 Solignano Vecchio 緩坡上一塊美麗莊園，並與波隆那大學長期合作，試圖從當地最尊貴的本土品種 Grasparossa di Castelvetro 中，篩選出最優秀的無性繁殖系（clone）。多年後接手酒莊的姪子 Francesco Gibellini 才發現，這支家族世代守護的老株，竟是義大利葡萄栽培實驗研究所登錄名單中獨一無二的存在——這成了酒莊最珍貴的身世。

如今酒莊由 Francesco Gibellini 與叔叔 Massimo 共同經營，是「一間扎根傳統的現代酒莊」。莊園約 14–15 公頃，園區間還夾雜橡木林與泉水小湖，生態完整。黏土質土壤、涼爽夜晚、向東坡向讓葡萄緩慢成熟、累積飽滿色素。他們把那支「世界獨一無二」的古老 Grasparossa 嫁接於 Golia 砧木、Guyot 引枝、每公頃約 4,000 株密植，堅持全程手工採收——對單一風土與單一老株的執著，正是酒莊核心。

在 Lambrusco 世界裡，Grasparossa 一向是色深、單寧最紮實、最有「紅酒感」的一支，而 Pederzana 正是把它推向精緻與深度的代表性小農。他們既做百搭日常的乾型氣泡紅，也在特別年份釀出旗艦 Ubi Maior——甚至用類似 Amarone 的風乾工法處理，是同產區極少見的野心之作。對想認識「乾型、嚴肅版 Lambrusco」的人，這是 Castelvetro 不能略過的名字。`,
    signature: [
      { name: `Il Grasparossa della Tradizione`, note: `最經典的入門乾型氣泡紅，深紫紅、櫻桃與李子果香、細緻氣泡與紮實單寧，是認識 Grasparossa「紅酒感 Lambrusco」最好的起點（你收的這支）。` },
      { name: `Spiriti Folletti (Secco)`, note: `刻意打破「又甜又軟」印象的乾型版本，野草莓、櫻桃與紫羅蘭、酸度俐落尾韻乾爽，配披薩一絕（你收的這支）。` },
      { name: `Ubi Maior`, note: `酒莊旗艦、整個產區罕見的野心之作：用風乾（appassimento）類 Amarone 工法，桶陳兩年、瓶陳三年，濃縮深厚。` },
      { name: `Puntamora`, note: `老藤晚收 Grasparossa 加少量 Ancellotta 的微甜（amabile）版本，酒體圓潤、口感柔順、百搭討喜。` },
    ],
  },
  {
    key: 'Fratelli Cella', name_zh: '雀拉', region_key: 'emilia-romagna',
    founded: '1960', place: 'Campegine, Emilia', type: '量產品牌', tagline: '行銷四十多國的商業蘭布魯斯科',
    owner: 'Cantine Riunite & CIV', image: 'photo-1774900134488-617fa79809ae',
    story: `Fratelli Cella 創立於 1960 年，是艾米利亞-羅馬涅最為人熟知的 Lambrusco 品牌之一，根據地在雷焦艾米利亞省的坎佩吉內（Campegine）小鎮。從一開始它就專注於這片土地最具代表性的微氣泡酒 Lambrusco——一種帶輕盈泡沫、酒精度不高、好親近的紅葡萄酒。六十多年來，Cella 把這種原本屬於艾米利亞餐桌的家常酒推向了全世界。

Cella 走的不是自有大莊園路線，而是合作社式、串連在地小農的模式：葡萄主要來自摩德納一帶、由眾多會員酒農細心種植，再以完整的一條龍生產鏈釀製——這讓它能穩定產出風格一致、品質可靠、價格親民的 Lambrusco。如今它隸屬於 Cantine Riunite & CIV 集團（背後約 1,500 戶葡萄農、4,600 公頃葡萄園、年售約 1.4 億瓶），是全世界 Lambrusco 與艾米利亞氣泡酒的龍頭。

在國際舞台上，Cella 行銷超過 40 個國家，在美國、日本與歐洲尤其受歡迎。它成功的秘訣很單純：好喝、酒精度低、帶一點甜，可以輕鬆配甜點或當開胃酒。對剛入門的人來說，Cella 幾乎是認識 Lambrusco 這個酒種最方便、最具代表性的一扇門——和同產區的佩德札納小農，剛好是兩個極端。`,
    signature: [
      { name: `Lambrusco dell'Emilia Rosso IGT`, note: `品牌最具代表性的微甜紅氣泡，深紅寶石色帶輕盈泡沫、紅莓與李子香、尾韻一抹櫻桃微苦，是認識 Lambrusco 的經典首選（你收的微甜款近這支風格）。` },
      { name: `Lambrusco dell'Emilia Rosato IGT`, note: `淡粉紅、活潑泡沫，清新果香帶明顯紫羅蘭花香，清爽討喜、入門者容易愛上。` },
      { name: `Lambrusco dell'Emilia Bianco IGT`, note: `以 Lambrusco 葡萄釀的白氣泡，清爽果香、柔甜收尾乾淨，想換個輕鬆風味時的熱門選擇。` },
      { name: `Lambrusco Rosso Amabile dell'Emilia IGT`, note: `半甜版紅 Lambrusco，甜酸平衡、莓果明顯，是超市與日常餐桌上最普及的甜微氣泡入門。` },
    ],
  },
  {
    key: 'Cave Mont Blanc', name_zh: '白朗峰', region_key: 'valle-aosta',
    founded: '1983', place: 'Morgex, 奧斯塔谷', type: '合作社', tagline: '歐洲最高酒廠（2,173m）',
    owner: '山地酒農合作社', image: 'photo-1765574782003-75d8f507f939',
    story: `海拔近一千兩百公尺、背倚歐洲最高峰白朗峰的義大利西北角，藏著一座「英雄式」的合作社酒莊——Cave Mont Blanc de Morgex et de La Salle。根源可追溯到 Morgex 本堂神父 Don Bougeat 在 1971 年催生的「葡萄農協會」。1983 年，受阿爾卑斯村莊互助傳統啟發，約 70 戶酒農正式成立合作社，把零散的小塊葡萄園集中、共享資源，讓這片獨一無二的風土被世界看見。創社三年後推出第一個年份，氣泡酒僅一千瓶就一炮而紅；如今年產約十萬至十四萬瓶。

這裡只種一個品種：原生白葡萄 Prié Blanc。它最傳奇之處，是極高海拔與嚴寒讓它躲過了十九世紀橫掃全歐的根瘤蚜，至今仍以「未嫁接」（自根）老藤栽培，是歐洲少數保留原始根系的葡萄。葡萄園散落在 Morgex 與 La Salle、海拔 900 至 1,200 公尺的山坡，全採低矮的「瓦萊達奧斯塔棚架」把藤蔓抬離地面、利用石牆與地熱抵禦霜凍——晚萌芽躲春霜、早熟趕在初雪前採收，是與高山賽跑的栽培哲學。

Cave Mont Blanc 不只「種得高」，更把高度玩成一種實驗精神。它在白朗峰纜車站、海拔 2,173 公尺處設了一座實驗酒窖，與高山嚮導協會合作在此進行瓶中二次發酵、熟成氣泡酒；近年並利用 Cogne 海拔約 1,800 公尺的廢棄磁鐵礦坑，借其恆溫恆濕自然陳年。作為瓦萊達奧斯塔唯一的 DOC 傳統法氣泡酒生產者、也是高山「英雄葡萄酒」的代表，它既守護瀕危原生品種與梯田景觀，也以海拔、冰酒與礦坑陳年成為義大利高山酒最具辨識度的名字之一。`,
    signature: [
      { name: `Blanc de Morgex et de La Salle DOC`, note: `招牌基礎款，100% 未嫁接 Prié Blanc、不鏽鋼釀造，清新爽脆帶柑橘與礦物感，是認識歐洲最高葡萄園最入門經典的一支（你收的氣泡即出自此系列）。` },
      { name: `Cuvée du Prince (Metodo Classico)`, note: `瓦萊達奧斯塔唯一的 DOC 傳統法氣泡代表作，瓶中陳年達 72 個月，氣泡細緻、酸度凌厲帶蘋果蜂蜜。` },
      { name: `Chaudelune Vin de Glace`, note: `招牌冰酒，葡萄結凍後夜採、以當地木桶釀成，蜜餞杏桃、香草與柑橘交織，是酒莊不可取代的甜酒名片。` },
      { name: `Cuvée des Guides`, note: `在白朗峰纜車站 2,173m 實驗酒窖二次發酵熟成的氣泡酒，把「歐洲最高酒窖」直接喝進杯中，極具話題與收藏意義。` },
    ],
  },
  {
    key: 'Grosjean', name_zh: '葛羅讓', region_key: 'valle-aosta',
    founded: '1968', place: 'Quart, 奧斯塔谷', type: '家族莊', tagline: '奧斯塔谷第一家有機認證酒莊',
    owner: 'Grosjean 家族', image: 'photo-1742974549252-ebb75c773e6f',
    story: `Grosjean 家族與奧斯塔山谷的葡萄藤糾纏已超過四百年。最早可追溯到 1630 年大瘟疫橫掃峽谷後，薩伏依公爵自勃艮第與薩伏依招募農家前來重建，Grosjean 就此落腳，世代於 Valgrisenche 高山牧牛、夏季在較低坡地種葡萄與栗子釀酒度冬。真正的轉捩點在 1960 年代：祖父 Dauphin Grosjean 全心投入釀酒、裝出家族第一批酒，並在 1968 年的奧斯塔葡萄酒展一鳴驚人，點燃五個兒子擴園精進的決心，奠定今日酒莊雛形。

Grosjean 是「英雄式葡萄栽培」最純粹的範本。葡萄園散落在海拔 500 至 900 公尺、坡度逼近 80% 的阿爾卑斯陡坡，全靠人工梯田耕作，每公頃投入高達 700–800 小時勞力，遠超義大利平均——機械幾乎使不上力。家族自 1975 年起停用殺蟲劑、只施有機肥，2011 年更成為奧斯塔山谷第一家全面有機認證的酒莊。釀造倚賴原生酵母、低硫、溫和萃取，骨子裡是讓在地品種誠實說話的自然派思維。他們守護著 Petite Arvine、Fumin、Cornalin、Premetta 等 11 種瀕危原生葡萄，是奧斯塔活生生的品種基因庫。

在義大利最小、最高、最難種的產區之一，Grosjean 是公認的標竿。它以一款 Fumin 紅酒成為奧斯塔山谷史上第一家奪下最高榮譽「Tre Bicchieri（三隻酒杯）」的酒莊，替整個產區打開被看見的大門；近年其白酒 Petite Arvine「Les Frères」再度摘下三杯，紅、白兩線都站在頂端。對想認識阿爾卑斯山葡萄酒的人，Grosjean 幾乎是進入這個冷涼、礦感、品種獨特世界的最佳起點。`,
    signature: [
      { name: `Petite Arvine "Les Frères"`, note: `奧斯塔白酒代表作，淡金色、熱帶水果與柑橘香、清爽帶礦石與一抹鹹鮮，近年摘下 Gambero Rosso 三隻酒杯（你收的 Vigne Rovettaz 是同品種的另一園）。` },
      { name: `Fumin "Vigne Rovettaz"`, note: `酒莊最具歷史意義的紅酒，純原生品種 Fumin、桶陳，深色野莓濃郁、層次豐富單寧柔順，正是讓 Grosjean 拿下奧斯塔首座三隻酒杯的酒。` },
      { name: `Torrette`, note: `奧斯塔最經典的日常紅酒法定產區，以 Petit Rouge 為主，紅果鮮明爽口親切，認識本地風格的入門必喝。` },
      { name: `Premetta`, note: `用極稀有原生品種 Premetta 釀的淺色輕紅，蔓越莓與草莓果香、絲滑解渴，Grosjean 是這支瀕危品種最重要的代表釀造者。` },
    ],
  },
  {
    key: 'Elena Walch', name_zh: '伊蓮娜·瓦爾希', region_key: 'trentino-alto-adige',
    founded: '1869', place: 'Tramin, 上阿迪杰', type: '家族莊', tagline: '南提洛首位女釀酒師的指標名莊',
    owner: 'Walch 家族（第五代）', image: 'photo-1770424683058-e8bdd328a54e',
    story: `Elena Walch 酒莊坐落於義大利最北端 Alto Adige 的 Tramin（德文 Termeno）小鎮——這裡正是芳香品種 Gewürztraminer（Traminer 一字即源自 Tramin）的歷史故鄉。家族釀酒淵源可上溯至 1869 年，奧地利人 Wilhelm Walch 買下這座建築，而它在此之前曾作為耶穌會修道院近七十年、修士早已在此釀酒。酒窖至今約三百年歷史，仍保存著 1873 年手工雕刻的古老橡木桶。

真正讓這個古老姓氏脫胎換骨的，是 Elena Walch 本人。她原是米蘭執業的建築師，1983 年受第四代莊主 Werner Walch 之邀前來修復家族那座 1620 年文藝復興城堡 Castel Ringberg，兩人因此相戀結婚，Elena 也放下建築投身釀酒。1985 年她成為南提洛史上第一位、也長期是唯一一位女性釀酒師，1988 年創立以己為名的品牌。她以近乎革命性的眼光重塑家業：率先把單一園分開釀造、推出強調風土的「terroir wines」，大膽改種更具潛力的品種、降低產量換品質。她的核心哲學就是「風土」。

如今酒莊由第五代、Elena 的兩個女兒 Julia 與 Karoline 自 2015 年起接掌，園區約 55–60 公頃、年產約五十萬瓶、全程手工採收。兩座招牌單一園是莊園的心臟：Caldaro 湖畔約 20 公頃的 Castel Ringberg（可能是全 Alto Adige 最大單一園），以及 Tramin 鎮上坡度超過 63%、純南向的 Kastelaz（Gewürztraminer 的聖地）。Gambero Rosso 更封 Elena 為「Gewürztraminer 女王」，是想認識阿爾卑斯山腳白酒精華的必訪名莊。`,
    signature: [
      { name: `Gewürztraminer Vigna "Kastelaz" Alto Adige DOC`, note: `鎮莊之寶、義大利 Gewürztraminer 的國際標竿，來自 63% 純南向極陡梯田，荔枝、玫瑰與熱帶香料濃郁卻優雅，被譽為女王級代表作。` },
      { name: `Beyond the Clouds Alto Adige Bianco DOC`, note: `頂級旗艦白酒，被視為 Alto Adige 第一支白酒「super cuvée」，以 Chardonnay 為主多品種共釀過法國桶，複雜礦感、陳年潛力出色。` },
      { name: `Lagrein Riserva Vigna "Castel Ringberg"`, note: `代表性紅酒，深石榴紅、酒體飽滿，黑莓、李乾、可可與煙燻加絲滑單寧，是 Lagrein 的高階典範（你收的 Lagrein 即此品種）。` },
      { name: `Pinot Grigio Vigna "Castel Ringberg"`, note: `義大利首批掛上法定「Vigna」單一園標示的灰皮諾之一，質地飽滿、礦感與深度兼具，顛覆灰皮諾平淡印象。` },
    ],
  },
  {
    key: 'Donnafugata', name_zh: '多娜佳塔', region_key: 'sicilia',
    founded: '1983', place: 'Marsala, 西西里', type: '家族名莊', tagline: '西西里最具代表性的名莊',
    owner: 'Rallo 家族（第五代）', image: 'photo-1690742135975-f04123a1c471',
    story: `Donnafugata 由 Giacomo Rallo 與妻子 Gabriella 於 1983 年在西西里創立。Rallo 家族並非新手——釀酒根源可追溯到 1851 年在馬沙拉的家族酒廠，至今逾 150 年、傳承五代。當他與被視為「女性葡萄酒先驅」的 Gabriella 另起爐灶時，西西里在國際版圖上幾乎還是一片空白；夫妻倆的夢想，正是釀出能讓世界重新認識西西里的偉大葡萄酒。第一塊葡萄園落在西部 Contessa Entellina 丘陵，是 Donnafugata 故事的起點。

「Donnafugata」這名字本身就是一則傳奇，字面意思是「逃亡的女子」，典出 Tomasi di Lampedusa 的西西里名著《豹》（Il Gattopardo）。這份文學與歷史的浪漫貫穿整個品牌：由 Gabriella 構想、與插畫家 Stefano Vitale 合作的繽紛手繪酒標，一舉揚棄當年制式標籤，以色彩與想像述說西西里風土，成為義大利酒標美學的標誌之一；家族更延伸出「Music & Wine」音樂品酒計畫。永續也是核心——不用除草劑與化肥、自產潔淨能源，是西西里 SOStain 永續基金會的一員。

如今由第五代 José 與 Antonio Rallo 姊弟掌舵，版圖橫跨西西里多個風土：西部核心 Contessa Entellina、火山島 Pantelleria（Zibibbo 老藤）、東南部 Vittoria，以及 2016 年起進駐的埃特納火山北坡，全莊約 380–410 公頃。從西部紅白名釀、火山島的傳奇甜酒，到熔岩坡上的優雅紅白，Donnafugata 已是帶領西西里走向世界的旗艦酒莊，也是「西西里葡萄酒復興」最具代表性的名字。`,
    signature: [
      { name: `Ben Ryé Passito di Pantelleria DOC`, note: `100% Zibibbo 風乾甜酒，名字源自阿拉伯語「風之子」，杏桃、糖漬橙皮與蜂蜜的濃郁複雜，是潘泰萊里亞風乾甜酒的標竿、酒莊最傳奇的招牌，必喝。` },
      { name: `Mille e una Notte`, note: `紅酒旗艦，以 Nero d'Avola 為主混 Petit Verdot 與 Syrah，自 1995 首釀即是西西里紅酒走向世界的象徵，結構磅礡。` },
      { name: `Tancredi`, note: `1990 年代開創性地把本土 Nero d'Avola 與 Cabernet Sauvignon 結合的經典紅酒，後與 Dolce & Gabbana 聯名酒標，兼具歷史與話題。` },
      { name: `Sul Vulcano Etna Rosso DOC`, note: `埃特納火山北坡、以 Nerello Mascalese 為主的紅酒，火山風土帶來紅果、薄荷與礦物的優雅細膩。` },
      { name: `Floramundi Cerasuolo di Vittoria DOCG`, note: `西西里唯一 DOCG，Nero d'Avola＋Frappato 的明亮櫻桃紅、單寧細酸度爽（正是你收的這支）。` },
    ],
  },
  {
    key: 'Franz Haas', name_zh: '法蘭茲·哈斯', region_key: 'trentino-alto-adige',
    founded: '1880', place: 'Montagna／Egna, 上阿迪杰', type: '家族莊', tagline: '義大利黑皮諾的標竿名莊',
    owner: 'Haas 家族（第八代）', image: null,
    story: `法蘭茲·哈斯（Franz Haas）酒莊位在上阿迪杰（Alto Adige／南提洛 Südtirol）南端的 Montagna（德文 Montan）與 Egna 一帶，1880 年創立，至今已傳承八代。這個家族有個浪漫的傳統：每一代的長子都取名 Franz Haas，姓名與酒莊就這樣一代代傳承下來。真正讓酒莊躍上國際的，是這一代的 Franz Haas——他與妻子 Maria Luisa 把焦點轉向高海拔風土與單一品種的精雕細琢，如今由下一代 Franz Josef 接棒延續。

哈斯最為人稱道的是黑皮諾（Pinot Nero）。在這個以白酒聞名的產區，他把嬌貴的黑皮諾種上涼爽的高海拔坡地，釀出細膩優雅、被視為義大利黑皮諾標竿的酒款——旗艦單一選樽「Schweizer」自 1990 年問世以來便是代表作。酒莊另一張名片是罕見的玫瑰麝香（Moscato Rosa）甜紅，以及那一系列色彩斑斕、辨識度極高的藝術酒標——出自畫家兼建築師 Riccardo Schweizer 之手（他曾與 Picasso、Chagall、Le Corbusier 等大師合作）。

酒莊約 60 公頃葡萄園散布在不同海拔、最高的地塊可達約 1,150 公尺，深信「高度與風土」是品質的關鍵。除了招牌黑皮諾，也釀出色的原生紅 Lagrein 與 Manna 等白酒。對台灣酒友來說，這是一家「在白酒產區、卻以紅酒（尤其黑皮諾）揚名」的特別名莊，由越昇國際代理引進。`,
    signature: [
      { name: `Pinot Nero "Schweizer" Alto Adige DOC`, note: `旗艦單一選樽黑皮諾，自 1990 年問世便是代表作，被視為義大利黑皮諾的標竿之一；僅最佳年份生產，細膩優雅與結構兼具（頂級價位）。` },
      { name: `Moscato Rosa`, note: `罕見的玫瑰麝香甜紅，玫瑰花瓣與荔枝般的迷人芳香、甜潤而有酸度撐起，是酒莊最具話題的傳奇招牌。` },
      { name: `Pinot Nero "Pònkler" Alto Adige DOC`, note: `高海拔單一園黑皮諾，純淨清新、優雅有勁，展現哈斯對黑皮諾風土的講究，是 Schweizer 之外的另一頂級表現。` },
      { name: `Manna Bianco Alto Adige DOC`, note: `酒莊招牌的多品種芳香白酒調配（Riesling、Chardonnay、Sauvignon、Gewürztraminer 等），花果奔放又有礦感層次，是南提洛白酒的代表作之一。` },
      { name: `Lagrein Alto Adige DOC`, note: `上阿迪杰招牌原生紅，深近墨黑、黑莓可可與紫羅蘭、尾段帶品種標誌的微苦（正是你收的這支正選④；其標準款黑皮諾「Classic Line」則是你的備選）。` },
    ],
  },
  {
    key: 'Tommasi', name_zh: '托馬西', region_key: 'veneto',
    founded: '1902', place: 'Pedemonte, Valpolicella, 威尼托', type: '家族名莊', tagline: 'Valpolicella 百年名門，Amarone 歷史家族創始成員',
    owner: 'Tommasi 家族（第四代）', image: null,
    story: `托馬西（Tommasi）1902 年由 Giacomo Tommasi 在威尼托 Valpolicella 經典產區的 Pedemonte 創立，是當地最具代表性的百年家族名門之一，如今由家族第四代（十餘位成員）共同經營。它最重要的身分，是「Amarone 歷史家族（Le Famiglie Storiche／Famiglie dell'Amarone）」的創始成員之一——這是一個由維羅納頂尖 Amarone 酒莊組成、致力捍衛 Amarone 品質與名聲的聯盟。

酒莊在 Valpolicella 核心擁有約 195 公頃葡萄園，專精於維羅納原生品種（Corvina、Corvinone、Rondinella）與當地的「枯藤法（appassimento）」工藝——從 Amarone、Ripasso 到甜型 Recioto，一脈相承。Tommasi 的代表作是單一園頂級的 Amarone Riserva「Ca' Florian」，而標準款 Amarone Classico 則是市場公認、品質穩定的標竿入門級。

近數十年 Tommasi 也把版圖擴展到義大利各地（托斯卡尼、普利亞、巴西利卡塔、倫巴底等），成為「具規模卻維持品質」的代表。對想認識義大利「四大紅酒之王」之一 Amarone 的人來說，Tommasi 是最可靠、最具代表性的起點之一。台灣由越昇國際代理。`,
    signature: [
      { name: `Amarone della Valpolicella Classico DOCG`, note: `市場公認的標竿入門級 Amarone，枯藤法釀造、斯拉夫尼亞大橡木桶陳年約 3 年，黑櫻桃、李乾、可可與絲絨般酒體（正是你收的這支）。` },
      { name: `Amarone della Valpolicella Classico Riserva "Ca' Florian"`, note: `單一園頂級 Riserva，更深邃濃縮、陳年潛力更長，是酒莊 Amarone 的旗艦之作。` },
      { name: `Valpolicella Classico Superiore Ripasso "Rafaèl/Ripasso"`, note: `以 Amarone 酒渣「復發酵（ripasso）」而成的「小阿瑪羅內」，比一般 Valpolicella 更有份量、CP 值高，是入門威尼托紅酒的好選擇。` },
      { name: `Recioto della Valpolicella Classico`, note: `同樣用風乾葡萄、但保留甜分的甜紅酒，是 Amarone 的「甜型前身」，黑櫻桃與巧克力般的濃郁甜潤。` },
    ],
  },
  {
    key: 'Roeno', name_zh: '羅埃諾', region_key: 'veneto',
    founded: '1980 年代', place: 'Brentino Belluno, Terra dei Forti, 威尼托', type: '家族小農', tagline: 'Terra dei Forti 最受矚目的精品小農',
    owner: 'Fugatti 家族', image: null,
    story: `羅埃諾（Azienda Agricola Roeno）是一家位於威尼托維羅納省北端 Brentino Belluno、坐落在阿迪傑（Adige）河谷 Terra dei Forti 一帶的精品家族小農。父親 Rolando Fugatti 創立後，由 Roberta、Cristina 與 Giuseppe 三姊弟接棒發揚——Roberta 主釀、家族同心，把這家小農經營成 Valdadige／維羅納區最受矚目的酒莊之一，多次獲義大利權威評鑑 Gambero Rosso 三杯（Tre Bicchieri）肯定。

Terra dei Forti（「碉堡之地」，名字源自拿破崙時代的要塞）是個跨威尼托與特倫提諾、被阿爾卑斯山環抱的狹長高山產區。冷涼氣候與大日夜溫差，讓 Roeno 的白酒（灰皮諾、Müller Thurgau 等）保有清新酸度與礦物純淨感，風格內斂優雅。酒莊也守護當地的原生紅葡萄 Enantio。

代表系列「Le Firme（簽名）」收錄了酒莊最講究的單一園款，其中單一園灰皮諾「Rìvoli」更拿下 Gambero Rosso 2026 三杯。對想認識「阿爾卑斯山腳高山白酒」精緻一面的人，Roeno 是很值得一探的精品小農。台灣由越昇國際代理。`,
    signature: [
      { name: `Pinot Grigio "Rìvoli" Valdadige Terradeiforti DOC`, note: `單一園 cru 灰皮諾，拿下 Gambero Rosso 2026 三杯、約 93 分；圓潤多層次、帶烤杏仁尾韻，打破「平淡灰皮諾」印象（正是你收的這支）。` },
      { name: `"Le Firme" 旗艦系列`, note: `酒莊最講究的單一園精選系列，展現 Terra dei Forti 高山風土的精緻一面。` },
      { name: `Enantio Terradeiforti DOC`, note: `以 Terra dei Forti 古老原生紅葡萄 Enantio（Lambrusco a Foglia Frastagliata）釀成，是當地最具身分認同的紅酒。` },
    ],
  },
  {
    key: 'Argiolas', name_zh: '阿吉歐拉斯', region_key: 'sardegna',
    founded: '1938', place: 'Serdiana, 薩丁尼亞', type: '家族名莊', tagline: '帶領薩丁尼亞走向世界的地標名莊',
    owner: 'Argiolas 家族（第三代）', image: null,
    story: `阿吉歐拉斯（Argiolas）是薩丁尼亞最具代表性的家族酒莊，1938 年由 Antonio Argiolas 創立於島嶼南部的 Serdiana，如今由家族第三代經營。Antonio 享壽逾百歲、見證薩丁尼亞葡萄酒從默默無聞走向國際，是島上的傳奇人物。

讓 Argiolas 真正揚名世界的，是 1988 年首釀的旗艦紅酒「Turriga」——以薩丁尼亞原生品種 Cannonau（即 Grenache）為主，並請來義大利傳奇釀酒顧問 Giacomo Tachis（也是 Sassicaia、Tignanello 的推手）操刀，多次拿下 Gambero Rosso 最高榮譽三只酒杯，奠定了薩丁尼亞頂級紅酒的地標地位。

酒莊堅持以島上原生品種為核心：紅有 Cannonau、Carignano，白有 Vermentino、Nasco 等，把地中海陽光、海風與灌木叢的香氣釀進酒裡。從入門的 Costamolino、進階的 Is Argiolas，到旗艦 Turriga，Argiolas 是認識「薩丁尼亞海島風土」最可靠的名字。台灣由越昇國際代理。`,
    signature: [
      { name: `Turriga Isola dei Nuraghi IGT`, note: `酒莊旗艦 icon 紅酒，以原生 Cannonau 為主、由傳奇顧問 Giacomo Tachis 打造，多次榮獲 Gambero Rosso 三只酒杯，是薩丁尼亞紅酒的世界級代表。` },
      { name: `"Is Argiolas" Vermentino di Sardegna DOC`, note: `Vermentino 的進階款，老藤晚收＋酒渣陳釀，酒體飽滿、帶海風鹹礦與地中海香草（正是你收的這支）。` },
      { name: `"Costamolino" Vermentino di Sardegna DOC`, note: `酒莊最暢銷的入門 Vermentino，清爽柑橘花香、鹹鮮俐落，CP 值高的日常海島白酒。` },
      { name: `"Costera" Cannonau di Sardegna DOC`, note: `以薩丁尼亞原生紅 Cannonau（Grenache）釀成，紅果、香料與地中海草本，柔順好入口的島嶼代表紅酒。` },
    ],
  },
];

export function producerByKey(key) {
  return PRODUCERS.find(p => p.key === key) || null;
}
