// 我的品飲清單
// 新增酒款只要往陣列裡塞一筆。所有欄位都會自動帶到 UI。
// id 必填且唯一；image 留 null 會用 SVG 酒瓶插畫，填 URL 會用照片。
//
// style_axis：風格光譜（主觀定位）。0 = 國際風格 / 高度標準化，
//   100 = 風土個性 / 反標準化。新增酒款時憑感覺給個 0–100 就好。
// style_note：一句話說明為什麼放在這個位置（modal 詳情頁會顯示）。

export const drinks = [
  {
    id: 'lambrusco-sorbara',
    category: 'wine',
    type: 'sparkling-red',
    type_zh: '氣泡紅酒',
    name_en: 'Lambrusco di Sorbara',
    name_zh: '蘭布魯斯科',
    producer: 'Cantina della Volta',
    varietal: 'Lambrusco',
    varietal_zh: '蘭布魯斯科',
    region: 'Emilia-Romagna',
    region_zh: '艾米利亞-羅馬涅',
    country: 'Italy',
    country_zh: '義大利',
    year: 2022,
    abv: 11.5,
    price_tier: '$',
    rating: 4,
    tasting_date: '2026-04-10',
    occasion: '週末晚餐',
    aroma: ['野莓', '櫻桃', '紫羅蘭'],
    palate: ['輕盈', '微氣泡', '活潑酸度'],
    finish: '清爽收尾，回甘帶櫻桃韻味',
    pairing: ['義式火腿', '披薩', '帕瑪森乳酪'],
    notes_short: '入門最友善的氣泡紅，冰過喝最棒',
    notes_long: '沒有單寧的乾澀感，氣泡像氣泡水一樣輕鬆。第一次喝紅酒覺得「太澀了」的人，這支會打開新世界。冰桶冰到 8°C 左右最好喝。',
    color_hex: '#722F37',
    beginner_friendly: true,
    style_axis: 72,
    style_note: '原生品種 Lambrusco di Sorbara＋傳統瓶中二次發酵，做的是產地的老派風格，不走國際討喜路線——偏風土那一端。',
    image: null,
  },
  {
    id: 'prosecco-doc',
    category: 'wine',
    type: 'sparkling-white',
    type_zh: '氣泡白酒',
    name_en: 'Prosecco DOC Brut',
    name_zh: '普羅賽柯',
    producer: 'La Marca',
    varietal: 'Glera',
    varietal_zh: '格雷拉',
    region: 'Veneto',
    region_zh: '威尼托',
    country: 'Italy',
    country_zh: '義大利',
    year: 2023,
    abv: 11,
    price_tier: '$',
    rating: 4,
    tasting_date: '2026-03-15',
    occasion: '朋友聚會',
    aroma: ['青蘋果', '西洋梨', '白花'],
    palate: ['清爽', '細緻氣泡', '微甜'],
    finish: '乾淨俐落，回韻清新',
    pairing: ['輕食', '海鮮', 'Brunch'],
    notes_short: '比香檳輕鬆、比氣泡水有靈魂',
    notes_long: '任何時候開都不會錯。氣泡比香檳細，酸度比 Cava 溫和，價格友善。完美的開場酒。冰透了喝。',
    color_hex: '#E8D9A8',
    beginner_friendly: true,
    style_axis: 22,
    style_note: 'La Marca 是大廠規模、基本款 Prosecco DOC，Charmat 槽中法主打穩定一致——這正是工業化標準化的那一端。',
    image: null,
  },
  {
    id: 'cabernet-chile',
    category: 'wine',
    type: 'red',
    type_zh: '紅酒',
    name_en: 'Casillero del Diablo Cabernet Sauvignon',
    name_zh: '紅魔鬼 卡本內蘇維濃',
    producer: 'Concha y Toro',
    varietal: 'Cabernet Sauvignon',
    varietal_zh: '卡本內蘇維濃',
    region: 'Central Valley',
    region_zh: '中央山谷',
    country: 'Chile',
    country_zh: '智利',
    year: 2021,
    abv: 13.5,
    price_tier: '$',
    rating: 3,
    tasting_date: '2026-02-28',
    occasion: '配晚餐牛排',
    aroma: ['黑醋栗', '雪茄盒', '青椒'],
    palate: ['中等酒體', '單寧明顯', '果味直接'],
    finish: '中等長度，帶巧克力尾韻',
    pairing: ['牛排', '紅醬義大利麵', '硬質乳酪'],
    notes_short: '便利商店也買得到的可靠紅酒',
    notes_long: '智利 Cabernet 是入門紅酒最穩的選擇。沒有舊世界的複雜，但果味乾淨、結構清晰。配牛排不會出錯。',
    color_hex: '#4A0E1F',
    beginner_friendly: true,
    style_axis: 12,
    style_note: '智利大量產的國際風卡本內，乾淨果味、好複製、全球通路都買得到——「哪裡做都差不多」的標準化代表。',
    image: null,
  },
  {
    id: 'sauvignon-blanc-nz',
    category: 'wine',
    type: 'white',
    type_zh: '白酒',
    name_en: 'Cloudy Bay Sauvignon Blanc',
    name_zh: '雲霧之灣 白蘇維濃',
    producer: 'Cloudy Bay',
    varietal: 'Sauvignon Blanc',
    varietal_zh: '白蘇維濃',
    region: 'Marlborough',
    region_zh: '馬爾堡',
    country: 'New Zealand',
    country_zh: '紐西蘭',
    year: 2023,
    abv: 13,
    price_tier: '$$',
    rating: 5,
    tasting_date: '2026-04-22',
    occasion: '配生蠔',
    aroma: ['百香果', '青草', '葡萄柚'],
    palate: ['高酸', '清脆', '熱帶水果'],
    finish: '酸度悠長，回甘像青蘋果',
    pairing: ['生蠔', '海鮮沙拉', '檸檬醃魚'],
    notes_short: '紐西蘭的招牌，酸到讓人精神',
    notes_long: '經典的 Marlborough Sauvignon Blanc。一打開酒杯整個房間都是百香果香。冰透喝，配海鮮絕配。',
    color_hex: '#E8F0C8',
    beginner_friendly: true,
    style_axis: 30,
    style_note: 'Marlborough 白蘇維濃本身就是被全世界複製的「國際 SB 模板」，Cloudy Bay 又是定義這風格的品牌——有產區辨識度，但高度標準化。',
    image: null,
  },
  {
    id: 'rose-provence',
    category: 'wine',
    type: 'rose',
    type_zh: '粉紅酒',
    name_en: 'Whispering Angel Rosé',
    name_zh: '低語天使',
    producer: "Château d'Esclans",
    varietal: 'Grenache Blend',
    varietal_zh: '格那希混釀',
    region: 'Provence',
    region_zh: '普羅旺斯',
    country: 'France',
    country_zh: '法國',
    year: 2023,
    abv: 13,
    price_tier: '$$',
    rating: 4,
    tasting_date: '2026-05-05',
    occasion: '夏天午後',
    aroma: ['草莓', '玫瑰', '柑橘皮'],
    palate: ['乾型', '輕盈', '礦物感'],
    finish: '優雅、不甜膩',
    pairing: ['沙拉', '壽司', '夏日水果'],
    notes_short: '優雅的乾型粉紅，不是便利商店那種甜膩玫瑰紅',
    notes_long: '普羅旺斯的代表作。粉紅酒不一定甜，這支證明粉紅可以非常乾、非常優雅。冰桶必備。',
    color_hex: '#F5B5C5',
    beginner_friendly: true,
    style_axis: 45,
    style_note: '普羅旺斯乾型粉紅有鮮明產區風格，但 Whispering Angel 是把這風格商品化、被全球模仿的大品牌——兩端拉鋸，落在中間偏國際。',
    image: null,
  },
  {
    id: 'bordeaux-cantemerle',
    category: 'wine',
    type: 'red',
    type_zh: '紅酒',
    name_en: 'Château Cantemerle',
    name_zh: '坎特美樂城堡',
    producer: 'Château Cantemerle',
    varietal: 'Merlot Blend',
    varietal_zh: '梅洛混釀',
    region: 'Haut-Médoc, Bordeaux',
    region_zh: '上梅多克，波爾多',
    country: 'France',
    country_zh: '法國',
    year: 2019,
    abv: 13,
    price_tier: '$$$',
    rating: 4,
    tasting_date: '2026-01-10',
    occasion: '生日',
    aroma: ['黑莓', '雪松', '皮革'],
    palate: ['圓潤單寧', '結構完整', '層次明顯'],
    finish: '悠長，帶煙燻與咖啡尾韻',
    pairing: ['烤羊排', '燉牛肉', '熟成乳酪'],
    notes_short: '第一支讓我覺得「啊這就是法國紅酒」的酒',
    notes_long: '波爾多左岸的列級酒莊。比智利那種直球紅酒多了好多層次——皮革、雪松、煙燻一波波出來。需要醒酒 30 分鐘。',
    color_hex: '#3A0A18',
    beginner_friendly: false,
    style_axis: 82,
    style_note: '波爾多列級酒莊、傳統混釀與嚴格產區法規——它是「被全世界模仿的原型」而不是模仿者，風土個性強。',
    image: null,
  },
  {
    id: 'pinot-nero-eppan',
    category: 'wine',
    type: 'red',
    type_zh: '紅酒',
    name_en: 'St. Michael-Eppan Pinot Nero',
    name_zh: '聖米歇爾-艾本 黑皮諾',
    producer: 'St. Michael-Eppan',
    varietal: 'Pinot Nero',
    varietal_zh: '黑皮諾',
    region: 'Alto Adige',
    region_zh: '上阿迪杰',
    country: 'Italy',
    country_zh: '義大利',
    year: 2023,
    abv: 13.5,
    price_tier: '$$',
    rating: null,
    tasting_date: '2026-06-02',
    occasion: '購入評估',
    aroma: ['紅櫻桃', '覆盆子', '紫羅蘭', '黑莓', '些許香料'],
    palate: ['中等酒體', '單寧細柔', '酸度清爽'],
    finish: '柔順收尾，紅果與淡淡香料尾韻',
    pairing: ['烤雞', '滷肉', '菇類料理', '鮭魚生魚片'],
    notes_short: '義大利最強黑皮諾產區的可靠大牌，入門紅酒天花板',
    notes_long: '尚未實際品飲，評分留白，等我自己喝過再打。上阿迪杰是公認義大利最會做黑皮諾的產區，St. Michael-Eppan 是當地頗受敬重的頂級合作社。這支是入門的「Classic」系列（不是頂級 Sanct Valentin 珍藏版）。黑皮諾單寧細柔、酸度清爽，是最好入口的紅酒之一，還能稍微冰一下喝，很適合台灣天氣。現在就好喝，建議 2027–28 年前享用。價格上 NT$1,200 落在合理進口價帶內、甚至偏低，買起來不虧——但好不好喝，等我自己的舌頭說了算。',
    color_hex: '#9E2B3C',
    beginner_friendly: true,
    style_axis: 60,
    style_note: '黑皮諾是最國際化的紅葡萄，但上阿迪杰的高山冷涼風土辨識度高，加上頂級合作社的大木桶傳統釀法——兩股力量拉鋸，落在中間略偏風土。',
    image: null,
  },
  {
    id: 'barbera-nizza-carretta',
    category: 'wine',
    type: 'red',
    type_zh: '紅酒',
    name_en: 'Tenuta Carretta Bricco Manera',
    name_zh: '卡蕾塔 巴貝拉 馬內拉園',
    producer: 'Tenuta Carretta',
    varietal: 'Barbera',
    varietal_zh: '巴貝拉',
    region: 'Nizza, Piedmont',
    region_zh: '尼薩',
    country: 'Italy',
    country_zh: '義大利',
    year: 2020,
    abv: 14.5,
    price_tier: '$$',
    rating: null,
    tasting_date: '2026-06-02',
    occasion: '購入評估',
    aroma: ['黑櫻桃', '李子', '香草', '咖啡', '可可'],
    palate: ['飽滿酒體', '單寧柔軟', '櫻桃酸度明亮'],
    finish: '悠長，帶香料與可可尾韻',
    pairing: ['紅燒肉', '牛肉麵', '烤香腸', '熟成硬乳酪'],
    notes_short: '巴貝拉最高等級 Nizza，低單寧、多汁、超下飯',
    notes_long: '尚未實際品飲，評分留白，等我自己喝過再打。Nizza DOCG 是巴貝拉的最高等級，Bricco Manera 是卡蕾塔的單一園（標準款，不是珍藏版 Mora di Sassi）；酒莊是皮埃蒙特超過五百年的老牌名莊。巴貝拉的招牌是「低單寧＋多汁酸度」，順口又下飯，加上橡木桶的香草、咖啡、可可層次更有深度；但酒精偏高（約 14.5%），建議配餐喝。現在就好喝，可放到 2028–30 年。價格上 NT$1,300 落在合理價帶的中上段，公道但不算撿便宜——好不好喝，留給我自己評。',
    color_hex: '#6E1530',
    beginner_friendly: true,
    style_axis: 70,
    style_note: '原生於皮埃蒙特的巴貝拉、最高等級 Nizza 單一園、五百年老莊——風土個性強；現代法國橡木桶的打磨讓它稍微往國際討喜靠一點。',
    image: null,
  },
  {
    id: 'arneis-cayega-carretta',
    category: 'wine',
    type: 'white',
    type_zh: '白酒',
    name_en: 'Cayega Roero Arneis',
    name_zh: '卡蕾塔 卡耶加 阿內斯',
    producer: 'Tenuta Carretta',
    varietal: 'Arneis',
    varietal_zh: '阿內斯',
    region: 'Roero, Piedmont',
    region_zh: '羅埃羅',
    country: 'Italy',
    country_zh: '義大利',
    year: 2023,
    abv: 13.5,
    price_tier: '$$',
    rating: null,
    tasting_date: '2026-06-02',
    occasion: '購入評估',
    aroma: ['西洋梨', '白桃', '柑橘', '白花', '礦石'],
    palate: ['乾型圓潤', '酸度清爽', '礦物尾韻'],
    finish: '乾淨清爽，礦物與柑橘回韻',
    pairing: ['清蒸魚', '生魚片', '鹽水蝦', '清爽海鮮'],
    notes_short: '皮埃蒙特軟順白酒，海鮮絕配、超好入口',
    notes_long: '尚未實際品飲，評分留白，等我自己喝過再打。阿內斯是皮埃蒙特的原生白葡萄，曾差點絕種、靠卡蕾塔等酒莊救回。Cayega 是不鏽鋼槽、不過桶的單一園版本（頂級過桶版是 Canorei 珍藏版），風格清新。乾型但柔順，果香（西洋梨、白桃）花香明顯、無橡木味，是最好入口的白酒之一，配台式海鮮、清蒸魚、生魚片絕配。要趁年輕喝，建議 2027 年前喝完、冰到 8–10°C。價格上 NT$1,100 在合理價帶頂端，看到 NT$900 上下更值得入手——至於喜不喜歡，我說了算。',
    color_hex: '#E6DCA2',
    beginner_friendly: true,
    style_axis: 73,
    style_note: '阿內斯是皮埃蒙特近乎絕種、被在地酒莊救回的原生白葡萄，單一園、不過桶、產區極小——非常風土；清爽討喜的風格讓它依然好親近。',
    image: null,
  },
  {
    id: 'taiwan-beer-classic',
    category: 'beer',
    type: 'beer-pale',
    type_zh: '拉格啤酒',
    name_en: 'Taiwan Beer Classic',
    name_zh: '台灣啤酒 經典',
    producer: '台灣菸酒',
    varietal: 'Lager',
    varietal_zh: '拉格',
    region: '台灣',
    region_zh: '台灣',
    country: 'Taiwan',
    country_zh: '台灣',
    year: null,
    abv: 4.5,
    price_tier: '$',
    rating: 4,
    tasting_date: '2026-05-20',
    occasion: '熱炒店',
    aroma: ['麥芽', '蓬萊米', '微花香'],
    palate: ['清爽', '碳酸明顯', '微甜'],
    finish: '清爽收尾，無苦韻',
    pairing: ['熱炒', '鹹酥雞', '滷味'],
    notes_short: '台灣味的記憶，配熱炒永遠不會錯',
    notes_long: '用蓬萊米一起釀，所以特別清爽。配熱炒、配滷味、配台式小吃就是對的。冰到結霜的程度最好喝。',
    color_hex: '#F5C148',
    beginner_friendly: true,
    style_axis: 42,
    style_note: '大廠拉格，但加了台灣蓬萊米的在地配方，比純國際大廠拉格多了一點地方個性。',
    image: null,
  },
  {
    id: 'heineken',
    category: 'beer',
    type: 'beer-pale',
    type_zh: '皮爾森啤酒',
    name_en: 'Heineken',
    name_zh: '海尼根',
    producer: 'Heineken',
    varietal: 'Pilsner',
    varietal_zh: '皮爾森',
    region: 'Zoeterwoude',
    region_zh: '佐特爾沃德',
    country: 'Netherlands',
    country_zh: '荷蘭',
    year: null,
    abv: 5,
    price_tier: '$',
    rating: 4,
    tasting_date: '2026-04-30',
    occasion: '夏天陽台',
    aroma: ['麥芽', '青草', '一絲花香'],
    palate: ['乾爽', '苦韻明顯', '中等碳酸'],
    finish: '苦尾乾淨',
    pairing: ['炸物', 'BBQ', '披薩'],
    notes_short: '全世界都認識的經典皮爾森',
    notes_long: '皮爾森啤酒的全球代表。乾爽、有層次、不會喝膩。配什麼都不會錯。',
    color_hex: '#E8B850',
    beginner_friendly: true,
    style_axis: 8,
    style_note: '全球化大廠皮爾森的定義級產品，追求世界各地口味一致——標準化的極端。',
    image: null,
  },
  {
    id: 'asahi-super-dry',
    category: 'beer',
    type: 'beer-pale',
    type_zh: '日式米拉格',
    name_en: 'Asahi Super Dry',
    name_zh: '朝日 Super Dry',
    producer: 'Asahi',
    varietal: 'Rice Lager',
    varietal_zh: '米拉格',
    region: 'Tokyo',
    region_zh: '東京',
    country: 'Japan',
    country_zh: '日本',
    year: null,
    abv: 5,
    price_tier: '$',
    rating: 4,
    tasting_date: '2026-05-12',
    occasion: '日本料理',
    aroma: ['白米', '麥芽', '一絲檸檬'],
    palate: ['極乾', '俐落', '低苦'],
    finish: '乾淨無餘味',
    pairing: ['壽司', '燒鳥', '日式定食'],
    notes_short: '日本人發明的 Karakuchi 乾爽路線',
    notes_long: '日本米啤酒的代表，比歐洲拉格更乾、更俐落。配日本料理是天作之合。',
    color_hex: '#F0D478',
    beginner_friendly: true,
    style_axis: 16,
    style_note: '日本大廠 karakuchi 乾爽拉格，全球統一規格、可大量複製——偏國際標準化。',
    image: null,
  },
  {
    id: 'taihu-honey-lager',
    category: 'beer',
    type: 'beer-craft',
    type_zh: '精釀啤酒',
    name_en: 'Taihu Honey Lager',
    name_zh: '臺虎 蜜蜂工坊',
    producer: '臺虎精釀',
    varietal: 'Honey Lager',
    varietal_zh: '蜂蜜拉格',
    region: '台北',
    region_zh: '台北',
    country: 'Taiwan',
    country_zh: '台灣',
    year: null,
    abv: 5,
    price_tier: '$$',
    rating: 5,
    tasting_date: '2026-05-18',
    occasion: '精釀酒吧',
    aroma: ['龍眼蜜', '麥芽', '柑橘'],
    palate: ['圓潤', '蜜甜', '中等苦'],
    finish: '蜜甜回韻，溫柔',
    pairing: ['炸物', '燒烤', '甜點'],
    notes_short: '台灣精釀代表，蜂蜜香超明顯',
    notes_long: '用台灣本土龍眼蜜釀的拉格，香氣超明顯但不會太膩。台灣精釀的入門首選。',
    color_hex: '#D4A848',
    beginner_friendly: true,
    style_axis: 80,
    style_note: '台灣精釀，用本土龍眼蜜的獨家配方，小批次、強調在地個性——明確的反標準化。',
    image: null,
  },
];

// 類型 → 中文 + 顏色（給篩選器跟圖表用）
export const typeMeta = {
  'sparkling-red':   { zh: '氣泡紅', accent: '#7A2024', group: 'sparkling' },
  'sparkling-white': { zh: '氣泡白', accent: '#B89A5E', group: 'sparkling' },
  'red':             { zh: '紅酒',   accent: '#5C1A1B', group: 'red' },
  'white':           { zh: '白酒',   accent: '#A8924E', group: 'white' },
  'rose':            { zh: '粉紅酒', accent: '#93515C', group: 'rose' },
  'beer-pale':       { zh: '淺色啤酒', accent: '#B68A3E', group: 'beer' },
  'beer-dark':       { zh: '深色啤酒', accent: '#5A3A22', group: 'beer' },
  'beer-craft':      { zh: '精釀啤酒', accent: '#8A6A3A', group: 'beer' },
};

// 風格光譜的兩端標籤（給 modal 與圖表共用）
export const STYLE_AXIS_ENDS = {
  left:  { zh: '國際風格', en: 'International' },
  right: { zh: '風土個性', en: 'Terroir' },
};

// 把 0–100 的 style_axis 轉成一個分級標籤
export function styleAxisTier(v) {
  if (v == null) return null;
  if (v <= 22) return { zh: '國際風格', en: 'International' };
  if (v <= 42) return { zh: '偏國際',   en: 'Leans Intl' };
  if (v <= 58) return { zh: '兼具',     en: 'Balanced' };
  if (v <= 78) return { zh: '偏風土',   en: 'Leans Terroir' };
  return { zh: '風土個性', en: 'Terroir' };
}
